### ISSUE TITLE
Update List of Supported Models `Clustering.jl` Section

### ISSUE THREAD

**Issue by john-waczak** [alan-turing-institute/MLJ.jl#1000]
Currently, the dev version of the docs only show `KMeans` and `KMedoids` as supported models. MLJClusteringInterface.jl has interfaces for both `DBSCAN` and `HierarchicalClustering` models that appear to be in the model registry. We should update the docs to make these more discoverable.

**Comment by ablaom** [comment]
CONGRATULATIONS ON OPENING THE 1000th issue on MLJ!!

**Comment by john-waczak** [comment]
Had to snatch up #1000!
