### ISSUE TITLE
Something not right with bubbles in tuning plots. 

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#103]
The following is generated by MLJ/examples/random_forest.jl

It seems to me that the bubbles  ought to be different sizes, no?

![random_forest_tuning](https://user-images.githubusercontent.com/30517088/54426206-286fae00-470f-11e9-9319-24f03515fbbf.png)

@mkborregaard Is this the intended behaviour?

**Comment by mkborregaard** [comment]
Oh but they are different sizes. Just not very much, because the numbers are similar

**Comment by mkborregaard** [comment]
Any suggestions for a size transformation?

**Comment by ablaom** [comment]
I would rescale bubble radius linearly so that smallest value is almost zero and largest value is about 2/3 the grid size.

**Comment by mkborregaard** [comment]
That will remove any information as to the absolute magnitude of differences. All plots would have the dame perceived gradient regardless of actual steepness. Just consider that now, the colours give relative differences, whereas sizes give absolute. That's a nice duality I think. It do you not care about absolute value at all?

**Comment by ablaom** [comment]
No, not really.

I do see your point, and the present implemetation conveys more information, as you say. The problem I have is this: I want to know, in a single glance (i) where to refine my grid search, and (ii) how much relative "noise" is there in the estimates.  The colours do encode this information, but I have to first interpret the color legend. In contrast, rescaled bubble sizes are  *immediately* interpretable. 

Because we omit estimates of uncertainty in our plot, we cannot in any case regard the plot as a complete summary of the tuning outcome, and I think only the most naive user would do so. This is just a diagnostic tool, no?

However, if you are not convinced by these arguments, please just leave it for now, many thanks!

**Comment by mkborregaard** [comment]
You're the boss, just laying out my considerations 😊

**Comment by ablaom** [comment]
Okay, after some further musings, I would like you to go ahead with the bubble size rescaling. The absolute value information is not lost, as it can be inferred from the colour scale. And, in my reading, rescaling the bubbles was the consensus request in #85.

**Comment by fkiraly** [comment]
(I still find bubble plots weird, just in general, but don't mind me)

**Comment by mkborregaard** [comment]
You can just `heatmap(model) ` instead of `plot(model) `.

**Comment by fkiraly** [comment]
(@mkborregaard thank you so much)

**Comment by ablaom** [comment]
@mkborregaard Sorry to bother you, but is this change still on your radar?

**Comment by mkborregaard** [comment]
Hi, it's fine with a reminder. I'm simply swamped with work, but that's normal so I might as well get on it :-)
