### ISSUE TITLE
SymbolicRegression.jl — registry update

### ISSUE THREAD

**Issue by MilesCranmer** [alan-turing-institute/MLJ.jl#1032]
Just letting you know that SymbolicRegression v0.20.0 has been released with MLJ support, so please feel free to update the registry when you get a chance.

Here are the docs on the new regressors: https://astroautomata.com/SymbolicRegression.jl/stable/api/#MLJ-interface

Thanks @OkonSamuel and @ablaom for your help!

Best,
Miles

**Comment by ablaom** [comment]
Thanks for this MileCranmer. 

To update MLJ's docuemtation, we still  need to:

- [ ] Add the models to the "Model Browser" by updating [this dictionary].
- [ ] Add the models to [this list](https://github.com/alan-turing-institute/MLJ.jl/blob/dev/docs/src/list_of_supported_models.md).

@OkonSamuel

**Comment by ablaom** [comment]
I think it's fine to do this at the same time as the new SIRIUS models, when they are ready,
