### ISSUE TITLE
Doc generation is failing silently

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#1045]
https://github.com/alan-turing-institute/MLJ.jl/actions/runs/5993524023/job/16254036811?pr=1044#step:6:812

To do:

- [x] Fix the "silence" of fail
- [ ] Fix the cause of fail

**Comment by DilumAluthge** [comment]
You likely want to set `strict = true` in the `makedocs` function. This should cause the failure to be visible (rather than silent).

**Comment by ablaom** [comment]
Thanks for the suggestion. Sadly, we have that already, no?

https://github.com/alan-turing-institute/MLJ.jl/blob/7c677a2f28a41b426aa6c80ff3cc823912661f73/docs/make.jl#L117
