### ISSUE TITLE
Add AutoEncoderMLJ model (part of BetaML)

### ISSUE THREAD

**Issue by sylvaticus** [alan-turing-institute/MLJ.jl#1074]
Hello, I have added to BetaML a model to use a [AutoEncoder](https://sylvaticus.github.io/BetaML.jl/stable/Utils.html#BetaML.Utils.AutoEncoder) in a very simple way from the end user prospective, without the need to understand the underlying neural network.
I have also created a MLJ wrapper, [`AutoEncoderMLJ`](https://sylvaticus.github.io/BetaML.jl/stable/Utils.html#BetaML.Utils.AutoEncoderMLJ). As this is my first transformer for MLJ, could you please check that the wrapper is fine and eventually add  it to the MLJ registry ? 

Thank you :-)

**Comment by ablaom** [comment]
Thanks @sylvaticus for adding the wrapper.  It's mostly good. 

Main thing is that 

```julia
mutable struct AutoEncoderMLJ <: MLJModelInterface.Deterministic
```
 should be 

```julia
mutable struct AutoEncoderMLJ <: MLJModelInterface.Unsupervised
```

Having "MLJ" in the name is unfortunate. Perhaps you put the interface in  a submodule to prevent name conflict with `AutoEncoder`? If you do that, you need to need to amend the load path at https://github.com/sylvaticus/BetaML.jl/blob/38074a9207ba36bd3427bc31eef42f7b990d1ac8/src/Utils/Utils_MLJ.jl#L159

The doc string is great but not [strictly compliant](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#Document-strings). There are examples for transformers (`Unsupervised` models) at the end of [this page](https://github.com/JuliaAI/MLJModels.jl/blob/dev/src/builtins/Transformers.jl).

There's no need to implement `predict` for  `Unsupervised` models. 

Feel free to add the following interface test, but that's up to you:

```julia
import BetaML
using MLJTestInterface

@testset "generic mlj interface test" begin
    fails, summary = MLJTestInterface.test(
        [BetaML.Utils.AutoEncoderMLJ,],
        MLJTestInterface.make_regression()[1];
        mod=@__MODULE__,
        verbosity=0, # bump to debug
        throw=false, # set to true to debug
    )
    @test isempty(failures)
end
```

**Comment by ablaom** [comment]
FYI I have just updated the MLJ Model Registry which has automatically added this model - my mistake. I don't think that's a big deal, but do let me know as soon as you have fixed `Deterministic -> Unsupervised` so I can update the registry again.

**Comment by sylvaticus** [comment]
yes, I am working on it... I didn't yet asked your opinion as I didn't yet
tested it (and haven't touched the doc).

Thank you for the suggestion about submodules, I will be able to use the
same name for native and MLJ interface models, although this is breaking....

Antonello

**Comment by sylvaticus** [comment]
I have fixed the `Deterministic` -> `Unsupervised` issue and changed its name to `AutoEncoder` by setting the MLJ in its own submodule `BetaML.Bmlj`.

`MLJTestInterface.test` passes, but I am still unsure about `MLJModelInterface.metadata_pkg`.. there ([at the end of /src/BetaML.jl file](https://github.com/sylvaticus/BetaML.jl/blob/f6f504ea1e627c340e3e0f986627e68e6e0218dc/src/BetaML.jl#L68)) I use `Bmlj.AutoEncoder`, is it fine like that ?

**Comment by ablaom** [comment]
> MLJTestInterface.test passes, but I am still unsure about MLJModelInterface.metadata_pkg.. there ([at the end of /src/BetaML.jl file](https://github.com/sylvaticus/BetaML.jl/blob/f6f504ea1e627c340e3e0f986627e68e6e0218dc/src/BetaML.jl#L68)) I use Bmlj.AutoEncoder, is it fine like that ?

I'm not completely sure I understand the question, but I do see that the package-related metadata is getting defined for Bmlj.AutoEncoder:

```julia
julia> package_name(BetaML.Bmlj.AutoEncoder)
"BetaML"
```

Is that what you were worried about?

**Comment by sylvaticus** [comment]
Yes, is it fine like that?

**Comment by ablaom** [comment]
Yes. It looks good to me. The most important thing is that the load path is good and it is:

```julia
julia> load_path(BetaML.Bmlj.AutoEncoder)
"BetaML.Bmlj.AutoEncoder"
```

**Comment by ablaom** [comment]
Note to self: This issue is addressed on BetaML#master; waiting for next release (currently at 0.10.4).

**Comment by ablaom** [comment]
Congratulations on the refactor. 

This is issue can be closed after:

- [ ] https://github.com/JuliaAI/MLJModels.jl/issues/547
