### ISSUE TITLE
Add stratified sampling

### ISSUE THREAD

**Issue by harryscholes** [alan-turing-institute/MLJ.jl#108]
It would be very useful to add stratified sampling of observations, so that the class distributions of training and testing data are representative of the whole data set. Thanks in advance!

**Comment by ablaom** [comment]
Good idea.

**Comment by ysimillides** [comment]
https://github.com/alan-turing-institute/MLJBase.jl/pull/3

**Comment by ablaom** [comment]
This is ought to be a very easy now #206 is pulled. See under "Custom resampling strategies" at https://github.com/alan-turing-institute/MLJ.jl/blob/evaluate-rebased/docs/src/evaluating_model_performance.md 

Related:

- For the actual construction of train/evaluate pairs, could use: [MLDataUtils]https://mldatautilsjl.readthedocs.io/en/latest/data/pattern.html#stratified-sampling

- #188

**Comment by tlienart** [comment]
Bump, we should really have this @sjvollmer up for grabs?

**Comment by ablaom** [comment]
Oops. This ought to help. https://github.com/alan-turing-institute/MLJ.jl/pull/299
