### ISSUE TITLE
Add type coercion to task constructors

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#109]
Branching off from #68:

In the current design one of the functions of task constructors is to establish the scientific type of the data. This is currently inferred from the data passed to the constructors, according to the convention that object `x` has scientific type `scitype(x)`; see the [docs](https://alan-turing-institute.github.io/MLJ.jl/dev/) for details. 

At present, this information is simply inferred from the data passed to the constructor. I suggest the following straightforward enhancement: The user passes, as an optional kwarg, a dictionary explaining how they would like to overide this behaviour. The dictionary is keyed on the names of feature and target columns; the values are the intended scitypes. So, a call might look like this:

```julia
types = Dict(:overall_quality => FiniteOrderedFactor, :is_freehold => Binary, :Price => Continuous)
task = SupervisedTask(data=house_prices, is_probabilistic=true, target=:Price, scitypes=types)
```

After coercion, the constructor would print out the final post-coercion types and scitypes of all variables. 

I can provide more detail on the existing design to potential implementers.

Any objections, other ideas?

**Comment by ablaom** [comment]
Okay, no objections. Any volunteers?

Some technical details:

- current task constructors live in MLJBase/tasks.jl with detailed doc strings. 
- extension code is to to in MLJ/tasks.jl (**please don't touch MLJBase**). We are just adding a keyword argument to the signature.

**Comment by giordano** [comment]
In #114 I implemented the coercion methods as suggested, however the method `coerce(T::Continuous, y)` assumes that any numerical type can be converted to `Float64`, which is not true for any arbitrary custom type.  For example, the `Measurement` type from [`Measurements.jl`](https://github.com/JuliaPhysics/Measurements.jl) is a subtype of `AbstractFloat` but doesn't have a conversion rule to `Float64` for a good reason: it would be a lossy conversion.

**Comment by ablaom** [comment]
Done.
