### ISSUE TITLE
Wrap Scikitlearn.jl Elastic Net algorithms

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#112]
- [x] sklearn.linear_model.ElasticNet : this will be `ElasticNet <: Deterministic{Any}` , `target_type(::ElasticNet) = MLJBase.Continuous`, `input_types(::ElasticNet) = MLJBase.Continous`

- [x] sklearn.linear_model.ElasticNetCV: this will be `ElasticNetCV <: Deterministic{Any}`, with same target_type and input_types as above. Note the sklearn model has `verbose` as a hyperparameter, which we will drop from the MLJ model. The MLJ `fit` will pass either 0 or 1 to the sklearn fit, according to whether the MLJ fit `verbosity` is  <= 0 or > 0.

**Comment by ablaom** [comment]
Some extra details:

**ElasticNetCV**

- Return for the `report` a named tuple with keys `(:l1_ratio, :alpha, :dual_gap)` whose values are `fitresult.l1_ratio_`, `fitresult.alpha_`, and `fitresult.dual_gap_`.

- Define `fitted_params(::ElasticNetRegressor, fitresult)` to be named tuple with keys `(:intercept, :coef)` and values given by `fitresult.intercept_` and `fitresult.coef_`.

**Comment by ablaom** [comment]
Plain **ElasticNet**

- Return for the `report` a named tuple with keys `(:n_iter, :dual_gap)` whose values are `fitresult.l1_ratio_`, `fitresult.dual_gap_`.

- Define `fitted_params(::ElasticNet, fitresult)` to be named tuple with keys `(:intercept, :coef)` and values given by `fitresult.intercept_` and `fitresult.coef_`.

- The `clean!` method to set `alpha=1` if `alpha` is not strictly positive. It should set `l1_ratio=0` if `l1_ratio` is not in the interval `[0, 1]`.

**Comment by ValdarT** [comment]
Just out of curiosity.. Why wrap scikit-learn when Julia already has a wrapper around the original Fortran code (https://github.com/JuliaStats/GLMNet.jl) as well as a native Julia implementation (https://github.com/JuliaStats/Lasso.jl)?

**Comment by ablaom** [comment]
Yes, I am aware of Lasso.jl, having implemented [Koala's](https://github.com/ablaom/KoalaElasticNet.jl) interface for it. We doing the sklearn because it looked quick and easy for @ysimillides, who has already done some sk wraps, and (I am busy with other things). It also struck me that Lasso.jl needed a little TLC, although maybe that's changed?

If you were interested in doing implementations for GLMNet or Lasso, I'm very happy to provide guidance.

**Comment by ablaom** [comment]
done
