### ISSUE TITLE
Adopt and update XGBoost.jl wrappers

### ISSUE THREAD

**Issue by ChrisRackauckas** [alan-turing-institute/MLJ.jl#116]
XGBoost.jl is a very good part of any ML library. The library is currently under-maintained, with a lot of issues installing on Windows. I was wondering if this project would consider adopting some of the maintenance of XGBoost.jl and help fix some of the build issues, ideally update it to use BinaryBuilder. 

https://github.com/dmlc/XGBoost.jl/issues/64

**Comment by ViralBShah** [comment]
Perhaps @staticfloat might already have kicked off some BB work (but I am not fully sure).

**Comment by staticfloat** [comment]
Yes, status here: https://github.com/JuliaPackaging/Yggdrasil/issues/10#issuecomment-484678477

**Comment by ViralBShah** [comment]
I would love to add that usage of MLJ.jl is likely to greatly increase if we can use XGBoost.jl, given how popular it is.

**Comment by ablaom** [comment]
Thanks @ViralBShah for the spring cleaning at XGBoost.jl. I hope interest in maintenance can be revived. 

BTW, MLJ already supports XGBoost:

```julia
julia> using MLJ

julia> models()["XGBoost"]
3-element Array{Any,1}:
 "XGBoostCount"     
 "XGBoostRegressor" 
 "XGBoostClassifier"
```

See also this [example](https://github.com/alan-turing-institute/MLJ.jl/blob/master/examples/xgboost.jl). The MLJ implementation is a wrap of XGBoost.jl. 

If the MLJ team at Turing grows as hoped, we may be able to find someone to push maintenance of XGBoost.jl along.

**Comment by ViralBShah** [comment]
The immediate steps are to get it into BinaryBuilder and make the tests pass.

**Comment by aviks** [comment]
This should probably be closed now.

**Comment by OkonSamuel** [comment]
cc @ablaom. can this be closed?
