### ISSUE TITLE
MLJBase: scitype_union not working on large arrays

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#120]
On my laptop:

```
julia> scitype_union(rand(10000))
Continuous

julia> scitype_union(rand(100000))
Continuous

julia> scitype_union(rand(1000000))
ERROR: ReadOnlyMemoryError()

julia> 
```

While the precise source of this error needs investigating, this raises the issue that `scitype_union(A)` is currently quite inefficient. Currently it computes the union over every element of the iterable `A`, even in cases (such as this one) where the scitype can be inferred from `typeof(A)`. There is room for improving the fallback here. 

The most common example where `union_scitype(A)` cannot be inferred from `A` is when `A` is a CategoricalArray. In that case `typeof(A)` is missing the number of classes and whether or not the classes are ordered or not. That is, we don't know (from `typeof(A)` alone) if we are `Multiclass{N}` or `FiniteOrderedFactor{N}` and we don't know what the value of `N` is. However, this can be obtained from a single element (if we assume elements all have a common pool).

**Comment by ablaom** [comment]
This new definition seems to fix the error (although no more performant):

```
scitype_union(A) = reduce((a,b)->Union{a,b}, (scitype(el) for el in A))
```

**Comment by giordano** [comment]
I was thinking pretty much about something like that.

> although no more performant

I think it actually has good performance (`scitype_union` is on master branch, `f` is your proposed implementation):
```
julia> @btime scitype_union($(rand(10)));
  412.125 ns (2 allocations: 176 bytes)

julia> @btime scitype_union($(rand(100)));
  10.513 μs (2 allocations: 912 bytes)

julia> @btime scitype_union($(rand(1000)));
  600.033 μs (3 allocations: 15.89 KiB)

julia> @btime scitype_union($(rand(10000)));
  54.965 ms (4 allocations: 156.47 KiB)

julia> @btime scitype_union($(rand(100000)));
  5.571 s (4 allocations: 1.53 MiB)

julia> @btime scitype_union($(rand(1000000)));
ERROR: ReadOnlyMemoryError()

julia> @btime f($(rand(10)));
  425.377 ns (2 allocations: 32 bytes)

julia> @btime f($(rand(100)));
  4.479 μs (2 allocations: 32 bytes)

julia> @btime f($(rand(1000)));
  44.527 μs (2 allocations: 32 bytes)

julia> @btime f($(rand(10000)));
  444.368 μs (2 allocations: 32 bytes)

julia> @btime f($(rand(100000)));
  4.473 ms (2 allocations: 32 bytes)

julia> @btime f($(rand(1000000)));
  45.891 ms (2 allocations: 32 bytes)
```

It looks like current `scitype_union` is O(n^2) while the new proposal is O(n).

**Comment by ablaom** [comment]
Even better, then. Thanks!

**Comment by giordano** [comment]
Can I use this new implementation in https://github.com/alan-turing-institute/MLJBase.jl/pull/7?

**Comment by giordano** [comment]
Oh, no, it's already merged :sweat_smile:

**Comment by giordano** [comment]
Wait, I just tested on *current* master (I didn't pull after https://github.com/alan-turing-institute/MLJBase.jl/pull/7 was merged): there is basically no change of performance between *current* master and your proposed solution, so the current implementation is already as efficient and doesn't fail for a on-million-element array as well
