### ISSUE TITLE
Migrate MultivariateStats:  MLJ -> MLJModels

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#125]
Presently MLJ uses RidgeRegressor from MultilinearStats for testing purposes. I propose that we remove this test dependency on MutltilinearStats and move the LocalMultilinearStats module (presently at MLJ/src/builtins) out to MLJModels. We would first define a new local version of ridge regression `SimpleRidgeRegressor` for local testing.

Basic ridge regression is easy to implement and quick-and-dirty code already exists in the docs at [Simple User Defined Models](https://alan-turing-institute.github.io/MLJ.jl/dev/simple_user_defined_models/).

Let's separate this into several PR's. I'm only including detail on the first. I'll
add detail to the others later or do these myself.

- [x] &nbsp;

    - In a new file MLJ/builtins/ridge.jl dump the quick-and-dirty code from the docs and flush it out to make it "fully compliant" with the model spec, as given in the [guide](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/). No need to wrap this code in a module as we have done elsewhere. 

    - In the docs the model is called "MyRegressor". Rename the model "SimpleRidgeRegressor". Replace all instances of "RidgeRegressor" in MLJ/test/ with "SimpleRidgeRegressor". 

    - Add `include("builtins/ridge.jl")` to MLJ/src/MLJ.jl. Write test code for this SimpleRidgeRegressor (check reasonable performance on small set of synthetic linear data, with lambda=0).

- [x] Copy and adapt MLJ/src/builtins/LocalMultivarateStats.jl and MLJ/test/LocalMultivariateStats.jl to MLJModels (dropping the "local")

- [x] Remove LocalMultivariateStats code and tests from MLJ. Remove MultivariateStats pkg as dependency from MLJ.

- [x] Register MultivariateStats at MLJRegistry (@ablaom to do) and
test `@load RidgeRegressor`, etc works from MLJ.

- [ ] Check MLJ/examples/  for any instances of RidgeRegressor which need addition of `@load RidgeRegressor` to access the model (ie, re-run those notebooks with necessary changes). Nowhere in these examples should SimpleRidgeRegressor occur.

**Comment by ayush-1506** [comment]
@ablaom I'll start working on this. A small question, the fitresult of SimpleRidgeRegressor should be a `LinearFitresult` (similar to LocalMultivariateStats), or should I get rid of `LinearFitresult`?
(Removing it would mean adapting the tests accordingly.)

**Comment by ablaom** [comment]
Ah good point. This simple guy has no intercept! No matter, this is just for internal testing. No need for a struct, just return the the vector of coefficients as in the docs. We will hide this model from the general user.

**Comment by ablaom** [comment]
@ayush-1506 Could you please do that last check after MLJModels 0.2.2 is merged into General (pending [here](https://github.com/JuliaRegistries/General/pull/791))? Make sure you run the notebooks under the current MLJ/master (which no longer has RidgeRegressor built-in).  I did some of these but it would not hurt to check again.

**Comment by ablaom** [comment]
The last item on this list will be sorted when https://github.com/alan-turing-institute/MLJ.jl/issues/137 is sorted.
