### ISSUE TITLE
Goals and collaboration on tasks

### ISSUE THREAD

**Issue by gbohner** [alan-turing-institute/MLJ.jl#13]
In order to facilitate working with multiple project members we need to first:

1. Create a design document, that outlines APIs between the various parts of the package.
2. Create a working prototype (complete with installation and examples)

Then individual tasks could be assigned as:

1. Integration into julia package manager ( make it work with ```Pkg.Clone()``` for now, then think about optional dependencies, when requesting model implementation packages and adding them on the fly ).
2. Extension API and guidelines (incorporating new libraries as sub-models)
3. Model composition / tuning implementation

**Comment by gbohner** [comment]
Design decisions to discuss:

1. Data container (agnostic to specifics)
2. Task descriptions / Composition
3. Meta-learning (hyperparameter setting)
4. Model composition
5. Evaluation and diagnostics (simple set of available metrics, benchmarks, diagnostics plots)

**Comment by gbohner** [comment]
See the poster for a bit more details: https://github.com/alan-turing-institute/mlj/blob/master/material/MLJ-JuliaCon2018-poster.pdf

**Comment by dominusmi** [comment]
> Design decisions to discuss:
> 
> 1. Data container (agnostic to specifics)
> 2. Task descriptions / Composition
> 3. Meta-learning (hyperparameter setting)
> 4. Model composition
> 5. Evaluation and diagnostics (simple set of available metrics, benchmarks, diagnostics plots)

I think each of these deserves an issue otherwise it's going to be a bit of a mess on a single thread. We can also better set priority being set as independent
