### ISSUE TITLE
Announcing MLJ + sktime tutorial and development sprint

### ISSUE THREAD

**Issue by vollmersj** [alan-turing-institute/MLJ.jl#143]
We are interested in both Python or Julia users and machine-learning enthusiasts, and those with no prior experience, but who are keen to learn and try out our packages on **your use case** and give your honest feedback.

Travel to, and accommodation in London will be covered subject to successful application - *see funding conditions and further important details (here)[https://github.com/alan-turing-institute/MLJ.jl/wiki/2019-MLJ---sktime-tutorial-and-development-sprint]*.

The aim of this gathering is to:

- Conduct first-line user testing (e.g. **your use case**) of our latest stable version (beginners)

- Creation of tutorials, improvement of documentation (intermediate)

- Interface, implement or integrate models from other packages (intermediate)

- Implement new features in a coding sprint (advanced users)

- Work together and socialize with other members of the Julia and pydata communities (everyone!)

**The purpose of the issue is to discuss agenda and preparations.**

**Comment by swenkel** [comment]
What is the status of the sprint?

> Applicants will receive an acceptance / rejection letter by May 30 (London time).

I haven't received anything yet but a copy of the filled out form.

**Comment by fkiraly** [comment]
I believe @ysimillides was dealing with this?
@ysimillides? @sjvollmer? @ablaom?

If I remember correctly, the "julia@turing" address had the problem that you could not send to it without registration (mistakenly locked to outside senders). Perhaps it has to do with that?

**Comment by ysimillides** [comment]
Notifications have been sent out.
