### ISSUE TITLE
Use of MLJRegistry

### ISSUE THREAD

**Issue by aviks** [alan-turing-institute/MLJ.jl#165]
Is there any need for a separate MLJRegistry.jl repo?  I see a few issues with the current mechanism 

* Just managing three separate repos/issues/pull-requests will get annoying

* Doing network requests outside of a pkg install workflow will not allow this package to function in firewalled installations (or in other constrained environments)

Maybe the registry should be part of the main `MLJ.jl` repo, or the `MLJModels.jl` repo?

**Comment by ablaom** [comment]
The registry has been merged into MLJ.
