### ISSUE TITLE
Local support at the ATI?

### ISSUE THREAD

**Issue by sje30** [alan-turing-institute/MLJ.jl#169]
**Describe the solution you'd like**
Is anyone at the ATI involved in this project?  I'm giving an intro workshop on deep neural nets there in July (for phd students) and it would be useful if appropriate to higlight MLJ toolkit.  Is anyone around to help me get started? (I'm an ATI fellow)

**Comment by ablaom** [comment]
Are you wanting to meet ahead of your nn event, or around the same time? 

My current visit to Turing ends July 3rd, but one of @sjvollmer @fkiraly @tlienart should be able to meet with you after that, I imagine.

**Comment by sje30** [comment]
It would be great to meet in person if possible.  I'm actually around at ATI tomorrow -should be free about 1pm?

**Comment by fkiraly** [comment]
We're actually all in the dev sprint now
https://github.com/alan-turing-institute/MLJ.jl/wiki/2019-MLJ---sktime-tutorial-and-development-sprint
@ablaom should have sent you an e-mail with details

**Comment by vollmersj** [comment]
We are infact supported by core Turing funding and part of the Tools Practice and Systems program.
