### ISSUE TITLE
range(SVC, :gamma, ...) returns NominalRange instead of NumericRange

### ISSUE THREAD

**Issue by oleskiewicz** [alan-turing-institute/MLJ.jl#170]
**Describe the bug**
```julia
using MLJ
@load SVC
svc = SVC()
gamma_range = range(svc, :gamma, lower=0.5, upper=1.5, scale=:linear)
```

**Expected behavior**
A `NumericRange` should be returned.

**Additional context**
```julia
using MLJ
@load SVC
svc = SVC()
gamma_range = range(svc, :gamma, values=[0.5, 1.0, 1.5])
```

This works, because `Base.range` in `src/parameters.jl` implementation returns `NominalRange`.

**Versions**
<details>
Juliav1.1, MLJ.jl#master (5a18eee)
</details>

**Comment by oleskiewicz** [comment]
Fixed by #171, with a caveat that `svc` needs to be initialised with a numerical, not automatic `:gamma`:

```julia
using MLJ; @load SVC;
svc = SVC(gamma=0.5)
gamma_range = range(svc, :gamma, lower=0.5, upper=1.5, scale=:linear)
```

**Comment by ablaom** [comment]
I have stopped the offending mutation of model structs in the fit methods of LIBSVM, which should resolve this issue. 

@oleskiewicz Would you be so kind as to check this is fixed in your notebook and close this issue if all okay?

**Comment by ablaom** [comment]
oops, I see I need to merge your PR first. looking at that now
