### ISSUE TITLE
Fitting SVC machine changes hyperparameters

### ISSUE THREAD

**Issue by oleskiewicz** [alan-turing-institute/MLJ.jl#172]
**Describe the bug**

When running `fit!` dispatched on a machine containing the `SVC` model, its hyperparameter `gamma` is changed from a Symbol `:auto` to a best-guess Float64.

**To Reproduce**
```
julia> using MLJ; @load SVC; svc = SVC();
julia> params(svc)
(kernel = RadialBasis::KERNEL = 2,
 gamma = :auto,
 weights = nothing,
 cost = 1.0,
 degree = 3,
 coef0 = 0.0,
 tolerance = 0.001,
 shrinking = true,
 probability = false,)
julia> task = load_iris(); mach = machine(svc, task); fit!(mach);
julia> params(svc)
(kernel = RadialBasis::KERNEL = 2,
 gamma = 0.25,
 weights = nothing,
 cost = 1.0,
 degree = 3,
 coef0 = 0.0,
 tolerance = 0.001,
 shrinking = true,
 probability = false,)
```

**Additional context**

The value is set when calling [`fit`](https://github.com/alan-turing-institute/MLJModels.jl/blob/be45bfce8e38f14501ab172424373b46b64c922f/src/LIBSVM.jl#L353).

**Comment by fkiraly** [comment]
Interesting case - I think there are two solutions:
(a) have a fittable "gamma-estimate" parameter which is set when the `:auto` parameter is given. If gamma is set to sth concrete, then "gamma-estimate" and "gamma" are equal
(b) have two learning strategies: one where gamma is fit, and it's not a hyper-parameter; one where it is a hyper-parameter but needs to be a number.

**Comment by ablaom** [comment]
fit methods are forbidden to change hyperparameters (RNG's excepted). 
problem fixed by making copy before sending to wrapped model fit

**Comment by ablaom** [comment]
Okay.
