### ISSUE TITLE
Flaw in the use of input_scitype_union, and so forth

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#176]
There is a flaw in the use of input_scitype_union, and so forth in matching models to data (tasks). Essentially, I have inadvertently confused  *type* unions and *set* unions. Without going into detail here, this becomes an issue in the case of tabular data having a column of mixed scitype, the most common case being a mixture of an "atomic" scitype (such as `Continuous`) and `Missing`. 

I thank @fkiraly for bringing this to my attention.

As we are planning some changes to the scitype implementation anyway, I suggest implementing the fix at the same time.

**Comment by fkiraly** [comment]
Some silly prototype code for `scitype` of data containers which may or may not be useful in general.
(don't want to PR but may help as a design study and/or for use of union in representation of set union of scitypes within a composite scitype, vs type union of scitypes)

```julia

#=
    scitype(X :: DataFrames.DataFrame)

    Arguments: a data frame X of type DataFrames.DataFrame 
    Output: the scitype of X, which is a parametric struct type 
                    fields: nrows :: Int - number of rows of X
                            schema :: NamedTuple - ordered column scitype schema of X
                                        keys = column names, entries = column types
                            colscitypes :: Set - set union of scitypes occurring in schema

=#

struct scitype_DataFrame{T <: NamedTuple} <: Found
    nrows :: Int
    schema :: T
    colscitypes
end

function Base.show(io::IO, dfst::scitype_DataFrame)
    print("data frame with ",dfst.nrows," rows\n")
    print("column schema: ")
    Base.show(dfst.schema)
end

function scitype(X::DataFrames.DataFrame)
    scitypesX = scitypes(X)
    return scitype_DataFrame(DataFrames.nrow(X), scitypesX, union(scitypesX))
end
```

**Comment by ablaom** [comment]
After reviewing the Sprint feedback, noting the flaw opening this
post, and following detailed discussions with @fkiraly, I propose we
make some enhancements to the scitype API outlined below.

We have agreed that the scitype of a container object, such as a
table, should be something meaningful. For me, "meaningful" means
comparable with declared scitypes for a model's input, target (or, in
the case of a transformer, output). After thinking this through
carefully, one discovers that there is no obvious way to achieve this
with a julia type heirarchy and the `<:` partial order as the method
of comparison. 

So I propose we extend the atomic scitypes already defined
(Continuous, FiniteOrder, etc) with new scitype objects (not julia
types) for containers, and extend the julia type partial order on the
atomic types, to a new scitype partial order `⊂` that makes sense for
the kind of comparisons we want to make, in matching model
requirements to properties of the data.  Such a scheme is now
implemented in MLJBase on the `tablescitype` branch
[here](https://github.com/alan-turing-institute/MLJBase.jl/blob/tablescitype/src/scitypes.jl)

Here's the kind of behaviour one obtains:

```julia
julia> X = (x1=[1,2,3], x2=rand(3), x3=[4,5,6])
(x1 = [1, 2, 3],
 x2 = [0.829538, 0.398633, 0.324797],
 x3 = [4, 5, 6],)

julia> y = rand(3)
3-element Array{Float64,1}:
 0.3459043064369627 
 0.31518975510134717
 0.5872279454121472 

julia> scitype(X)
TableScitype(Set(DataType[Count, Continuous]))

julia> scitype(y)
ArrayScitype(Continuous, 1)

julia> scitype(X) ⊂ TableScitype(Set([Infinite]))
true

julia> scitype(X) ⊂ TableScitype(Set([Multiclass, Continuous]))
false

julia> scitype(y) ⊂ VectorScitype(Infinite)
true

julia> scitype(y) ⊂ VectorScitype(Finite)
false
```

I propose furthermore, that each supervised `Model` object have two
traits `scitype_X` and `scitype_y` (to replace `input_scitype_union`,
`target_scitype_union` and `input_is_multivariate`) whose values are a
container scitype, and that `scitype(model)` return a named tuple
`(X=..., y=...)` with values the trait values. Then checking
compatibility of model with data is much simpler than before:

```julia
	scitype(X) ⊂ scitype(model).X && 
        scitype(y) ⊂ scitype(model).y
```

*Aside.* In a different proposal, the scitype of a table has the full
scitype "schema" (as currently obtained with `scitypes`). However,
this makes no sense to me, as the `scitype(model).X` would never
encode this kind of information.

**Comment by fkiraly** [comment]
Agreed with most, except the aside where I find the conclusion not necessary:

"However, this [scitype(::table) encoding the full schema] makes no sense to me, as the scitype(model).X would never encode this kind of information."

I doubt that this is a necessary argument. Why should `scitype(model).X` impact the `scitype` of a table in this way?
I agree that if you were to put the full schema in the scitype of a table, you have too much information to conduct the "obvious" comparison with the model scitype.
But the full schema would be useful in other kind of frequent, useful comparisons, e.g.: can I use a model fitted to dataset 1 to predict on dataset 2? You can, iff schema 1 is a sub-dictionary of schema 2 (forgetting about ordering). There's no way to decide this from the set union of column scitpyes alone.

**Comment by ablaom** [comment]
@fkiraly Let me try to understand this. What schema do I assign to object `scitype_X(RidgeRegressor)` ?

**Comment by fkiraly** [comment]
I would make it a struct encoding (in one of the multiple ways discussed) a structured type with the following fields:

X: continuous
y: continuous
task: deterministic_regression

`scitype(RidgeRegressor)` would return the above structured scitype, `scitype(RidgeRegressor).X`, which would be a more interface consistent way of getting the answer, would be the single input scitype it can deal with.

You can check compatibility with `X,y` by checking
`⊆(scitype(X).schema, scitype(RidgeRegressor).X)`
and
`⊆(scitype(y).schema, scitype(RidgeRegressor).y)`
where `⊆`, I believe, is already defined for `⊆( ::Dict, ::Set)` - it checks whether every element of the first argument is contained in the second.

**Comment by fkiraly** [comment]
On a supplementary note: I would recommdn avoiding scitype-related methods with unobvious names, such as `scitype_X`, `scitypes`, `scitypabulous` or `mydogatemyscitype`, because the user can't really guess, or inspect the methods.

If it's always the same thing - that is, `scitype` - users can call it and inspect the returned struct, which can even contain a string explaining the contents, for good measure.

**Comment by fkiraly** [comment]
On a secondary supplementary note: since in Julia it doesn't seem to be user friendlily possible to explicitly construct and manipulate structured types in isolation, i.e., withou handling inhabitants as well, instead of a `DataType` typed struct to encode

X: continuous
y: continuous
task: deterministic_regression

we may be want to use structs where the scitypes are *values* of an inhabitant, rather than declared types, i.e.:

X = continuous : Set{scitype}
y = continuous : Set{scitype}
task = deterministic_regression : set{scitype}

or similar

**Comment by fkiraly** [comment]
Random idea: if we end up adopting a task interface that contains the data, we could define `⊆(::Learner, ::Task)` to do the "obvious" thing.

**Comment by fkiraly** [comment]
Random idea: if we end up adopting a task interface that contains the data, we could define `⊆(::Learner, ::Task)` to do the "obvious" thing.

**Comment by ablaom** [comment]
@fkiraly Allow me to respond to your suggestion above later.

For now I wanted to note  that we can stick to Julia types after all. The basic idea is that we can do "disjoint" unions of types by just wrapping types with `Val`. For example, for the disjoint union of types `Continuous` and `Union{Missing, Finite}` we use `Union{Val{Continuous}, Val{Missing,Finite}}`. 


Here is a vastly simplified implementation of a Table scitype (without schema, which one gets with `scitypes` as in the current implementation):

```julia
struct Table{T} end

# convenience constructor for the *type* (not for instances which we
# never use):
Table(Ts...) = Table{<:Union{[Val{<:T} for T in Ts]...}}

# scitype for a table:
scitype(X) = Table{Union{[Val{S} for S in values(scitypes(X))]...}}
```

That's it.  In action:

```julia
julia> import MLJBase: Continuous, Finite, OrderedFactor, Count,  scitypes

julia> X = MLJBase.load_reduced_ames().X;
julia> scitype(X)
Table{Union{Val{Continuous}, Val{Multiclass{25}}, Val{Multiclass{15}}}}

julia> t1 = Table(Continuous, Union{Missing, Finite})
Table{#s29} where #s29<:Union{Val{#s28} where #s28<:Continuous, Val{#s28} where #s28<:Union{Missing, Finite}}

julia> t2 = Table(Continuous, OrderedFactor)
Table{#s29} where #s29<:Union{Val{#s28} where #s28<:Continuous, Val{#s28} where #s28<:OrderedFactor}

julia> scitype(X) <: t1
true

julia> scitype(X) <: t2
false
```

**Comment by fkiraly** [comment]
How would this work with learners though?

I.e., how would the above look like when we need structured types?

**Comment by fkiraly** [comment]
Also, I still think the size of a table should be part of its `scitype`...
