### ISSUE TITLE
Add sample-weight interface point?

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#177]
Some supervised and unsupervised algorithms allow one to weight instances and currently there is no obvious interface for passing this information to theses algorithms

**Comment by fkiraly** [comment]
Dare I say ... tasks?

Of course one can also just add it to signatures wherever an X appears, and check whether row lengths agree.

**Comment by ablaom** [comment]
I'm thinking:

- add model trait `supports_sample_weights` to MLJBase, with default value `false`
- when true, `MLJBase.fit` has extended signature: `fit(model, verbosity, X, y, w)`
- when constructing a machine for such models the `w` is optional: `machine(model, X, y, w)` or `machine(model, X, y)` as before (for uniform weights).

As far as I can tell this breaks nothing. 

If people want to discuss contriving sample-weight support for non-supporting models (oversampling, and so forth), please open a new thread.

A test case already exists: the SVM models at https://github.com/alan-turing-institute/MLJModels.jl/blob/master/src/LIBSVM.jl supports weights (currently weights passed as a hyperparameter).

**Comment by fkiraly** [comment]
Small comment: I think the default/baseline case for the weighted version should be "ignore the weights". That way, every learner would be able to take weights as additional input, which should make building of learners easier and avoid an interface case distinction.

**Comment by fkiraly** [comment]
If you want oversampling (and so forth), I'd consider these reduction strategies, hence wrappers (or more generally, first-order compositors).

**Comment by ablaom** [comment]
@fkiraly I like your suggestion to make the fit signature the same for alll cases (`w` gets ignored when not used) but this will break some code.

**Comment by ablaom** [comment]
Evaluation (as opposed to training) now supports per-observation weights #206

**Comment by ablaom** [comment]
Resolved a while ago.
