### ISSUE TITLE
Neural Network port via Flux/Knet

### ISSUE THREAD

**Issue by ayush1999** [alan-turing-institute/MLJ.jl#19]
The poster mentions a port to work with neural networks, via Flux and Knet to be working, but I couldn't find any interface for these packages.

**Comment by ablaom** [comment]
By "poster", I think you mean the schematic under link to poster. This summarises a review of the status of ML packages and is not related to MLJ. 

I do not believe there has ever been interfaces to Flux or KNet for MLJ. 

I have moved the schematic back under the section on "History" to avoid the understandable confusion its previous placement caused, thanks!
