### ISSUE TITLE
Control verbosity of @load macro

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#192]
**Is your feature request related to a problem? Please describe.**
Whenever I load a model in a script, I get verbose information about the packages being loaded.

**Describe the solution you'd like**
I would like to control this verbosity, possibly by using an alternative macro. `@load` would be quiet, and then `@loaddbg` would print information about package imports.

**Describe alternatives you've considered**
An alternative would be to make `@load` quiet, and to not introduce a `@loaddbg`.

**Additional context**
The context is normal usage. I would like to try out a couple of models in a problem, and the messages printed can get annoying quickly.

**Comment by ablaom** [comment]
Sounds good idea to me. Suggested  syntax:

@load PCA verbosity=0

We use "verbosity"  levels elsewhere in the interface, rather than "silent".

PR welcome.

**Comment by juliohm** [comment]
I would make this verbosity option 0 by default. Then users interested in the messages can pass verbosity=1 or higher.

Will try submit a PR.
