### ISSUE TITLE
DecisionTreeRegressor fails to predict

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#193]
**Describe the bug**
The `DecisionTreeRegressor` fails to make predictions.

**To Reproduce**
```julia
using MLJ
@load DecisionTreeRegressor

X = rand(100,2)
y = rand(100)

model = DecisionTreeRegressor()

theta = MLJ.fit(model, 0, X, y)
yhat = MLJ.predict(model, theta, X)
```
>ERROR: MethodError: no method matching apply_tree(::Tuple{DecisionTree.Node{Float64,Float64},Nothing,Nothing}, ::Array{Float64,2})
Closest candidates are:
  apply_tree(::Union{Leaf{T}, Node{S,T}}, ::Array{S,2}) where {S, T} at /home/juliohm/.julia/packages/DecisionTree/nfB7O/src/classification/main.jl:149
Stacktrace:
 [1] predict(::DecisionTreeRegressor, ::Tuple{DecisionTree.Node{Float64,Float64},Nothing,Nothing}, ::Array{Float64,2}) at /home/juliohm/.julia/packages/MLJModels/GgPjI/src/DecisionTree.jl:268
 [2] top-level scope at none:0

**Expected behavior**
I would expect it to work.

**Additional context**
No additional context.

**Versions**
>Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 2

>MLJ v0.2.5

**Comment by juliohm** [comment]
@ayush-1506 @ayush1999 helped with the issue over slack. The fit method returns a tuple `(fitresult, report, cache)`. So we need to call `MLJ.predict(model, theta[1], X, y)`.

**Comment by ayush-1506** [comment]
It's actually (fitresult, cache, report). (Though it doesn't matter in this case.)

**Comment by ablaom** [comment]
X cannot be a matrix. it must be a table supporting the Tables.jl interface.
