### ISSUE TITLE
TunedModel objects not displaying correctly

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#197]
If you run `MLJ/tests/tuning.jl` and look at `tuned_model`, it does  not display properly:

```
julia> tuned_model
MLJ.DeterministicTunedModel(model = FooBarRegressor @ 1…31,
                            tuning = Grid
  resolution: Int64 10
  parallel: Bool true
,
                            resampling = Holdout
  fraction_train: Float64 0.7
  shuffle: Bool false
  rng: Random.MersenneTwister
,
                            measure = MLJ.rms,
                            operation = StatsBase.predict,
                            ranges = NumericRange @ 3…94,
                            minimize = true,
                            full_report = true,
                            train_best = true,) @ 6…41
```

This appears due to the use of `@with_kw`macro in defining `Grid` and `Holdout` struct (also `CV` struct has this). I suggest we dump the use of the macro and just define keyword constructors by hand as before.

**Comment by tlienart** [comment]
Yes that's because `@with_kw` comes with a `show` method baked in which clashes with the one you had written, sorry I should have thought of this. There's a `@with_kw_nowshow` which doesn't do that and "just" does the named constructor. 

Using this it gives:

```julia
julia> tuned_model
MLJ.DeterministicTunedModel(model = SimpleDeterministicCompositeModel @ 1…11,
                            tuning = Grid @ 1…92,
                            resampling = Holdout @ 1…22,
                            measure = MLJ.rms,
                            operation = StatsBase.predict,
                            ranges = MLJ.ParamRange[NominalRange{Array} @ 1…23, NumericRange @ 1…83],
                            minimize = true,
                            full_report = false,
                            train_best = true,) @ 1…47
```

What do you think?

**Comment by ablaom** [comment]
It's great to know about the no-show option. It may make sense elsewhere. 

In this case, let's revert. Less macros and one less dependency can't be a bad thing. 

Thanks.
