### ISSUE TITLE
Loss functions in MLJ

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#205]
Is the notion of loss function implemented in MLJ? I am tempted to use LossFunctions.jl in my packages because it seems very comprehensive

That also brings a few questions to mind: To what extent MLJ.jl is connected with the JuliaML organization? Does it make sense to migrate this repo to that organization? It feels sometimes that very few people have push access in the MLJ.jl repo, and that it could be growing much faster with other collaborators. What are your thoughts on this?

**Comment by ablaom** [comment]
You will be able to use LossFunctions very soon. Working on this right now. 

MLJ does not have any formal association with JuliaML. We are aware of the resources there and hope to make better use of those resources there that are mature or being actively maintained. Do you have some specific suggestion, apart form LossFunctions?

Collaboration is very welcome in the form of PR's.  

 @juliohm It sounds like you are keen to help out. Is there a specific area you would like to work on? It would be great if you can implement an MLJ interface for (parts of) GeoStats. You can find a recent roadmap under CONTRIBUTE.md for other possibilities.

There is an existing loss functions discussion here #91 . So closing this issue.
