### ISSUE TITLE
Migrate @load macro to MLJBase.jl?

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#208]
**Is your feature request related to a problem? Please describe.**
It is not really a problem, but it would be handy to be able to reexport `@load` from MLJBase.jl from projects that extend the functionality therein.

**Describe the solution you'd like**
If it makes sense, we could move the code for `@load` in loading.jl to MLJBase.jl, and reexport it in MLJ.jl. This way other packages that also depend on MLJBase.jl, and are not MLJ.jl could reexport the macro to load models as well without the need for an extra `using MLJ`.

**Describe alternatives you've considered**
Leave the `@load` macro where it is currently. I think loading mechanisms could make sense at a MLJBase.jl level, but it wouldn't be so problematic to have it under MLJ.jl

**Additional context**
No additional context.

**Comment by ablaom** [comment]
Thanks for that. Suggestion appreciated. 

The idea is that MLJBase contains just enough for you to implement the `Model` interface. The entry point for most  users is MLJ.   See also this discussion: https://github.com/alan-turing-institute/MLJBase.jl/issues/19

Since you can import MLJ  and use the @loads macro, this design choice makes no restriction on the functionality you require, although it may add dependencies to what you want to do. 
But as I am confident your use-case is not going to be the common one, I don't see a reason to abandon the current design choice at this point-of-time.

**Comment by juliohm** [comment]
I keep my opinion that MLJ.jl should be a wrapper package (i.e. a project) instead of containing actual code. Over the years developing GeoStats.jl I ended up realising this recurring issue where I needed access to a particular construct and needed to migrate code from GeoStats.jl to GeoStatsBase.jl.

The load macro is not a big deal, but it would be very handy to be able to re-export it from MLJBase.jl instead of forcing users to load the entire MLJ.jl in their scripts. Loading time is an issue at the present moment with Julia, and having MLJ.jl as a dependency just because of a macro seems inefficient.

**Comment by ablaom** [comment]
MLJ is already is already a "project". ML algorithms are not implemented in MLJ but external packages. I agree some MLJ functionality might gradually move out as it becomes more elaborate (eg, tuning) but it would move to new repo, not to MLJBase. MLJBase is just the model API.

**Comment by juliohm** [comment]
Can you please reconsider this issue? I am constantly having to load the full MLJ.jl stack just to get access to the `@load` macro.

**Comment by ablaom** [comment]
The macro stub is there. See https://github.com/alan-turing-institute/MLJBase.jl/blob/master/src/MLJBase.jl. It was added in August when I closed the issue.

**Comment by juliohm** [comment]
Just installed MLJBase.jl locally, this is what it produces:

```julia
julia> using MLJBase
[ Info: Precompiling MLJBase [a7f614a8-145f-11e9-1d2a-a57a1082229d]

julia> @load DecisionTreeClassifier
ERROR: LoadError: MethodError: no method matching @load(::LineNumberNode, ::Module, ::Symbol)
in expression starting at REPL[4]:1
```

**Comment by ablaom** [comment]
As explained earlier, there is no way to load models whose implementations of the API live MLJModels without loading MLJModels. 

```julia
julia> using MLJModels
julia> @load DecisionTreeRegressor
DecisionTreeRegressor(pruning_purity_threshold = 0.0,
                      max_depth = -1,
                      min_samples_leaf = 5,
                      min_samples_split = 2,
                      min_purity_increase = 0.0,
                      n_subfeatures = 0,
                      post_prune = false,) @ 6…16
```
MLJModels is not a dependency of MLJBase because MLJModels depends on MLJBase (because this is where the API that models implement live).

**Comment by juliohm** [comment]
I thought the `@load` macro was just looking up names, but I realize now that it actually instantiates a model.
