### ISSUE TITLE
Boosting Packages

### ISSUE THREAD

**Issue by ysimillides** [alan-turing-institute/MLJ.jl#21]
During the last call, various libraries where mentioned for boosting algorithms.

The three options we discussed (and from a brief search most commonly used) are :

- CatBoost, which currently has no Julia interface, although someone mentioned an interest on his (developers?) side to port it.

- XGBoost, which currently has a Julia interface, with a version working for v0.7 and v1.0, alongside tests and a build.jl file to automatically build it if needed when using it. Although this version is not yet "tagged", with the new package manager this is less of an issue (and I can always get in touch with them to speed this process up if necessary).

-  LightGBM, which has an unmaintained Julia interface, not currently working on v0.7, with no tests present. It also requires the separate building of the dependency, although with Requires / writing our own build file this can be somewhat managed.

From an ease of use perspective it seems to be wisest to integrate/copy over XGBoost, although from a performance/feature point of view a different package might be more optimal if you have some suggestions.

Also some issues are open regarding packaging/upgrading such as #4, #7 and from what I can gather, these have now been fixed? (module registering the package itself?)

**Comment by darenasc** [comment]
I mentioned CatBoost, I had a chat in July with one of the authors of the [paper](http://learningsys.org/nips17/assets/papers/paper_11.pdf) and we could communicate and get advice from people at Yandex if we want to implement it. 

I'd be keen to work on an implementation of CatBoost but no time at the moment.

**Comment by ysimillides** [comment]
XGBoost has been implemented, but will be moved to a new package (MLJXGBoost). This will also allow us to implement LightGBM

**Comment by swenkel** [comment]
one remark on XGBoost: It might be worth to look into a pure implementation of XGBoost. [There is one that seems to be twice as fast as the reference implementation](https://discourse.julialang.org/t/new-machine-learning-package-julia-implementation-of-xgboost/8912/20). However it is not compatible with Julia 0.7+ but there is one person [who implements/wants to implement a new one](https://discourse.julialang.org/t/new-machine-learning-package-julia-implementation-of-xgboost/8912/21).

**Comment by ysimillides** [comment]
@swenkel that's definitely something work looking into, and plans for the package in the future, i.e. replacing external languages and libraries with pure julia implementations. I'll keep an eye out for it, and also try contacting the author to see what progress they've made.

**Comment by ablaom** [comment]
Closing, as XGBoost.jl wrap is written and other implementations have or can be given new issues.
