### ISSUE TITLE
Dataset generation for model inspection

### ISSUE THREAD

**Issue by davidbp** [alan-turing-institute/MLJ.jl#214]
#### Is your feature request related to a problem? Please describe

Many classifiers have convergence theorems that tell us that they can classify correctly any linearly separable problem.  It would be nice to have code that generates  [bloobs](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_blobs.html). We could use this generated datasets to test, document and visually assess the classification boundaries of our learning algorithms.

Other functions could be also added to visually inspect the behaviour of clustering algorithms. Something like this
![image](https://user-images.githubusercontent.com/4223580/63505361-b1b3b980-c4d3-11e9-95cc-afd1f609fbb1.png)

**Describe the solution you'd like**
A simple julia version of [a bloob generator](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.make_blobs.html)   would be enough to start.

**Comment by ablaom** [comment]
Sounds good to me. 

@davidbp Probably isn't going to happen soon unless you are volunteering :-)

**Comment by davidbp** [comment]
Done! 

I have translated the functions to generate the same data as sklearn. You can take a look  [here](https://github.com/davidbp/MulticlassPerceptron.jl/blob/master/notebooks/learning_tests.ipynb
)

**Comment by ablaom** [comment]
Looks great, thanks!

The PR should be made to MLJBase, so anyone implementing the MLJ interface for their model has a  ccess. There is already src/datasets.jl, which you could add to, but a new file is probably better. How about `datasets_synthetic.jl` ? 

Related: https://github.com/alan-turing-institute/MLJBase.jl/issues/118
