### ISSUE TITLE
Update examples to MLJ 0.4.0

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#216]
Here's a great opportunity for new contributors.

The main breaking changes effecting the examples would  concern:

- tuning

- learning networks

These are now both covered in the updated [manual](https://alan-turing-institute.github.io/MLJ.jl/v0.3/), so that should be easy to sort. Note there are now *two* ways to export a learning network. The examples should use the new easy @from_network macro, which should work everywhere, except possibly for the ames example. 

It would also be good to add multiple measures to the performance estimates, where there is more than one choice available. The built-in measures are listed in the manual and we can now use losses from LossFunctions.jl (need `using LossFunctions`, which will be needed to be added to the example environments).

Important notes:

- The environments (Project.toml and Manifest.toml) files also need to be updated. These make the examples completely reproducible after updates to MLJ.

- At present examples are notebooks. That's fine, but better, in my opinion, would be [Literate.jl](https://github.com/fredrikekre/Literate.jl) compliant .jl scripts from which we can automatically generate the notebooks (and testing). The Literate.jl format is very quick  to learn if one is not already familiar. Both .ipynb and .jl could be there, but the .jl scripts would be the master versions. 

Here's a breakdown:

- [x] tour
- [x] random forest
- [x] ames
- [x] tiny demo
- [x] XGBoost.jl (needs its own folder and environment files)

New examples also welcome.

For newcomers interested in tackling the updates, this is great opportunity for us to get useful feedback on the pkg, so don't be shy about asking questions - here or on the  #mlj slack channel. 

If interested, claim one or more items from above in a comment below.

**Comment by ablaom** [comment]
@tlienart Can you please tick off the items you already migrated to the JuDoc site?

**Comment by tlienart** [comment]
All these examples have now been ported either in whole or sliced in parts: https://alan-turing-institute.github.io/MLJTutorials/ I think this issue can be closed.
