### ISSUE TITLE
Add docs for 'pipe' syntax

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#231]
Add entry in `/docs/src/composing_models.md` for the `|>` syntax with an example.

**Comment by ablaom** [comment]
@tlienart This can just be copied from MLJTutorials, yes?

**Comment by tlienart** [comment]
Yes, the one thing that prevents me from doing that is a good name. "Pipe" syntax may be confusing with pipeline? I said "arrow" syntax during the talk, and someone half jokedly said we should call the operator something like the walrus operator in python; what's your take?

**Comment by ablaom** [comment]
Just Pipe is confusion. Arrow sound good to me.
