### ISSUE TITLE
Document out-dated

### ISSUE THREAD

**Issue by stevewangldcap** [alan-turing-institute/MLJ.jl#235]
**Document in Performance Measure section is outdated**

https://alan-turing-institute.github.io/MLJ.jl/stable/performance_measures/

**To Reproduce**

```julia
julia> using MLJ
​
julia> y = [1, 2, 3, 4];
​
julia> ŷ = [2, 3, 3, 3];
​
julia> w = [1, 2, 2, 1];
​
julia> rms(ŷ, y) # reports an aggregrate loss
0.8660254037844386
​
julia> l1(ŷ, y, w) # reports per observation losses
ERROR: UndefVarError: l1 not defined
Stacktrace:
 [1] top-level scope at none:0

```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by ablaom** [comment]
Thanks for that!

Can I please have `versioninfo()` and `using Pkg; Pkg.status()`?

**Comment by stevewangldcap** [comment]
started new julia session, it all worked.
