### ISSUE TITLE
[docs] Document metadata_pkg, metadata_model and @mlj_model

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#241]
Following

- merge in MLJBase of https://github.com/alan-turing-institute/MLJBase.jl/pull/47 and
- merge in MLJModels of https://github.com/alan-turing-institute/MLJModels.jl/pull/66

document `metadata_pkg`, `metadata_model` and `@mlj_model` (exported from `MLJBase`) in `docs/src/adding_new_models_for_general_use.md`

**Comment by ablaom** [comment]
Documentation for:
- [ ]  metadata_pkg
- [ ] metadata_model
- [ ] @mlj_model
