### ISSUE TITLE
Create/utilize a style guide

### ISSUE THREAD

**Issue by jpsamaroo** [alan-turing-institute/MLJ.jl#243]
It would be beneficial for the sake of minimizing the size of diffs if we enforce a consistent style guide for MLJ and its dependencies/sister packages. For me specifically, it bugs me that there is a lot of non-functional whitespace scattered around the codebase, and I clean it up whenever I make a PR to nearby code. Additionally, it makes it hard to feel confident when I modify code, someone won't ask me to change it again to fix the styling. Having something explicitly documented would be helpful in this regard.

**Comment by ablaom** [comment]
Thanks for that. I agree that it is annoying when whitespace is altered. 

Rather than enforcing any traditional style (and debating what that should look like) I would prefer the protocol that one restrains from altering existing whitespace. I apologise in advance for instances in which I will probably violate this (but any) "style guide". 

I would never ask another contributor to alter the style of their PR. I value the content of their contribution far in excess of the value of a consistent code style.

**Comment by jpsamaroo** [comment]
I suppose that works fine as a rule, although once more contributors come onbpard it might become an issue (but we could address that later down the line).

The one thing I want to be able to change is to remove whitespace at the end of a line (or in an otherwise empty line), where it serves no purpose. Most projects I know of ask contributors to remove such whitespace since it serves no purpose and can cause code to look "ugly" in an editor that shows this whitespace explicitly.

**Comment by tlienart** [comment]
By the way the removal of whitespace is done automatically by the likes of Atom

Also: 

http://blog.ranjansakalley.com/2015/09/cleaning-up-whitespace-changes-in-a-pull-request.html

**Comment by tlienart** [comment]
Manipulation error,

Ref for whitespace removal: http://blog.ranjansakalley.com/2015/09/cleaning-up-whitespace-changes-in-a-pull-request.html

Btw, modern editors like Atom remove whitespaces automatically which I think is good... People who use VIM or similar can use plugin to the same effect (e.g. https://howchoo.com/g/odg0mdyzmwr/vim-how-to-remove-trailing-whitespace-on-save)

**Comment by ablaom** [comment]
All and sundry will be happy to learn that I have added whitespace display and clean-up to my editor, so I can now obsess over red bits of code that never before concerned me (because they were invisible and had no effect on the code meaning) 👅 😄
