### ISSUE TITLE
Wrap TSne.jl and UMAP.jl into MLJ.jl

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#250]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to have embeddings like TSne.jl, UMAP.jl and MultivariateStats.jl as unsupervised models. I personally find that TSne.jl and UMAP.jl should be part of MultivariateStats.jl and then MLJ.jl could wrap MultivariateStats.jl.

**Describe alternatives you've considered**
Didn't consider alternatives.

**Additional context**
No context

**Comment by tlienart** [comment]
cross ref https://github.com/alan-turing-institute/MLJModels.jl/issues/42
