### ISSUE TITLE
Use alphabetical ordering for ambiguous provider package

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#257]
I don't think it's a good thing that

```
@load LinearRegressor
```

throws an error. Rather, I think we should just apply a heuristic:

* which provider packages are available? if only one, use that one
* if more than one, use the first one in alphabetical order

**Comment by ablaom** [comment]
That sounds reasonable to me. I suggest a warning that multiple packages provide the model be issued, and that the non-macro version `load("LinearRegressor")` still throw an error.
