### ISSUE TITLE
Get predictions

### ISSUE THREAD

**Issue by petrostat13** [alan-turing-institute/MLJ.jl#259]
How can I get the prediction vector of a wrapped learning network, if I export it as a standalone model? 

When I use the @from_network method it works fine, but if I do it as a 'mutable struct' I can't get the predictions, since there is no 'predict' method. 

For example, how would it work on this wrapped model? (taken directly from the documentation page)

```
mutable struct WrappedRidgeII <: DeterministicNetwork
    ridge_model
end

# keyword constructor
WrappedRidgeII(; ridge=RidgeRegressor) = WrappedRidgeII(ridge); 

function MLJ.fit(model::WrappedRidgeII, verbosity::Integer, X, y)
    Xs = source(X)
    ys = source(y, kind=:target)

    stand_model = Standardizer()
    stand = machine(stand_model, Xs)
    W = transform(stand, Xs)

    box_model = UnivariateBoxCoxTransformer()  # for making data look normally-distributed
    box = machine(box_model, ys)
    z = transform(box, ys)

    ridge_model = model.ridge_model ###
    ridge =machine(ridge_model, W, z)
    zhat = predict(ridge, W)

    yhat = inverse_transform(box, zhat)
    fit!(yhat, verbosity=0)
    
    return fitresults(yhat)
end
```

**Comment by ablaom** [comment]
Thanks for posting. This led me to a documentation typo.

Re your post: There is a fallback `predict` method for such cases. The following works for me after fixing the documentation bug (#261):

```julia
X, y = @load_boston
mach = fit!(machine(WrappedRidgeII(), X, y))
predict(mach, rows=1:10)
```
