### ISSUE TITLE
[docs] Composing models is missing height variable

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#267]
https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/

`height` is not specified.

**Comment by ablaom** [comment]
`height` is just the name of the target in that example (instead of the more usual `y`). 

@tlienart Feel free to change this to `y` as others are likely to have the same confusion.

**Comment by tlienart** [comment]
uh yeah but unless I was being stupid, if you try to run the example on that page you'll get an error that height is not defined.

If you specify

```julia
height = [178, 194, 165, 173, 168];
```

then it works. 

Yes I can provide a PR for this

**Comment by tlienart** [comment]
Ok well that's the issue:

```
height = [67.0, 81.5, 55.6, 90.0, 61.1]; nothing # hide
```

**Comment by ablaom** [comment]
Ok. My bad, I'm not understanding use of #hide in documenter:

```@example 7
using MLJ
X = (age    = [23, 45, 34, 25, 67],
     gender = categorical(['m', 'm', 'f', 'm', 'f']));
height = [67.0, 81.5, 55.6, 90.0, 61.1]; nothing # hide
```

**Comment by tlienart** [comment]
I think it just hides the line 😄 

It's useful if you want to have code blocks that have steps you don't want to show because they're obvious or distracting but are needed to get the code to run on Documenter.

I'll close this I think the problem is solved 🙂
