### ISSUE TITLE
Allow specification of number of values for given parameters in Grid

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#269]
At the moment, `Grid(resolution=5)` will lead to `5^d` points if you have `d` hyperparameters. 

It would be nice to offer the possibility to specify resolution per hyperparam:

```julia
Grid(resolution=(:(ridge_model.lambda)=>5, :(knn_model.K)=>5, :knn_weight=>3))
```

(By the way, more generally, we'd want to support something like that for a probabilistic grid where you'd allow sampling in the different dimensions according to different distributions and a different number of samples)

**Comment by ablaom** [comment]
Agreed!

**Comment by tlienart** [comment]
I'm happy to attempt a PR for this but I'm not very familiar yet with the internals of `tuning.jl` :)

**Comment by ablaom** [comment]
Implemented as stated except resolution is vector instead of tuple for consistency with ranges and elsewhere.

**Comment by tlienart** [comment]
awesome
