### ISSUE TITLE
[proposal] set explicit compat versions for the model registry

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#276]
As discussed on the MLJ call and see also https://github.com/alan-turing-institute/MLJModels.jl/issues/86 it would be desirable to have a way to check that at any one time all models available via MLJ "work" which may require some form of compat bounds.

When package devs update their models, they would submit a PR for a version bump, where we would require explicit tests to pass before doing so?

**Comment by ablaom** [comment]
#279 Adds bounds but does not address other points made here.

**Comment by ablaom** [comment]
Closing in favour of https://github.com/alan-turing-institute/MLJModels.jl/issues/244
