### ISSUE TITLE
Implement more classifier metrics such AUC, PPV

### ISSUE THREAD

**Issue by vollmersj** [alan-turing-institute/MLJ.jl#277]
**Is your feature request related to a problem? Please describe.**
We would like to provide more metrics 
**Describe the solution you'd like**
Wrap around MLBase
**Describe alternatives you've considered**
reimplement from scratch
**Additional context**

**Comment by ablaom** [comment]
Some notes and resources:

- The measure interface actually lives in MLJBase.jl

- Manual describes the measure API: https://alan-turing-institute.github.io/MLJ.jl/dev/performance_measures/

- if considering interfacing metrics defined in other packages, look at MLJBase/src/loss_functions_interface.jl where this done already for metrics in LossFunctions.jl

- If considering a binary classification metric that is not symmetric in the choice of "true", then the true value will need to be a parameter. In MLJ a binary target (scitype <:Finite{2}) is just an abstract vector whose elements are `CategoricalValue` (or `CategoricalString`) and the pool size is two. So there is no distinguished "true" class.
