### ISSUE TITLE
Add default_measure to learning_curve!

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#283]
In `learning_curve!` (but not only there) you can specify a measure which, by default, is set to `rms`; however if you leave it to default and try to do this on a classifier you'll get an error. 

It would be easy  to change so that it takes a reasonable default measure for the type of model something like

```julia
function learning_curve!(mach::Machine{<:Supervised};
                         resolution=30, resampling=Holdout(),
                         measure=default_measure(mach), operation=predict,
                         range=nothing, verbosity=1, n=1)
```

where `default_measure` returns for instance either `rms` or `cross_entropy` or some such based on what type of input it gets

**Comment by ablaom** [comment]
Actually, there is already a `default_measure(model)` function, defined in MLJBase/src/measures.jl, which uses the scientific type of the target to determine a sensible default. So, 

```julia
function learning_curve!(mach::Machine{<:Supervised};
                         resolution=30, resampling=Holdout(),
                         measure=default_measure(mach.model), operation=predict,
                         range=nothing, verbosity=1, n=1)
```

ought to do it.

**Comment by Sinansi** [comment]
Hello,

Can someone confirm whether the MLJ.learning_curve! function has been deprecated?
I cannot find this function from MLJ documentation 0.3.0 onward.
So I checked 0.3.0 release notes, but couldn't find a deprecation announcement. 

Thank you!

**Comment by ablaom** [comment]
Yes, good catch, thanks.  It is not in the manual, will address this. 

https://github.com/alan-turing-institute/MLJ.jl/issues/362

There is a docstring, so you can do `?learning_curve!` at the REPL. And there is a demo at https://alan-turing-institute.github.io/MLJTutorials/pub/getting-started/ensembles-2.html

**Comment by Sinansi** [comment]
Thank you so much Dr. Anthony!
Yes, I have been working on the Tutorials since you provide me with the link.
Your tutorials are so informative and helpful, and I am glad they are available in various formats.
Great work!

**Comment by ablaom** [comment]
Your welcome. Kudos for the tutorials goes in large part to @tlienart.

**Comment by ablaom** [comment]
Resolved by https://github.com/alan-turing-institute/MLJ.jl/issues/358
