### ISSUE TITLE
Flush out unsupervised models in "Adding models for general use" section of manual

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#285]

**Comment by caseykneale** [comment]
I have a bunch of those here:
https://github.com/caseykneale/ChemometricsTools.jl/blob/master/src/Analysis.jl
https://github.com/caseykneale/ChemometricsTools.jl/blob/master/src/Clustering.jl
https://github.com/caseykneale/ChemometricsTools.jl/blob/master/src/AnomalyDetection.jl
https://github.com/caseykneale/ChemometricsTools.jl/blob/master/src/MultiWay.jl
https://github.com/caseykneale/ChemometricsTools.jl/blob/master/src/TimeSeries.jl
https://github.com/caseykneale/ChemometricsTools.jl/blob/master/src/CurveResolution.jl
probably others too

**Comment by ablaom** [comment]
Point out that unsupervised models can implement a predict as well as transform, eg, clustering.
