### ISSUE TITLE
CV(shuffle=true) does not seem to properly shuffle the data

### ISSUE THREAD

**Issue by baggepinnen** [alan-turing-institute/MLJ.jl#289]
**Describe the bug**
`CV(shuffle=true)` does not seem to properly shuffle the data. If I manually perform the shuffle, no `Inf`s are produced below

**To Reproduce**
```julia
tree_model = MLJ.@load DecisionTreeClassifier
forest_model = EnsembleModel(atom=tree_model, n=10)
y = CategoricalArray((ones(Int,100,10) .* (1:10)')[:])
input =  table(randn(1000,2))
e = MLJ.evaluate(forest_model, input, y, resampling=CV(nfolds=2, shuffle=true), measure=cross_entropy, verbosity=1)

julia> e
(measure = MLJBase.CrossEntropy[cross_entropy],
 measurement = [Inf],
 per_fold = Array{Float64,1}[[Inf, Inf]],
 per_observation = Array{Array{Float64,1},1}[[[Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf  …  Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf], [Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf  …  Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf, Inf]]],)

```

**Expected behavior**
No `Inf` in result

**Comment by ablaom** [comment]
Thanks for that! Good catch! You have actually uncovered two bugs in one:

- CV shuffle is not working (simple bug i will fix)
- pdf smoothing in `DecisionTree` not working (https://github.com/alan-turing-institute/MLJModels.jl/issues/93)

**Comment by baggepinnen** [comment]
Awesome, thanks for your work on this package, I think it has great potential!
