### ISSUE TITLE
Break MLJ into MLJ and MLJBase

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#29]
@MikeInnes has suggested that we extract from MLJ.jl the methods to be extended by external packages and put them into a new package MLJBase.jl. So, if I want to my package CoolRandomForests.jl to implement the MLJ.jl interface, I just need to import MLJBase.jl. The higher level abstractions (tasks, trainable models, learning networks, tuning and so forth) stays in MLJ.jl, which imports MLJBase.jl.

This is a fairly ubiquitous design pattern in Julia and I can think of no reason not to do this. Unless I objections are raised by the end of this Friday 7th, I will go ahead and implement.

**Comment by fkiraly** [comment]
Yes, agreed – I wanted to raise an issue on framework functionality vs extensibility myself.
It makes sense to carefully think about module design.

A related issue which Mike’s may or may not cover is how much of the metadata a user has to provide for it to work with mlj.

There is a natural trade-off in user experience depending on whether one is the creator of an algorithm or not.

Hence I’d suggest a two-tiered system:

Low-tech -> user specifies only methods necessary for running the strategy, e.g., fit/predict, say, but not metadata and perhaps not even a full meta-parameter specification. Can be used with mlj with the user’s implicit knowledge of what the method does, and is very quick to implement and not difficult, a few lines to interface perhaps. Perhaps mlj “infers” meta-data on the fly. However, this is ineligible for addition to mlj as it requires “secret creator knowledge” to be bug-free, hence is only for own use.

High-tech -> full specification of a method conforming with an “extension” document. Contains metadata and all the sugar and would make the method eligible for the mlj registry or similar. More complicated to do but needed if the method is to be easily used by users other than the creator.

**Comment by ysimillides** [comment]
Sebastian has created https://github.com/alan-turing-institute/MLJInterface.jl , we shall split the package there.

**Comment by ablaom** [comment]
Model interface moved to [MLJBase](https://github.com/alan-turing-institute/MLJBase.jl)
