### ISSUE TITLE
Static transformers depending on parameters

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#291]
**Static transformations**

In learning networks (and elsewhere) one can include ordinary
data-manipulating functions such as `vcat`, `exp`, `selectcols` (to
select features), etc. These are called *static transformations* in
the manual to distinguish them from transformations with *learned
parameters* that must be trained. More generally, however, one would
like to include static transformations that depend on parameters. A
simple example is a transformation that returns a weighted combination
of two inputs, the two weights constituting the parameters on which
the transformation depends.

In Julia, the most natural way for the user to define such
transformations themselves, is to put the parameters - let's call them
*hyperparameters*, to distinguish them from learned parameters - in a
struct and make the instances *callable*:

```julia
mutable struct Blend
    weights::Tuple{Float64,Float64}
end
(blend::Blend)(y1, y2) =  blend.weights[1]*y1 + blend.weights[2]*y2
```

**The problem**

One would like to include static transformations depending on
parameters in learning networks. However, if one wants to export the
learning network as a stand-alone model using the `@from_network`
macro, then *only parameters that appear as fields of a `Model` in the
network* can be exposed as parameters in the exported model. This is
why the learning network used to define KKNRidgeBlend in [this
chapter](https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/)
(which involves blending two variables predictions together, as
  above) must be exported in the more general (but less convenient way).

**The solution**

I propose we address the above problem on the following way:

- Any static transformation, such as blend above, is declared as a
  subtype of a new type `Static <: Unsupervised <: Model` So, above, write
  `mutatable struct Blend <: Static`. 

- `fit` for such models is "do nothing", return `nothing` objects.

- `transform` for such models just *calls* the object

**Example workflow**

Here's the definition of composite model type `Comp` that returns a
weighted average of the predictions of two determinisic regressors,
called `regressor1` and `regressor2`. As default values for the models, we use
`KNNRegressor` and `RidgeRegressor`:

```julia

## STATIC TRANSFORMATION FOR BLENDING

mutable struct Blend <: Static
    weights::Tuple{Float64,Float64}
end
(blend::Blend)(y1, y2) =  blend.weights[1]*y1 + blend.weights[2]*y2


## LEARNING NETWORK

X = source()
y = source(kind=:target)

rgs1 = KNNRegressor()
rgs1_ = machine(rgs1, X, y)
y1 = predict(rgs1_, X)

rgs2 = RidgeRegressor()
rgs2_ = machine(rgs2, X, y)
y2 = predict(rgs2_, X)

blend  = Blend(0.5, 0.5) # default blend
blend_ = machine(blend, y1, y2)
yhat = transform(blend_, y1, y2)


## EXPORT THE MODEL

comp = @from_network Comp(regressor1=rgs1, regressor2=rgs2, blend=blend) <= yhat

```

**Issues **

I believe (@tlienart to confirm) that the arrow syntax for defining learning networks implements some calling behaviour on models that might interfere here.

Otherwise this is pretty straightforward and would not break anything. 

Thoughts anyone?

**Comment by tlienart** [comment]
This seems perfectly reasonable. One side note is that Blend should be a one parameter thing with (a, (1-a)); 

With respect to the arrow syntax, given that Blend is a subtype of supervised, it should be fine, maybe just implement without looking at the arrow syntax and ping me and I'll test and possibly extend the arrow syntax to make sure it still works fine?

**Comment by ablaom** [comment]
Okay. Please see MLJBase#static (which implements the `Static` type and associated methods) and MLJ#static which fails because of an ambiguity in calling an instance of `Static`.

**Comment by tlienart** [comment]
Ok so after having a look at the code, I think we need to fix the  approach a bit, let's just not make static callable individually and just use the usual `transform` so for instance

```julia
mutable struct Scale <: MLJBase.Static
    scaling::Float64
end
transform(s::Scale, _, X) = s*X
```

that's  not really more complicated.

Then the arrow is unchanged, you would do

```julia
X |> Scale(0.5)
```

I'm happy to add these changes  but the file `test/static.jl` is missing from `MLJBase#static`  I believe.

@ablaom

**Comment by ablaom** [comment]
I'm not overly enthusiastic about this. Defining a static transformation is more fundamental than arrow syntax and should be as natural as possible, in my opinion. It's clunk for the general user to have that mysterious "_".

**Comment by tlienart** [comment]
well  then let's just introduce an `apply` method which does this `transform` without fitresult?

This is not just  about being compatible with the arrow syntax, it's just weird to make that model callable where all other  models aren't (and the reason they aren't is because we can't generically make models callable before 1.3).

Anyway, I'd suggest:

```julia
transform(s::Static, args...) = apply(s, args...) # fallback
inverse_transform(s::Static, args...) = reverse(s, args...) #  fallback

apply(s::Static, args...) = # user defined
reverse(s::Static, args..) = # user defined
```

can use another name than `reverse` of course like `unapply` or `inverse_apply` to keep with `inverse_transform` idea.

**Comment by ablaom** [comment]
Some good ideas, and thanks for exploring this option in code. 

I don't, however, like this solution much better because we introduce a new method name, and the reasons for doing so will appear totally mysterious to the user. If we could use "transform" here instead of "apply" that would be better, but I couldn't see how to make that work. 

I think we *can* implement the original static transformer design if we make some compromises with the arrow syntax (which, personally, I see as improvements). After reviewing the latest syntax, I believe it takes convenience to an extreme, compounding several orthogonal syntactic simplifications, which could be confusing and are arguably unnecessary. There is also quite a bit of "hidden knowledge" here. 

If we dump dump lines marked with "A" then there are no conflicts, because then arrow syntax only overloads calling for models when the argument is an AbstractNode, no? When the model instance is called with anything that is not an abstract node, the user-defined calling behaviour will be used (applying only for static transformers, for the moment).

For consistency, I would eliminate lines marked `B` as well. I think it's better to be explicit about when you are changing a data format from matrix to table, and when you are wrapping data in source node, and the cost in extra code is a small price to pay for this explicitness, IMO. 

@tlienart Your reaction? 

```julia
# Syntactic sugar for arrow syntax
# we need version ≥ 1.3 in order to make use of multiple dispatch
# over abstract types

# This allows implicit: data |> machine
(mach::AbstractMachine{<:Unsupervised})(data) = transform(mach, data)
(mach::AbstractMachine{<:Supervised})(data)   = predict(mach, data)
(mach::AbstractMachine)(data::AbstractMatrix) = data |> table |> mach    <-----B

# This allows implicit: data |> Unsupervised
(m::Unsupervised)(data::AbstractNode) = data |> machine(m, data)
(m::Unsupervised)(data) = source(data) |> m                 <------------ A
(m::Unsupervised)(data::AbstractMatrix) = data |> table |> m       <------------ A

# This allows implicit: data |> Supervised
(m::Supervised)(data::NTuple{2,AbstractNode}) = data[1] |> machine(m, data...)          
(m::Supervised)(data::Tuple{AbstractNode,Any}) = (data[1], source(data[2], kind=:target)) |> m   <--B
(m::Supervised)(data::Tuple) = (source(data[1]), data[2]) |> m    <-- B
(m::Supervised)(data::Tuple{AbstractMatrix,Any}) = (data[1] |> table, data[2]) |> m   <-- B

# This allows implicit: data |> inverse_transform(node)
inverse_transform(node::Node{<:NodalMachine{<:Unsupervised}}) =
    data -> inverse_transform(node.machine, data)
```

**Comment by tlienart** [comment]
Ok so after thinking a bit about this, here's a suggestion  which may be acceptable, it would look like this:

```julia
using MLJBase:table, matrix
mutable struct Scaling <: Static
  scaling::Float64
end
@static transform(s::Scaling, X) = table(s.scaling * matrix(X), prototype=X)
@static inverse_transform(s::Scaling, X) = table(matrix(X) / s.scaling, prototype=X)

mutable struct Blend <: Static
    weights::Tuple{Float64,Float64}
end
@static transform(b::Blend, y1, y2) =  b.weights[1]*y1 + b.weights[2]*y2
```

The `@static` would serve as a way to declare a model that is not learned and  would discard  the (nothing) results that are passed from the machine so that the above amounts to writing the syntax with the `_` that I had suggested earlier. It could also take care of declaring a default `fit` that does nothing but I believe there's already  a fallback for this.

The advantage here is that there's no new syntax, it's effectively  just the  same but the user would understand  that there's a difference between a learned transform and a static one. Also it's compatible with the arrow syntax.

**Comment by tlienart** [comment]
on  second thoughts, I'm wondering why we need all this, couldn't we just have

```julia
transform(s::Scaling, X) = table(s.scaling * matrix(X), prototype=X)
inverse_transform(s::Scaling, X) = table(matrix(X) / s.scaling, prototype=X)
```

are there cases where that wouldn't work?

**Comment by tlienart** [comment]
This is a working implementation:

```julia
using MLJBase

import Base.@static
import MLJBase: transform, inverse_transform

mutable struct Scaling <: MLJBase.Static
    scaling::Float64
end

macro static(ex)
    if ex.args[1] isa Expr
        part = ex.args[1]
        fn   = part.args[1]
        if fn ∈ (:transform, :inverse_transform)
            m = part.args[2] # :(s::Scaling)
            ex2 = quote
                $fn($m, _, args...) = $fn($m,  args...)
            end
            eval(ex2)
        end
    end
    # eval the base def
    ex
end

@static transform(s::Scaling, X) = MLJBase.table(MLJBase.matrix(X)*s.scaling, prototype=X)
@static inverse_transform(s::Scaling, X) = MLJBase.table(MLJBase.matrix(X)/s.scaling, prototype=X)

X = MLJBase.table(randn(5,5))
transform(Scaling(0.5), X)

using MLJ

m = machine(Scaling(0.5), X)
fit!(m)
Xs = transform(m, X)
Xss = inverse_transform(m, Xs)

MLJBase.matrix(X) ≈ MLJBase.matrix(Xss)
```

**Comment by ablaom** [comment]
Many thanks for your time exploring another alternative. However, this is really inferior to your earlier proposal

```julia
mutable struct Scale <: MLJBase.Static
    scaling::Float64
end
transform(s::Scale, _, X) = s.scaling*X
inverse_transform(s::Scale, _, X) = X / s.scaling
```
The two options have a similar burden in terms of novelty (`_` versus `@static`) but the macro option is even more mysterious: I have no idea what a macro does without looking at the code, but I can make a guess about what "_" might mean. 

While I am not completely happy about it, I think my earlier criticisms (which I stand by) have been magnanimously considered here, and suggest we go with this earlier approach, leaving the arrow syntax to claim all model calling behaviour for now.

**Comment by ablaom** [comment]
Still, to do is update documentation to reflect the above.
