### ISSUE TITLE
Make MLJ citable

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#296]
As per Slack discussion, it would be good that MLJ could be cited.

Martin Trapp from Turing.jl suggested  [Zenodo](https://about.zenodo.org/)

cc @vollmersj

**Comment by ablaom** [comment]
Sounds like a good idea to me. Unless someone wants to give me a couple of weeks off development to write a paper 😄

**Comment by tlienart** [comment]
closed with https://github.com/alan-turing-institute/MLJ.jl/issues/331#issuecomment-554173627
