### ISSUE TITLE
Saving metadata about wrapped but not loaded algorithms

### ISSUE THREAD

**Issue by vollmersj** [alan-turing-institute/MLJ.jl#3]
Data about wrapped learner need to be present even if Module is not installed

[FILE.IO](https://github.com/JuliaIO/FileIO.jl/blob/d4e34014e508da06e03ea838bc5440d6fc02732f/docs/registry.md)
[METADATA.JL](https://github.com/JuliaLang/METADATA.jl)

[MLR meta data](https://github.com/mlr-org/mlr/blob/master/R/Learner_properties.R)

**Comment by ysimillides** [comment]
@ablaom has initial work on this (there is now part of the model interface specification), but further work is still needed.

**Comment by ablaom** [comment]
This discussion is continued at #22.
