### ISSUE TITLE
Scitype check after dropping missing values

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#306]
Let's say the dataset has 5 rows, one of them has a `missing` in the target. We may want to drop  it. The issue  is that the resulting target column still has a `Union{Missing,T}` scitype (and machine type) even though it has no missing values. 

so two  things:

1. there should be  an easy way to cast that to  a type without missing
2. the warning that's raised for incompatible scitype should not trigger in such a case

**Comment by tlienart** [comment]
A trick can be to  apply a fill imputer on the data but it feels a bit ugly

**Comment by ablaom** [comment]
https://github.com/alan-turing-institute/ScientificTypes.jl/issues/33

**Comment by ablaom** [comment]
I think https://github.com/alan-turing-institute/ScientificTypes.jl/pull/34, resolving issue in preceding comment makes this issue go away. Re-open if you disagree.
