### ISSUE TITLE
Example of `unpack` in `?unpack` doesn't work: ERROR: MethodError: no method matching !=(::Symbol)

### ISSUE THREAD

**Issue by zygmuntszpak** [alan-turing-institute/MLJ.jl#313]
**Describe the bug**
The usage examples in the documentation of `unpack` don't work.

**To Reproduce**
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 5 1600 Six-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)

Environment:
  JULIA_EDITOR = atom -a
  JULIA_NUM_THREADS = 6

 [add582a8] + MLJ v0.5.2

```julia
using  MLJ
table = DataFrame(x=[1,2], y=['a', 'b'], z=[10.0, 20.0], w=[:A, :B])
Z, XY = unpack(table, ==(:z), !=(:w);:x=>Continuous, :y=>Multiclass)
```

```julia
 Z, XY = unpack(table, ==(:z), !=(:w);:x=>Continuous, :y=>Multiclass)
ERROR: MethodError: no method matching !=(::Symbol)
Closest candidates are:
  !=(::Any, ::Any) at operators.jl:185
  !=(::Float64, ::Float64) at float.jl:450
  !=(::Float32, ::Float32) at float.jl:449
```

**Comment by zygmuntszpak** [comment]
The solution appears to be the following:
Change 

`Z, XY = unpack(table, ==(:z),  !=(:w) ;:x => Continuous, :y => Multiclass)`

to

`Z, XY = unpack(table, ==(:z), w -> w != (:w) ;:x => Continuous, :y => Multiclass)`

In other words, you need to make use of an anonymous function. I figured this out by looking at the test set of `unpack` here: https://github.com/alan-turing-institute/MLJBase.jl/blob/aed7b794b0124f474faea4009da90f6bdfcbaf5f/test/data.jl

**Comment by ablaom** [comment]
Yeah, in julia 1.2 the example works as stated. Probably the doc should be generic or contain an qualification.

**Comment by ablaom** [comment]
Resolved in https://github.com/alan-turing-institute/MLJ.jl/commit/b7f9819f366c07502f9b358e3b6686aa2931522a

**Comment by dnabanita7** [comment]
Well for now, in julia 1.7 and 
```
using  MLJ
table = DataFrame(x=[1,2], y=['a', 'b'], z=[10.0, 20.0], w=[:A, :B])
```
doesn't work.

**Comment by ablaom** [comment]
Thanks for reporting @dnabanita7. The docstring example (with your minor change to `w`) works fine for me, however, on both Julia 1.8.5 and 1.7.3:

```julia
using MLJBase
using DataFrames
julia> table = DataFrame(x=[1,2], y=['a', 'b'], z=[10.0, 20.0], w=[:A, :B])
2×4 DataFrame
 Row │ x      y     z        w      
     │ Int64  Char  Float64  Symbol 
─────┼──────────────────────────────
   1 │     1  a        10.0  A
   2 │     2  b        20.0  B

julia> Z, XY, W = unpack(table, ==(:z), !=(:w))
([10.0, 20.0], 2×2 DataFrame
 Row │ x      y    
     │ Int64  Char 
─────┼─────────────
   1 │     1  a
   2 │     2  b, [:A, :B])

julia> XY
2×2 DataFrame
 Row │ x      y    
     │ Int64  Char 
─────┼─────────────
   1 │     1  a
   2 │     2  b

julia> Z
2-element Vector{Float64}:
 10.0
 20.0

julia> W
2-element Vector{Symbol}:
 :A
 :B
```

Can you please provide more detail about what is not working for you? If you are new to Julia, perhaps you have a package management issue and can report the output of `using Pkg; Pkg.status()`?
