### ISSUE TITLE
Move the MLJ manual to new repo MLJManual

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#316]
Generation of documentation is a serious slowdown for testing in the present MLJ repo. The new repo could ultimately be modelled on the excellent MLJTutorials repository, although I believe that means  converting a bunch of markdown into raw script (could be phase two). 

@tlienart What to you think?

**Comment by tlienart** [comment]
A few comments:

- Moving to another repo is potentially a good idea but decouples release with docs, we'd have to look at how they do it in the DiffEq environment to do that right
- JuDoc could work for docs but does not do some of the things Documenter does like scraping the code and docstrings
- Maybe a temporary solution would be to have the docs only be generated on releases as opposed to  every time we make  a merge on dev ?

**Comment by ablaom** [comment]
https://github.com/alan-turing-institute/MLJ.jl/pull/322  implements "test docs for merges onto #master" only, which will do for now, I think.

Thanks @tlienart  for this.
