### ISSUE TITLE
Streamline tests

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#323]
If enacted, this would potentially lead to a fair bit of refactoring but I believe it's justified.

#### the problem

The situation as it stands now is that we add metrics and models and metadata for these things and add ad-hoc tests for each; there is no elementary standardized testing done across the board and this may lead to bugs further down the route (esp as the code base grows). Things like:

* testing that the metadata can be retrieved correctly and matches what is expected
* testing that models return sensible results
* testing that metrics return sensible results

#### way  forward

When interfacing with sklearn I tried to add something with that in mind; that all  classifiers/regressors would go through the same elementary tests. The same idea can be applied to metrics and can/should be extended to check metadata etc.

While this is reasonably straightforward for metrics e.g.:

* check that everything wrong gives bad score
* check that everything correct gives top score
* check ordering (more correct > less correct)

It's not as easy for models; this is a  well known issue; models may have a stochastic component (this can be alleviated when using Julia models but for things in other languages it requires setting seeds in Python/C etc which is a bit of a  pain) and some models make sense only in specific regimes (e.g. SGD models make little sense on small data) or on specific data.

Anyway I don't have a perfect solution but I think we could agree on a series of standardized tests which would be run by default on everything  (unless expliclitly avoided for Volkswagen-style models); we should also compare with sklearn / MLR whenever our models go a bit beyond what they were written for (e.g. if we add stuff to make the predict in a way we want like in GP or when using weights)

This doesn't have to be done immediately but I think it'd be nice to brainstorm on how we could make testing more systematic and hopefully get a more robust codebase as a result

**Comment by tlienart** [comment]
So after thinking about this, it seems that the MLJTutorials is effectively a kind of integrated test suite which would not require too much extra work. The only thing would be the necessity to trigger a build there whenever new releases are made. Maybe we could  just agree to do this every minor-releases.

**Comment by ablaom** [comment]
Thanks for these comments @tlienart. 

> Maybe we could just agree to do this every minor-releases.

Sound good to me.
