### ISSUE TITLE
Support for class weights (and interpretation)

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#328]
Yesterday  during the call we discussed briefly that we would support a mechanism to specify class weights in MLJ.

A question was asked as to how this relates to  algorithms which can work with a "prior" on classes  such  as (for  instance) (Bayesian)LDA.

Opening an issue here to  keep track  of  the  conversation, input is welcome.

**Comment by ablaom** [comment]
I expect that priors/weights on target classes should be viewed as hyperparameters of the model. 

As articulated [elsewhere](https://github.com/alan-turing-institute/MLJ.jl/issues/177), *per-sample* weights are to be passed as arguments to machines (or `fit`/`update` methods in the model API). 

For the record, @darenasc has a table of the different types of weight support in the scikitlearn models.

**Comment by ablaom** [comment]
Update: see end of this comment: https://github.com/alan-turing-institute/MLJBase.jl/issues/457#issue-749113102
