### ISSUE TITLE
How to cite MLJ?

### ISSUE THREAD

**Issue by mllg** [alan-turing-institute/MLJ.jl#331]
We are writing a short JOSS paper about mlr3, and want to cite MLJ as related work. What is the recommended way to cite it?

**Comment by tlienart** [comment]
Thanks Michel, we currently have not written anything formal on MLJ but you're not the first  one to  ask (xRef #296) so I'll have a  look today to see if I can get MLJ to be an entry in Zenodo and will keep you posted.

**Comment by juliohm** [comment]
I think a JOSS paper for MLJ.jl is a good idea 👍  Their review process is fast, and you can write a more detailed description of the project as part of the repository.

**Comment by mllg** [comment]
The bibtex generated by zenodo is broken, is this ok four you?

```bibtex
@manual{mlj,
    title = {MLJ: A pure Julia machine learning framework},
    author = {Anthony Blaom and Franz Kiraly and Thibaut Lienart and Sebastian Vollmer},
    organization = {Alan Turing Institute},
    year = {2019},
    doi = {10.5281/zenodo.3541505}
}
```

**Comment by tlienart** [comment]
Hey @mllg can I get back to you a bit later on this? I'd like to get feedback from at least anthony before pushing for a specific format, cheers!

**Comment by mllg** [comment]
We will be submitting to JOSS tomorrow, but there usually is still plenty of time to update the references before the paper gets published - I'll ping you here again if necessary.

**Comment by ablaom** [comment]
You can cite this: https://zenodo.org/record/3541506#.Xc4FAC-B1TY

```
@software{anthony_blaom_2019_3541506,
  author       = {Anthony Blaom and
                  Franz Kiraly and
                  Thibaut Lienart and
                  Sebastian Vollmer},
  title        = {alan-turing-institute/MLJ.jl: v0.5.3},
  month        = nov,
  year         = 2019,
  publisher    = {Zenodo},
  version      = {v0.5.3},
  doi          = {10.5281/zenodo.3541506},
  url          = {https://doi.org/10.5281/zenodo.3541506}
}
```
