### ISSUE TITLE
Either update tour or redirect to MLJTutorials. 

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#337]
The tour is quite old. In particular the tuning API has changed since last update. 

There are references to the tour in the README.md (currently under review) but also in the manual.

I believe the "Getting Started" part of MLJTutorials makes the tour redundant, so I suggest this be the target of the updated links. 

Any objections?

**Comment by tlienart** [comment]
I would think once we merge the new README, we can get rid of the `examples/` folder

**Comment by ablaom** [comment]
Agreed. Lets keep this issue open to remind us the links to the tour in the manual need updating.
