### ISSUE TITLE
Ordering of `report(composite).reports`

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#346]
Maybe this has been  addressed already with new functionalities to inspect trained models in a composite model.

What is  the ordering of `report(pipeline).reports`? it  seems to be reverse order but why?

```julia
data = dataset("ISLR", "OJ")

X = select(data, [:PriceCH, :PriceMM, :DiscCH, :DiscMM, :SalePriceMM,
                  :SalePriceCH, :PriceDiff, :PctDiscMM, :PctDiscCH]);
@pipeline SPCA(std = Standardizer(),
               pca = PCA())
spca_mdl = SPCA()
spca = machine(spca_mdl, X)
fit!(spca)
```

To get things like total variance:

```julia
r = report(spca).reports[1]
```

why [1]?

**Comment by ablaom** [comment]
`r = report(spca)` has *two* keys: `machines` and `reports`. The first lists the machines; the second lists the machine reports, in the same order (which I agree, could be reversed in the implementation). So, for example

```julia
julia> r = report(spca)
julia> zip(r.machines, keys.(r.reports)) |> collect
2-element Array{Tuple{Any,Tuple{Symbol,Vararg{Symbol,N} where N}},1}:
 (NodalMachine{PCA} @ 8…50, (:indim, :outdim, :mean, :principalvars, :tprincipalvar, :tresidualvar, :tvar))
 (NodalMachine{Standardizer} @ 1…74, (:features_fit,))  
```

In general the machines trained in a learning network (possibly branching) don't have an intrinsic ordering, so just listing the reports without the corresponding machines is insufficient. 

I acknowledge the fact that what I describe was not obvious. Happy to hear suggestions for a alternative way of collating the machine reports. (Keep in mind that reports are associated with machines and not models. Two machines could potentially point to the same model but have different training outcomes, and hence reports. )

**Comment by ablaom** [comment]
bump @tlienart 

Can I close this?
