### ISSUE TITLE
MLJ releases since 0.5.2 not reflected in the manual

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#374]
I  can't see my recent updates to the [manual](https://alan-turing-institute.github.io/MLJ.jl/v0.5/). The pull down menu for choosing the version includes no entry after 0.5.2 (and the dev and stable options do not appear to reflect either). 

In particular, [this](https://github.com/alan-turing-institute/MLJ.jl/blob/master/docs/src/learning_curves.md) new section does not appear.

**Comment by tlienart** [comment]
Investigating... the builds are done properly as per https://github.com/alan-turing-institute/MLJ.jl/commits/gh-pages, the latest one matching `0.5.6`.

**Comment by tlienart** [comment]
Ok I think this fixes it as we now have:

https://travis-ci.com/alan-turing-institute/MLJ.jl/jobs/263563416#L652-L659

```
┌ Info: Deployment criteria:
│ - ✔ ENV["TRAVIS_REPO_SLUG"]="alan-turing-institute/MLJ.jl" occurs in repo="github.com/alan-turing-institute/MLJ.jl.git"
│ - ✔ ENV["TRAVIS_PULL_REQUEST"]="false" is "false"
│ - ✔ ENV["TRAVIS_TAG"]="" is (i) empty or (ii) a valid VersionNumber
│ - ✔ ENV["TRAVIS_BRANCH"]="master" matches devbranch="master" (if tag is empty)
│ - ✔ ENV["DOCUMENTER_KEY"] exists
│ - ✔ ENV["TRAVIS_EVENT_TYPE"]="pull_request" is not "cron"
└ Deploying: ✔
```

**Comment by tlienart** [comment]
this was automatically  closed by the commit comment but reopening while I'm not 100% sure this is fixed

**Comment by tlienart** [comment]
Ok so this appears now: https://alan-turing-institute.github.io/MLJ.jl/dev/learning_curves/

**Comment by tlienart** [comment]
this should now be fixed 👍 https://alan-turing-institute.github.io/MLJ.jl/stable/
