### ISSUE TITLE
Minor issue in the warning issue caused by missing *

### ISSUE THREAD

**Issue by dsweber2** [alan-turing-institute/MLJ.jl#378]
I would make a pull request, but the overhead is probably more on both ends. In machines.jl, line 54 https://github.com/alan-turing-institute/MLJ.jl/blob/74632f2d4f5ab4c6a79fbe99c250a679ee8cf2bd/src/machines.jl#L54
```
@warn "The scitype of `X`, in `machine(model, X, y)` or "
        "`machine(model, X, y, w)` is "*
```

should be
```
@warn "The scitype of `X`, in `machine(model, X, y)` or " *
        "`machine(model, X, y, w)` is "*
```

**Comment by tlienart** [comment]
nice catch, thank  you
