### ISSUE TITLE
Upgrade to Julia 1.0

### ISSUE THREAD

**Issue by roberthoenig** [alan-turing-institute/MLJ.jl#4]
So far, mlj has been developed with Julia 0.6. With the release of Julia 1.0, we should try to upgrade.

There are no test suites right now, so it'll involve a lot of manual testing to see what's broken.

Please comment your findings on what needs to be changed and other thoughts on the upgrading process :)

**Comment by lsindoni** [comment]
It seems that some of the dependencies might require porting first.

**Comment by lsindoni** [comment]
I'll have a go at MLBase

**Comment by roberthoenig** [comment]
I'm working on fixing the tests for MLLabelUnits

**Comment by ysimillides** [comment]
Works on Julia v1.0 #17
