### ISSUE TITLE
machine run error

### ISSUE THREAD

**Issue by imrankhan441** [alan-turing-institute/MLJ.jl#402]
```julia
iris = dataset("datasets", "iris")
labels = iris[:Species]
data = convert(Matrix, iris[:, 1:4])
tree_model = @load DecisionTreeClassifier
tree = MLJ.machine(tree_model, data, labels) # **NB: [error in this line]**
```
```
ERROR: MethodError: no method matching machine(::Nothing, ::Array{Float64,2}, ::CategoricalArray{String,1,UInt8,String,CategoricalString{UInt8},Union{}})
```

**Again**

`tree = MLJ.machine(tree_model, X, y)`**NB: [error in this line]**

ERROR: MethodError: no method matching machine(::Nothing, ::Array{Float64,2}, ::Array{Int64,1})

**Comment by tlienart** [comment]
Hello, please try:

```julia
julia> X,y = @load_iris;

julia> tree_model = @load DecisionTreeClassifier;
[ Info: Precompiling DecisionTree [7806a523-6efd-50cb-b5f6-3fa6f1930dbb]

julia> tree = machine(tree_model, X, y)
Machine{DecisionTreeClassifier} @ 1…75


julia> fit!(tree)
[ Info: Training Machine{DecisionTreeClassifier} @ 1…75.
Machine{DecisionTreeClassifier} @ 1…75
```

### Note

The thing that causes an issue in your code is the conversion, MLJ does not expect `Array{Float64,2}` as input, it expects **Tables**, so the conversion is what causes problems, it was a DataFrame at the start (assuming  you used  RDatasets) and that's an acceptable format for MLJ.

I'll close this issue but feel free to re-open if that doesn't solve your issue.
