### ISSUE TITLE
Designing a package to interface with julia mlj

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJ.jl#410]
Am currently working on a new package DiscriminantAnalysis.jl that will interface with julia. 
Using MLJ interface with my package makes things easier m
Can I re-export some mljbase functions like `fit!`, `machine`, `predict` for users of my package leaving other things like model composition, tuning, etc to be done from `MLJ`. Or does that affect things

**Comment by tlienart** [comment]
Hello Sam, that's great! you might find  the new readme of MLJModels useful: [here](https://github.com/alan-turing-institute/MLJModels.jl#mljmodels). It offers a step-by-step guide of how to add an  interface to MLJ. 

If  you have issues with the instructions or questions, would you mind opening issues directly on the MLJModels repo? Thanks!
