### ISSUE TITLE
Accuracy metric to tune DecisionTreeClassifier

### ISSUE THREAD

**Issue by darrencl** [alan-turing-institute/MLJ.jl#424]
Hi,

I would like to use `DecisionTreeClassifier` to solve my classification problem. This model will output probability of an observation being in class A. 

As we all know, a common metric in classification is `accuracy`, which is what I want to use. Now, I am able to get the accuracy on the test data `y_pred` comparing to ground truth `y` by
```julia
# test is indices coming from `partition` function
mean(accuracy(mode.(y_pred), y[test])
```

However, I would like to use this as a evaluation metric during hyperparameter tuning, that is the parameter `measure` in `TunedModel`. Is there anyway I can get `accuracy` working for tuning `DecisionTreeClassifier` during training?

```julia
tree = @load DecisionTreeClassifier
# Putting here just as reference
tree_tuned_model = TunedModel(; model=tree,
                                tuning=Grid(),
                                resampling=CV(nfolds=5, shuffle=true),
                                measure=accuracy,
                                ranges=ranges)
```

In case needed, here's the error message and stacktrace (but this pretty much have already been explained above)
```
ArgumentError: 
DecisionTreeClassifier @ 1…60 <: Probabilistic but prediction_type(accuracy) = :deterministic. 
To override measure checks, set check_measure=false. 

Stacktrace:
 [1] _check_measure(::DecisionTreeClassifier, ::MLJBase.Accuracy, ::CategoricalArray{String,1,UInt32,String,CategoricalString{UInt32},Union{}}, ::Function, ::Bool) at /home/darren/.julia/packages/MLJBase/t7MaX/src/resampling.jl:327
 [2] (::getfield(MLJBase, Symbol("##270#271")){Machine{DecisionTreeClassifier},typeof(predict),Bool})(::MLJBase.Accuracy) at ./none:0
 [3] iterate at ./generator.jl:47 [inlined]
 [4] collect(::Base.Generator{Array{MLJBase.Accuracy,1},getfield(MLJBase, Symbol("##270#271")){Machine{DecisionTreeClassifier},typeof(predict),Bool}}) at ./array.jl:606
 [5] _process_weights_measures(::Nothing, ::MLJBase.Accuracy, ::Machine{DecisionTreeClassifier}, ::Function, ::Int64, ::Bool) at /home/darren/.julia/packages/MLJBase/t7MaX/src/resampling.jl:358
 [6] fit(::Resampler{CV,DecisionTreeClassifier}, ::Int64, ::DataFrame, ::CategoricalArray{String,1,UInt32,String,CategoricalString{UInt32},Union{}}) at /home/darren/.julia/packages/MLJBase/t7MaX/src/resampling.jl:736
 [7] #fit!#140(::Nothing, ::Int64, ::Bool, ::Function, ::Machine{Resampler{CV,DecisionTreeClassifier}}) at /home/darren/.julia/packages/MLJBase/t7MaX/src/machines.jl:180
 [8] (::getfield(StatsBase, Symbol("#kw##fit!")))(::NamedTuple{(:verbosity,),Tuple{Int64}}, ::typeof(fit!), ::Machine{Resampler{CV,DecisionTreeClassifier}}) at ./none:0
 [9] fit(::MLJ.ProbabilisticTunedModel{Grid,DecisionTreeClassifier}, ::Int64, ::DataFrame, ::CategoricalArray{String,1,UInt32,String,CategoricalString{UInt32},Union{}}) at /home/darren/.julia/packages/MLJ/YWvn8/src/tuning.jl:299
 [10] #fit!#140(::Array{Int64,1}, ::Int64, ::Bool, ::Function, ::Machine{MLJ.ProbabilisticTunedModel{Grid,DecisionTreeClassifier}}) at /home/darren/.julia/packages/MLJBase/t7MaX/src/machines.jl:180
 [11] (::getfield(StatsBase, Symbol("#kw##fit!")))(::NamedTuple{(:rows,),Tuple{Array{Int64,1}}}, ::typeof(fit!), ::Machine{MLJ.ProbabilisticTunedModel{Grid,DecisionTreeClassifier}}) at ./none:0
 [12] top-level scope at In[245]:2
```

Thanks!

**Comment by OkonSamuel** [comment]
Greetings @darrencl  the `DecisionTreeClassifier` is `probabilistic` while the `accuracy` measure is strictly for `deterministic` responses. To overcome you can wrap the `DecisionTreeClassifier` in a `pipeline` as thus
```julia
 tree = @load DecisionTreeClassifier
tree_classifier= @pipeline Tree_Model(model = tree,
                                                           yhat -> mode.(yhat)) # predicts the modal class.
```
then create the `TunedModel` as
```julia
ranges = range(tree_classifier,
                          :(model.min_purity_increase), 
                          lower=0.01,
                          upper=1.0,
                          scale = :log)
self_tuning_tree_classifier = TunedModel(; model=tree_classifier,
                                tuning=Grid(),
                                resampling=CV(nfolds=5, shuffle=true),
                                measure=accuracy,
                                ranges=ranges)
self_tuning_tree = machine(self_tuning_tree_classifier, X, y)
```
Note: y must be a categorical array.

**Comment by ablaom** [comment]
Okay, one problem  is that the `accuracy` measure applies to `Deterministic` model predictions, rather than `Probabilistic` model predictions:

```julia
julia> info(accuracy).prediction_type
:deterministic

julia> info("DecisionTreeClassifier").prediction_type
:probabilistic
```

To overcome this, try adding the keyword `operation=predict_mode` to your `TunedModel` constructor (or calls to `evaluate!`). This overrides the default `operation=predict` (for when you want to use a probabilistic measure).

That said, you may instead want to consider a more informative measure, that *is* probabilistic, such as `BrierScore()` or `cross_entropy`, depending on your use case.  Here are all of them:

```julia
julia> measures(m->m.prediction_type == :probabilistic)
15-element Array{NamedTuple{(:name, :target_scitype, :supports_weights, :prediction_type, :orientation, :reports_each_observation, :aggregation, :is_feature_dependent, :docstring, :distribution_type),T} where T<:Tuple,1}:
 (name = auc, ...)                         
 (name = cross_entropy, ...)               
 (name = BrierScore(UnivariateFinite), ...)
 (name = DWDMarginLoss(), ...)             
 (name = ExpLoss(), ...)                   
 (name = L1HingeLoss(), ...)               
 (name = L2HingeLoss(), ...)               
 (name = L2MarginLoss(), ...)              
 (name = LogitMarginLoss(), ...)           
 (name = ModifiedHuberLoss(), ...)         
 (name = PerceptronLoss(), ...)            
 (name = ScaledMarginLoss(), ...)          
 (name = SigmoidLoss(), ...)               
 (name = SmoothedL1HingeLoss(), ...)       
 (name = ZeroOneLoss(), ...)       
```

For example, we have:

```julia
julia> info(BrierScore())
Brier proper scoring rule for `MultiClass` data; aliases: `BrierScore()`, `BrierScore(UnivariateFinite)`
(name = "BrierScore(UnivariateFinite)",
 target_scitype = AbstractArray{#s126,1} where #s126<:Finite,
 supports_weights = true,
 prediction_type = :probabilistic,
 orientation = :score,
 reports_each_observation = true,
 aggregation = MLJBase.Mean(),
 is_feature_dependent = false,
 docstring = "Brier proper scoring rule for `MultiClass` data; aliases: `BrierScore()`, `BrierScore(UnivariateFinite)`",
 distribution_type = UnivariateFinite,)
```

**Comment by ablaom** [comment]
Okay, there you have two solutions. Take your pick

**Comment by darrencl** [comment]
Thanks @OkonSamuel @ablaom !

While you guys are here, I have one more question (unrelated, but I just posted here rather than opening up a new issue)

So essentially, I would like to do a grid search, not only for the model hyper-parameter, but also for my data preprocessing parameters. So, for instance I have this preprocessing function:

```
function preprocess(param1, param2)
   ...
end

# 1. Load data
# 2. Partition, etc
# 3. Grid search of pre-processing (param1 and param2) 
#     along with the model tuning according to evaluation metric
```
I am just wondering if there is any `MLJ`-way of doing that sort of workflow or I do need to implement my own grid search for pre-processing parameter?

**Comment by OkonSamuel** [comment]
* MLJ can only load data that is built into the package e.g boston dataset. To load other datasets you can make use  of packages like [CSV.jl,](https://github.com/JuliaData/CSV.jl) [RDatasets.jl](https://github.com/JuliaStats/RDatasets.jl) etc,
* MLJ allows for data preprocessing (e.g using an unsupervised model like `FeatureSelector` etc.) and partitioning (i.e Selecting the portion of data to fit on ).
* These preprocessing models can be comibined with other models in a **Linear Pipeline** or **Learning Network**.
* MLJ allows for parameter tuning of all models (i.e including `LinearPipelines` and ``Learning Networks`) by wrapping with a `TunedModel` as shown above.
* Both numerical and non-numerical hyperparameters can be tuned.

As a quick example lets say you want combine `FeatureSelector` (preprocessing step) with a `DecisionTreeClassifier` using a pipeline as
```julia
# First create the pipepline
tree = @load DecisionTreeClassifier
tree_classifier = @pipeline Tree_Model(preprocessor= FeatureSelector(), model = tree) prediction_type=:probabilistic

#Then wrap it with a TunedModel
r1 = range(tree_classifier, :(model.min_purity_increase), lower=0.001, upper=1.0, scale = :log) # NumericRange
r2 = range(tree_classifier, :(preprocessor.features), values = [[:x1,], [:x1, :x2]]) # defines norminal range
 tuned_tree_model = TunedModel(; model=tree_classifier, 
                                   tuning = Grid(), 
                                   resampling = CV(nfolds=5, shuffle=true), 
                                   measure = accuracy, 
                                   ranges = [r1, r2], 
                                   operation = predict_mode)

# then fit the TunedModel to tune the selected hyperparameters of the tree classifier (i.e preprocessor and tree_model)
X = (x1=rand(100), x2=rand(100), x3=rand(100));
y = repeat(["a","b","c","d"], outer=25)
y = categorical(y)[shuffle(1:100)]
mach= machine(tuned_tree_model, X, y)
fit!(mach)
best_model = fitted_params(mach).best_model

```
Hope this helps.
for more information see [https://alan-turing-institute.github.io/MLJ.jl/stable/tuning_models/)

**Comment by darrencl** [comment]
Thanks!

**Comment by darrencl** [comment]
Hey @OkonSamuel 

Just to confirm, by the look at [the source code](https://github.com/alan-turing-institute/MLJModels.jl/blob/e68f7cbf8a41dff3f79d8bc6f90962cc3f92b415/src/builtins/Transformers.jl) I can define my own pre-processing (e.g. `my_custom_transformer(skew=0)`) function and chuck it into the pipeline by extending `MLJBase.Unsupervised`? 

Then, the `MLJBase.fit` seems to filter which features we wanted to `transform`, so the hard work is done by the transform?

```
function my_transform(row, skew)
    # Some transformation
end

@with_kw_noshow mutable struct MyCustomTransformer <:MLJBase.Unsupervised
    skew
end

# I want to transform all features
function MLJBase.fit(transformer::MyCustomTransformer, verbosity::Int, X)
    fitresult = collect(Tables.schema(X).names)
    report = NamedTuple()
    return fitresult, nothing, report
end

MLJBase.fitted_params(::MyCustomTransformer, fitresult) = (features_to_keep=fitresult,)

MLJBase.transform(transformer::MyCustomTransformer, fitresult, X)
    map(row -> my_transform(row, transformer.skew), eachrow(X))
end

# Then, I can tune the 'hyper-parameter' skew by
tree_classifier = @pipeline Tree_Model(preprocessor= MyCustomTransformer(), model = tree) prediction_type=:probabilistic

#Then wrap it with a TunedModel
... # load and initialize model and pipeline
r1 = range(tree_classifier, :(model.min_purity_increase), lower=0.001, upper=1.0, scale = :log) # Model hyper-parameter
r2 = range(tree_classifier, :(preprocessor.skew), values = Vector(0.1:0.1:0.5) # Preprocessing hyper-parameter

tuned_tree_model = TunedModel(; model=tree_classifier, 
                                   tuning = Grid(), 
                                   resampling = CV(nfolds=5, shuffle=true), 
                                   measure = accuracy, 
                                   ranges = [r1, r2], 
                                   operation = predict_mode)
... # Train, test, get best hyper-params (skew + min_purity_increase)
fitted_params(mach).best_fitted_params
```
That's the rough code I can think of, is that sounds about right? Anyway, I wanted to do row-based transformation since 1 row in my data is 1 spectrum. How can I do that in `MLJBase.transform` (the code above seems to transform per column/feature)?

Thanks!

**Comment by OkonSamuel** [comment]
@darrencl yes your right the `@with_kw_noshow` keyword is from [parameters.jl](https://github.com/mauro3/Parameters.jl) and for your use case it should be defined as:

```
@with_kw_noshow mutable struct MyCustomTransformer <:MLJBase.Unsupervised
    skew :: Real =0.0 #I assigned a type real and a default value 0.0
end
```
Also since `:(prepocessor.skew)` is a subtype of `Real` then `r2` should be defined as:
```
r2 = range(tree_classifier, :(model.prepocessor.skew), lower=0.1, upper=0.4, scale = :linear)
```
The rest of your code seems okay to me.

**Comment by darrencl** [comment]
@OkonSamuel Thanks! Anyway, I am just wondering with `lower`, `upper`, and `scale=:linear` arguments. For instance, in `lower=0.1, upper=0.4, scale = :linear`, are they supposed to be `0.1, 0.2, 0.3, 0.4`?

Cause I think I got weird result on having these following ranges

```
# t1pad and pow are in Int64 type
ranges = [range(classifier, :(preprocessor.t1pad), lower=1, upper=2, scale = :linear),
          range(classifier, :(preprocessor.skew), lower=0.1, upper=0.3, scale = :linear),
          range(classifier, :(preprocessor.pow), lower=1, upper=2, scale = :linear)]
```

That seems to iterate over 40-point grid. I would expect 80 from that if I calculated correctly (2*20*2)

**Comment by OkonSamuel** [comment]
@darrencl the grid generated by ` range(classifier, :(preprocessor.skew); upper=0.1, lower=0.4, scale=:linear)` depends on the `resolution` keyword in `Grid` function set in the `TunedModel` constructor and type of skew (Float64?).
For example for range `r1 = range(classifier, :(preprocessor.skew); upper=0.1, lower=0.4, scale=:linear)` setting `Grid(resolution=4)` tunes over a `[0.1, 0.2, 0.3, 0.4]` grid whereas setting `Grid(resolution=7)` tunes over a `[ 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4]` grid
Another example defining a range `r1 = range(classifier, :(preprocessor.t1pad), lower=1, upper=3, scale = :linear)` in a `TunedModel creates [1, 2, 3] grid if `resolution` >=3 and  [1, 3] grid if `resolution` <3
see `iterator` and `Grid` function in [docs](https://alan-turing-institute.github.io/MLJ.jl/v0.7/tuning_models/) for more details

Therefore assuming a default `resolution` of 10 the code below tunes over a  40 (i.e 2*10*2) point grid.
```
# t1pad and pow are in Int64 type
ranges = [range(classifier, :(preprocessor.t1pad), lower=1, upper=2, scale = :linear) ,
          range(classifier, :(preprocessor.skew), lower=0.1, upper=0.3, scale = :linear),
          range(classifier, :(preprocessor.pow), lower=1, upper=2, scale = :linear)]
```

**Comment by darrencl** [comment]
Hi @OkonSamuel I am implementing those and having issue with the performance. I am creating another issue for this cause maybe it'll be a new discussion. Would you mind having a quick look at that (#440 )? 

Thanks a lot!
