### ISSUE TITLE
Decoder rounding

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#43]
While looking at the GaussianProcesses case, I noticed that their method spews out floats. So for instance your training labels may be `1,1,2,1,...` and the return would be `0.99, 1.11, ...`. 

Since the inverse transform expects the same type as the input type, there's an extra step needed which I coded as:

```julia
nlevels = length(decoder.pool.levels)
pred_rc = clamp.(round.(Int, pred), 1, nlevels)
```

But this is a bit of a hack and it seems to me this should be addressed within the `inverse_transform` maybe? Or maybe I missed something that was already present.

**Comment by ablaom** [comment]
The decoder expects the same input type for inverse_transform as output by transform. Any other behaviour would be confusing, it seems to me. I am not familiar with the package to know what float predictions are supposed to mean.

**Comment by tlienart** [comment]
So what would you suggest in this case? that the work around I proposed is ok for now and will be applied for any model that outputs floats instead of classes?

As far as I'm aware there are other algorithms that convert the class number into a continuous float and try to predict that (e.g. Poisson regression model IIRC). 

I understand it may not be a good idea to do this rouding/clamping inside the inverse_transform though. But it might be worth investigating to see what sklearn does.

**Comment by tlienart** [comment]
I need to understand their code in more depth, see also https://github.com/STOR-i/GaussianProcesses.jl/issues/108. 

The problem is that their doc is severely lacking so it's kind of hard to get in the nitty gritty without just reading the whole code.

I do believe that what I've coded is effectively a count regression and therefore produces ordered categorical instead of classes. Once they get back to me I'll come back here and adjust correspondingly.

**Comment by fkiraly** [comment]
short comment which is potentially helpful (or not): I don't see any in-principle reason for that the decoder (aka inverse transform) should be *mathematically* the exact inverse of the encoder, so why not allow the user to put out-of-bound fixes etc in the decoder?

**Comment by ablaom** [comment]
This implementation has a some flaws and I disabled it. Roughly, the  problem is the a GP Regressor is being used to carry out GP Classification.

**Comment by ablaom** [comment]
This discussion seems a little stale now. Feel free to  re-open or just continue discussion
