### ISSUE TITLE
Adhere by Invenia's bluestyle

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#434]
To  help guide future PRs and generally  converge towards "one style" for MLJ repos, I suggest we formally commit to  Invenia's [blue style](https://github.com/invenia/BlueStyle). It's well  thought  out and it's not very far from what we're kind of organically doing in MLJ and MLJBase anyway.

One difference is  the line limit which at the moment is very arbitrarily set everywhere in the MLJ universe, I think @ablaom uses < 80, I tend to use 80 and they  suggest < 92. I reckon let's just pick any number and stick to it. Atom uses 80 by default so that could work...

These things might seem like they don't matter but I think it may help eventual convergence towards "clean code" where the style is similar throughout which would help new contributors find their way around the code & contribute.

**Comment by ablaom** [comment]
I'm happy with 80 character limit.

**Comment by ablaom** [comment]
https://github.com/alan-turing-institute/MLJ.jl/blob/master/CONTRIBUTING.md
