### ISSUE TITLE
Working with models with the same name from different packages

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#446]
I believe we talked about this a while back but I couldn't find the relevant issue.

In a session if I have `@load LinearRegressor pkg=GLM`  and then further I want  to do `@load LinearRegressor pkg=MLJLinearModels` I believe this should remove the previous one and overwrite `LinearRegressor` with the latest call (so here from MLJLM). 

thoughts?

**Comment by ablaom** [comment]
Okay, I guess it shouldn't be too hard to fix so that the second call overwrites the first, and that's certainly valuable. 

A more serious issue I have been sitting on is this: Maybe you want to load them both at the same time to schedule benchmarking (comparing multiple models on given data). In that case I guess we want syntax like 

```julia
@load LinearRegressor as LR1 pkg=MLJLinearModels
@load LinearRegressor as LR2 pkg=GLM
```

Yes?

**Comment by tlienart** [comment]
Yes that looks very sensible :+1:

**Comment by ablaom** [comment]
Okay, I don't see how we can just overwrite type definitions. I suggest we implement the `@load ... as` syntax, and then if someone attempts to load a model whose name is already taken, then we automatically generate a new name.

**Comment by ablaom** [comment]
Here's the current behaviour:

```julia
julia> model1 = @load LinearRegressor pkg=GLM
[ Info: Precompiling GLM [38e38edf-8417-5370-95a0-9cbb8c7f171a]
LinearRegressor(
    fit_intercept = true,
    allowrankdeficient = false) @ 1…62

julia> model2 = @load LinearRegressor pkg=MLJLinearModels
┌ Info: A model type "LinearRegressor" is already loaded. 
└ No new code loaded. 
LinearRegressor(
    fit_intercept = true,
    allowrankdeficient = false) @ 6…49
```

Actually, I think if we just cut out one check the second will load just fine. It's just the the two *type* names that will have to be qualified. But I haven't checked this.

**Comment by ablaom** [comment]
Closed in favour of https://github.com/alan-turing-institute/MLJModels.jl/issues/242
