### ISSUE TITLE
What parts of MLJBase should be reexported in MLJ

### ISSUE THREAD

**Issue by vollmersj** [alan-turing-institute/MLJ.jl#462]
I noticed StaticTransformer has remainded in MLJBase whereas as all other transformer moved to MLJModels. So if you do 
```
using MLJ
using MLJModels
```
you still dont have access to StatiticTransformer. This could be simply fixed with export in MLJ.jl

**Comment by juliohm** [comment]
This reflects are more serious issue with export conventions. We should
probably use Reexport.jl to reexport all submodules names automatically.
See GeoStatals.jl for reference. The @reexport macro reexports all exported
names in the submodules.

**Comment by ablaom** [comment]
@sjvollmer `StaticTransformer` is no longer meant for general use. Use `Static` instead.

Sorry the docs are bit buried at https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/#Static-operations-on-nodes-1 but #393 should fix this.

@juliohm I don't believe we just re-export every submodule method, so this is not a simple refactor.
