### ISSUE TITLE
Overload model traits to work on the named-tuple "proxies" for models listed by models()

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#464]
So, it would be nice to be able to do

```julia
models(is_pure_julia)
```
instead of the more awkward

```julia
models(m->m.is_pure_julia)
```

We could simply overload the model traits to do this. We already have (MLJModels/src/model_search.jl):

```julia
ModelProxy = Union{NamedTuple{SUPERVISED_PROPERTYNAMES},
                   NamedTuple{UNSUPERVISED_PROPERTYNAMES}}
```

So, we do

```julia
is_pure_julia(m::ModelProxy) = getproperty(m, :is_pure_julia)
```
but do this automatically for all traits with an `eval` loop. 

cc @juliohm

**Comment by ablaom** [comment]
This should be done at MLJModels/src/model_search.jl

**Comment by OkonSamuel** [comment]
@ablaom. This only makes sense for traits returning boolean responses(e.g `is_pure_julia`). For other traits i don't think this works(e.g `models(pakage_name == "pakage")`. So maybe it's better to overload only on selected traits. Happy to open  PR in that regard if this is fine with you,

**Comment by ablaom** [comment]
Yes, you are right! `models(m -> package_name(m)=="package")` is no simpler than `models(m -> m.package_name=="package")`. But maybe its confusing to just overload some of the traits. We could do all of them, but that would include `name`, currently not in scope, which might cause annoying conflicts with other uses. 

On reflection, the status quo is probably preferable. 

@OkonSamuel What do you think?

**Comment by OkonSamuel** [comment]
@ablaom. This status quo is fine by me.

**Comment by ablaom** [comment]
Thanks for the offer of help
