### ISSUE TITLE
Automatic Ensembling options

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJ.jl#466]
Right now I find the most convenient ensembling framework to be [SuperLearner](https://github.com/ecpolley/SuperLearner). 
I don't know if MLJ currently has similar options, but I think it would be super helpful. 

Does anyone here use other ensembling interfaces w/ features they like?

**Comment by ablaom** [comment]
I'm not familiar with the package. I'm assuming your talking about (large) homogeneous ensembles? 
In that case MLJ has `EnsembleModel` which is a model wrapper. These are covered in the docs and MLJTutorials. But it only provides bagging, at this point. (No boosting, for example.) There is an issue open to add some other functionality: https://github.com/alan-turing-institute/MLJ.jl/issues/363

If you are talking about inhomogeneous ensembles, and composite models more generally, then MLJ already has a pretty flexible API. You can, for example, build a [stacking](https://alan-turing-institute.github.io/MLJTutorials/getting-started/stacking/) composite model (with out-of-sample base learner predictions) with it.

**Comment by ablaom** [comment]
Closing in favour of #363. If that issue is not applicable, please feel free to re-open with a clarification of intent.
