### ISSUE TITLE
Julia v1.4.0 is downloading MLJ v0.2.3 instead of MLJ v0.10.1

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJ.jl#476]
Julia v1.4.0 is downloading MLJ v0.2.3 instead of MLJ v0.10.1

**Comment by DilumAluthge** [comment]
Can you reproduce this in a fresh environment?

I.e. if you run `rm -rf ~/.julia`, and then you open Julia and do `Pkg.add("MLJ")`, what happens?

**Comment by azev77** [comment]
@DilumAluthge 
it now downloaded the latest MLJ.jl. 
Very strange!

**Comment by DilumAluthge** [comment]
When in doubt, it never hurts to try setting a up a fresh set-up with `rm -rf ~/.julia`.

**Comment by DilumAluthge** [comment]
@azev77 I think this issue can be closed?

**Comment by azev77** [comment]
Thank you @DilumAluthge 
Though other users might have similar challenges so it might be worth keeping your `rm` trick easily visible

**Comment by ablaom** [comment]
@DilumAluthge This fix sounds pretty drastic. I have a lot of shared environments that would presumably be lost with this. Is there a more surgical fix you can recommend?

**Comment by azev77** [comment]
@ablaom 
the world needs more surgical fixes right now
See discussion: https://discourse.julialang.org/t/julia-v1-4-0-has-been-released/36324/16
