### ISSUE TITLE
Treatment of supervised models predicting an ordered categorical

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#48]
Currently, `target_kind` can be `:nominal` or `:numeric`, with `:numeric` including ordered categoricals. These last must be represented as integers by the user but predictions can be continuous (or pdf's with continuous support). Is this satisfactory, or do we want to formally separate out the ordered categorical case?

The new proposal could be:

(i) replace `[:nominal, :numeric]` options with `[:factor, :ordered_factor, :continuous]` 
(ii) implementers of the interface for an algorithm with `:ordered_factor` targets can expect the target(s) to be ordered `CategoricalVector`'s for case of finite number of classes and `Vector{<:Integer}` for the infinite case.
(iii) in infinite class case, `predict` can output a continuous value (float) if available. In finite case a discrete prediction is required.

**Comment by fkiraly** [comment]
Hm, the meta-data design can cope with this, so MLJ would know when a method cannot deal with the presented variable type?

From the methodological perspective, I see no problem, and a potential benefit - there is a vast array of methods specifically dealing with ordinal (non-continuous) variables.

A potential issue arises from the practical side: R, in theory, also has an ordinal type, but to my knowledge it is cumbersome to use and methods that would be expected to work with it often break for strange reasons. I'm not sure about reasons and have simply avoided it in the past, so maybe someone has more insight about the potential pitfall?

**Comment by ablaom** [comment]
Done
