### ISSUE TITLE
Add info with workaround to avoid MKL error

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#491]
Add the following in some format in the README

> Finally another note, for mac users there is currently an issue with Julia on >=1.3 (unrelated to MLJ) which may make you see weird MKL errors when using MLJ with SckitLearn packages. There is a simple work around which is to install an older version of OpenSpecFun_jll; given that these _jll packages have weird version names, it’s a bit tricky to do and long story short I’ve forked the repo with the right version. In order to use it and avoid the errors, please just do Pkg.develop(PackageSpec(url="https://github.com/tlienart/OpenSpecFun_jll.jl")) in your MLJ environment. This will be a temporary workaround while the Julia folks solve the core issue (which might take a while).

+ link to [Discourse disscussion](https://discourse.julialang.org/t/julia-1-3-1-4-on-macos-and-intel-mkl-error/36469/2)
+ link to [Package builder issue](https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/700)

**Comment by ablaom** [comment]
Done. Thanks @tlienart for all the work here.

**Comment by azev77** [comment]
@ablaom you prob are aware, but the reader doesn’t mention some new models including LightGBM, unless you’re deliberately waiting
