### ISSUE TITLE
Broken link for MLJ tour in documentation

### ISSUE THREAD

**Issue by MaximeBouton** [alan-turing-institute/MLJ.jl#501]
**Describe the bug**

There is a broken link in the documentation: 
https://alan-turing-institute.github.io/MLJ.jl/stable/julia_blogpost/#Introduction-1
The link to MLJ tour is broken

**To Reproduce**

click here: https://github.com/alan-turing-institute/MLJ.jl/blob/master/docs/src/tour.ipynb

**Comment by MaximeBouton** [comment]
This one two: self tuning random forest, https://github.com/alan-turing-institute/MLJ.jl/blob/master/examples/random_forest.ipynb

**Comment by ablaom** [comment]
Indeed. Thanks for that. 

These links are from a old blog post and point to resources that are now dead. Please visit https://github.com/alan-turing-institute/MLJTutorials which has subsumed these resources. 

For a more recent overview of the MLJ design, see the [MLJ design paper](https://github.com/alan-turing-institute/MLJ.jl/blob/master/paper/paper.md) but note this is not a final, published document. 

I have updated the document. It will be live after next parch release.
