### ISSUE TITLE
Conflict w Scikitlearn.jl

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJ.jl#502]
In a fresh Julia installation. 
```julia
using Pkg; Pkg.add(["MLJ", "MLJModels"])
Pkg.add(["ScikitLearn"])
```
Installs `ScikitLearn v0.5.1` instead of the [latest](https://github.com/cstjean/ScikitLearn.jl/releases) `ScikitLearn v0.6.1`

Next, when I install all other MLJ model packages: 
```julia
Pkg.add([
    "Clustering",
    "DecisionTree",
    "EvoTrees",
    "GLM",
    "LightGBM",
    "LIBSVM",
    "MLJLinearModels",
    "MultivariateStats",
    "NaiveBayes",
    "NearestNeighbors",
    "ParallelKMeans",
    #"ScikitLearn",
    "XGBoost"
])
```
& find all other model packages are the latest.

Finally `Pkg.add(["RDatasets", "TableView", "DataFrames"])`
Installs: 
RDatasets v0.6.1  & not 0.6.7 
TableView v0.4.1  & not 0.6.0

TableView is prob outside of your scope, but I think conflicts w/ MLJ relevant packages are an issue.

**Comment by ablaom** [comment]
Please note that *none* of the packages you mention are dependencies of any MLJ repository. That is, none of them are listed as [deps] and  therefore none have [compat] entries either. It follows that MLJ does not place any direct upper bound on their versions. 

That said, the [compat] entries in MLJ (and the other MLJ repos) do indirectly effect what version of your favourite packages you want to use with MLJ. If you can identify a [compat] entry that could be updated to allow this, please open an issue. However, determining if this is possible requires some investigation. You could start by installing `ScitkitLearn` in a fresh env, pinning it at the version you want, and adding MLJ and MLJModels after that. I expect you will get a conflict error message which will help us determine the problem. However, we may need some other 3rd party package shared by both to update *their* [compat], and so forth. 

Welcome to dependency hell. 👿 You didn't escape it by switching to Julia. It is everywhere.

**Comment by ablaom** [comment]
Sorry, I should have pointed out that appreciate the information you have posted here - the ScikitLearn one is particularly interesting. Thanks!

Also, we are aware of the CategoricalArrays 0.8 update but are waiting on DataFrames and CSV to update theirs - otherwise some of our CI testing breaks. There is small possibility this will fix the RDatasets issue.

**Comment by azev77** [comment]
This issue can prob be closed. 
A possible solution is `instantiatefromURL` which I mentioned to @tlienart in the tutorials repo...
