### ISSUE TITLE
MLJ_VERSION code does not work if MLJ is not at the top-level

### ISSUE THREAD

**Issue by DilumAluthge** [alan-turing-institute/MLJ.jl#508]
If MLJ is not installed at the top level of the project (e.g. it is a dependency of some other package), then the MLJ_VERSION code will fail.

I'll submit a fix shortly.

**Comment by ablaom** [comment]
Fixed: https://github.com/JuliaRegistries/General/pull/13886

**Comment by DilumAluthge** [comment]
Thank you @ablaom :)
