### ISSUE TITLE
Cannot add MLJ conflicting with Plots.jl and RecipesBase.jl

### ISSUE THREAD

**Issue by BoundaryValueProblems** [alan-turing-institute/MLJ.jl#516]
I could add and use MLJ before the recent updates and improved Plots.jl package, but not any more. I have installed and been using the following versions of Plots.jl:
```
 [91a5bcdd] Plots v1.2.0 #master (https://github.com/JuliaPlots/Plots.jl.git)
 [3cdcf5f2] RecipesBase v1.0.1
```
When I try to add MLJ, I got the following conflicts:

```julia
(@v1.4) pkg> add MLJ
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package MLJ [add582a8]:
 MLJ [add582a8] log:
 ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.5, 0.3.0, 0.4.0, 0.5.0-0.5.9, 0.6.0-0.6.1, 0.7.0, 0.8.0, 0.9.0-0.9.3, 0.10.0-0.10.3, 0.11.0-0.11.2] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.1, 0.2.0-0.2.5, 0.3.0, 0.4.0, 0.5.0-0.5.9, 0.6.0-0.6.1, 0.7.0, 0.8.0, 0.9.0-0.9.3, 0.10.0-0.10.3, 0.11.0-0.11.2]
 ├─restricted by compatibility requirements with RecipesBase [3cdcf5f2] to versions: [0.8.0, 0.9.0-0.9.3, 0.10.0-0.10.3, 0.11.0-0.11.2] or uninstalled, leaving only versions: [0.8.0, 0.9.0-0.9.3, 0.10.0-0.10.3, 0.11.0-0.11.2]
 │ └─RecipesBase [3cdcf5f2] log:
 │   ├─possible versions are: [0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 1.0.0-1.0.1] or uninstalled
 │   └─restricted to versions 1 by Plots [91a5bcdd], leaving only versions 1.0.0-1.0.1
 │     └─Plots [91a5bcdd] log:
 │       ├─possible versions are: 1.2.0 or uninstalled
 │       └─Plots [91a5bcdd] is fixed to version 1.2.0
 └─restricted by compatibility requirements with MLJTuning [03970b2e] to versions: [0.1.0-0.1.1, 0.2.0-0.2.5, 0.3.0, 0.4.0, 0.5.0-0.5.9, 0.6.0-0.6.1, 0.7.0] or uninstalled — no versions left
   └─MLJTuning [03970b2e] log:
     ├─possible versions are: [0.1.0-0.1.4, 0.2.0, 0.3.0-0.3.3] or uninstalled
     └─restricted by compatibility requirements with RecipesBase [3cdcf5f2] to versions: uninstalled
       └─RecipesBase [3cdcf5f2] log: see above
```
Thanks for your help!

**Comment by OkonSamuel** [comment]
If you don't mind you can install MLJ in a new enviroment thus
```julia
julia> using Pkg; Pkg.activate("My_MLJ_env", shared=true)
julia> Pkg.add(["MLJ", "MLJModels"])
```

**Comment by BoundaryValueProblems** [comment]
@OkonSamuel ; thank you very much! I could install MLJ in the new environment as you suggested. Then, I added Plots.jl. I could add it, but the installed version of Plots.jl was 0.29.9 instead of 1.2.0. When I tried to install Plots.jl v1.2.0, however, it generated the same version conflict errors as I initially reported. It would be really nice if the MLJ team could resolve this issue since the Plots team spent a large amount of time to improve and update it to reach v1.2.0. Thanks!

**Comment by OkonSamuel** [comment]
@BoundaryValueProblems  the new enviroment is shared  and should be only for MLJ (you can still use all your installed packages from the new enviroment by call `using package`). You can install Plots in the old enviroment (remove MLJ from the old enviroment to avoid conflicts with plots).

**Comment by OkonSamuel** [comment]
@BoundaryValueProblems. does it work now??

**Comment by BoundaryValueProblems** [comment]
Yes, it works. I didn't know that from the new environment, I still can use the packages I added. So this way, for the moment, I can run both the latest version of Plots.jl and MLJ. But as I said, it is not yet ideal in that we have to set up a different environment. So hopefully, MLJ can be added without creating a new environment in the near future!

**Comment by ablaom** [comment]
@OkonSamuel Thanks for this.

**Comment by BoundaryValueProblems** [comment]
@OkonSamuel and @ablaom Considering https://github.com/alan-turing-institute/MLJ.jl/issues/522, please open this issue. It's not really resolved. Using the newly-created environment is not ideal, and not the true solution. Thanks!

**Comment by azev77** [comment]
@BoundaryValueProblems 
I agree that using a new environment is not ideal. I’m not sure there is a good long run alternative

**Comment by OkonSamuel** [comment]
@BoundaryValueProblems  https://github.com/alan-turing-institute/MLJTuning.jl/issues/45 should resolve this

**Comment by ablaom** [comment]
https://github.com/JuliaRegistries/General/pull/14377

**Comment by BoundaryValueProblems** [comment]
@OkonSamuel and @ablaom ; Thank you very much! Now, I can use MLJ without creating a new environment!!
