### ISSUE TITLE
possible test failure in upcoming Julia version 1.5 

### ISSUE THREAD

**Issue by rfourquet** [alan-turing-institute/MLJ.jl#517]
A PkgEval run for a Julia [pull request](https://github.com/JuliaLang/julia/pull/29240) which changes the generated numbers for `rand(a:b)` indicates that the tests of this package might fail in Julia 1.5 (and on Julia current master branch).

Also, you might be interested in using the new [StableRNGs.jl](https://github.com/rfourquet/StableRNGs.jl) registered package, which provides guaranteed stable streams of random numbers across Julia releases.

Apologies if this is a false positive. Cf. https://github.com/JuliaCI/NanosoldierReports/blob/ab6676206b210325500b4f4619fa711f2d7429d2/pkgeval/by_hash/52c2272_vs_47c55db/logs/MLJ/1.5.0-DEV-87d2a04de3.log

**Comment by ablaom** [comment]
I think we can just loosen the bound so that it works in all versions. I think this was just a ball-park test.
