### ISSUE TITLE
More informative error for supplying model type instead of instance in range method

### ISSUE THREAD

**Issue by drcxcruz** [alan-turing-institute/MLJ.jl#521]
**Describe the bug**
"ERROR: ArgumentError: `values` does not have an appropriate type"  by calling range function

julia>     r1 = range(pipeRandomForestClassifier, :(fs.features), values=cases)
ERROR: ArgumentError: `values` does not have an appropriate type.
Stacktrace:
 [1] nominal_range(::Type{T} where T, ::Expr, ::Array{Array{Symbol,1},1}) at C:\Users\BCP\.julia\packages\MLJBase\OZmIu\src\hyperparam\one_dimensional_ranges.jl:153
 [2] range(::Type{pipeRandomForestClassifier}, ::Expr; values::Array{Array{Symbol,1},1}, lower::Nothing, upper::Nothing, origin::Nothing, unit::Nothing, scale::Nothing) at C:\Users\BCP\.julia\packages\MLJBase\OZmIu\src\hyperparam\one_dimensional_ranges.jl:94
 [3] top-level scope at REPL[143]:1

**To Reproduce**

```julia 
@load RandomForestClassifier  pkg = DecisionTree
@load RandomForestRegressor   pkg = DecisionTree

@pipeline pipeRandomForestClassifier(
                tree = RandomForestClassifier(),
                hot = OneHotEncoder()) prediction_type = :probabilistic
    
cases = [[Symbol(names(Xy)[j]) for j in 1:i] for i in 1:ncol(Xy)] 
r1 = range(pipeRandomForestClassifier, :(fs.features), values=cases)

```

**Expected behavior**
It appears that values is required and there is no default for it.  So, MLJ user must provide the values.  I think a default set of values should be in the model already.  In this matter, we do not have to explicitly define it.  

If we must define the values and if there was an error with it, the error message should be more clear indicating more details as to what is incorrect. 

Thank you!

**Additional context**

julia> schema(Xy)
┌─────────┬─────────┬────────────┐
│ _.names │ _.types │ _.scitypes │
├─────────┼─────────┼────────────┤
│ X       │ Float64 │ Continuous │
│ Y       │ Float64 │ Continuous │
└─────────┴─────────┴────────────┘
_.nrows = 1000

julia> cases
2-element Array{Array{Symbol,1},1}:
 [:X]
 [:X, :Y]

**Versions**
Julia 1.4.1

(@v1.4) pkg> status
Status `C:\Users\BCP\.julia\environments\v1.4\Project.toml`
  [336ed68f] CSV v0.6.1
  [324d7699] CategoricalArrays v0.7.7
  [861a8166] Combinatorics v1.0.1
  [a93c6f00] DataFrames v0.20.2
  [7806a523] DecisionTree v0.10.1
  [31c24e10] Distributions v0.23.2
  [38e38edf] GLM v1.3.9
  [09f84164] HypothesisTests v0.10.0
  [7073ff75] IJulia v1.21.2
  [add582a8] MLJ v0.11.2
  [a7f614a8] MLJBase v0.13.3
  [e80e1ace] MLJModelInterface v0.2.3
  [d491faf4] MLJModels v0.9.9
  [e1d29d7a] Missings v0.4.3
  [54e16d92] PrettyPrinting v0.2.0
  [612083be] Queryverse v0.5.0
  [2913bbd2] StatsBase v0.33.0
  [009559a3] XGBoost v0.4.3

</details>

**Comment by ablaom** [comment]
Thanks for reporting! I have been caught by this myself. 

The error is that you haves supplied as the first argument of `range` a *type* instead of an *instance*. You should do:

```
range(pipeRandomForestClassifier(), :(fs.features), values=cases)
```

There is a conscious reason for this design decision. If the argument expected was a type, the user might expect the type comes from the field type as annotated in the struct definition. But sometimes this is something like `Union{nothing, Float64}` and its really the instance you want to look at. 

We could overload to instantiate with the default values, but that would mean more "hidden knowledge". I would prefer to report a more informative error and I have re-titled this issue accordingly. 

BTW, instead of supplying a model as first argument, you can just declare the type yourself, as in:

```
range(Vector{Symbol}, :(fs.features), values=cases)
```

**Comment by ablaom** [comment]
Note to fixer (probably myself 😄 ):  Take care, the first argument is allowed to be a type, in the special case that the user is declaring the type of `values` (as in example immediately above) instead of a model from where to infer the type. In the case of a composite model, the type of the hyper parameter *could* be a model type. And this is another reason for the design choice described above.

**Comment by drcxcruz** [comment]
hi, I am still having trouble :)  i have tried the following two ways.

julia> range(pipeRandomForestClassifier(), :(fs.features), values=cases)
ERROR: type pipeRandomForestClassifier has no field fs

julia> range(pipeRandomForestClassifier(), :(tree.features), values=cases)
ERROR: type RandomForestClassifier has no field features

julia> pipeRandomForestClassifier()
pipeRandomForestClassifier(
    tree = RandomForestClassifier(
            max_depth = -1,
            min_samples_leaf = 1,
            min_samples_split = 2,
            min_purity_increase = 0.0,
            n_subfeatures = 0,
            n_trees = 10,
            sampling_fraction = 0.7,
            pdf_smoothing = 0.0),
    hot = OneHotEncoder(
            features = Symbol[],
            drop_last = false,
            ordered_factor = true,
            ignore = false)) @ 6…91

####################################################################
julia> r1 = range(pipeRandomForestClassifier(), :(tree.max_depth), lower = 3, upper = 10)
MLJBase.NumericRange(Int64, :(tree.max_depth), ... )

julia> r2 = range(Vector{Symbol}, :(fs.features), values=cases)
MLJBase.NominalRange(Array{Symbol,1}, :(fs.features), ... )

julia>   tmRandomForestClassifier = TunedModel(
               model = pipeRandomForestClassifier,
               tuning = Grid(resolution = 7),
               resampling = CV(rng = 11),
               ranges = [r1,r2],
               measure = cross_entropy, # don't use rms for probabilistic responses
           )
ERROR: Only `Deterministic` and `Probabilistic` model types supported.

####################################################################

**Comment by ablaom** [comment]
There seems quite a few sources of confusion here. I think the easiest thing for me is just guess what it is you're trying to do and show you an implementation that does that. I think if you study that carefully, this should clear up many things.

The following works for me:

```julia 
using MLJ

ncolumns = 3
X = MLJ.table(rand("abc", (10, ncolumns))|> categorical);
schema(X)
y = rand("MF", 10) |> categorical;

@load RandomForestClassifier  pkg = DecisionTree
@load RandomForestRegressor   pkg = DecisionTree

# Note the order here - the tree comes *after* the encoder:
my_pipe = @pipeline MyPipe(
    selector = FeatureSelector(),
    hot = OneHotEncoder(),
    tree = RandomForestClassifier()) prediction_type = :probabilistic

_names = schema(X).names |> collect # make this a vector not tuple!
_ncols = length(_names)
cases = [Symbol.(_names[1:i]) for i in 1:_ncols]

r1 = range(my_pipe, :(selector.features), values=cases)

# check:
julia> iterator(r1) # 
3-element Array{Array{Symbol,1},1}:
 [:x1]          
 [:x1, :x2]     
 [:x1, :x2, :x3]

# wrap in a tuning strategy:
tuned_pipe = TunedModel(model=my_pipe,
                        range=r1,
                        measures=[cross_entropy, BrierScore()],
                        resampling=CV(nfolds=9))

mach = tuned_pipe_machine = machine(tuned_pipe, X, y) |> fit!

julia> report(mach).history
3-element Array{Tuple{MyPipe,NamedTuple{(:measure, :measurement),Tuple{Array{MLJBase.Measure,1},Array{Float64,1}}}},1}:
 (MyPipe @ 1…17, (measure = [cross_entropy, BrierScore{UnivariateFinite}], measurement = [0.6421118793060917, -0.4344444444444445]))
 (MyPipe @ 2…52, (measure = [cross_entropy, BrierScore{UnivariateFinite}], measurement = [6.63832086487329, -0.7722222222222224]))  
 (MyPipe @ 1…90, (measure = [cross_entropy, BrierScore{UnivariateFinite}], measurement = [0.885580946781597, -0.6777777777777779])) 
```

**Comment by ablaom** [comment]
We see that using just feature `:x1` is best:

```julia
julia> report(mach).best_model
MyPipe(
    selector = FeatureSelector(
            features = Symbol[:x1]),
    hot = OneHotEncoder(
            features = Symbol[],
            drop_last = false,
            ordered_factor = true,
            ignore = false),
    tree = RandomForestClassifier(
            max_depth = -1,
            min_samples_leaf = 1,
            min_samples_split = 2,
            min_purity_increase = 0.0,
            n_subfeatures = 0,
            n_trees = 10,
            sampling_fraction = 0.7,
            pdf_smoothing = 0.0)) @ 1…17

julia> ans.selector.features
1-element Array{Symbol,1}:
 :x1
```

**Comment by drcxcruz** [comment]
thanks, I got it working.  I will be doing more testing :)

  pipeRandomForestClassifier = @pipeline RandomForestClassifierPipe(
                selector = FeatureSelector(),
                hot = OneHotEncoder(),
                tree = RandomForestClassifier()) prediction_type = :probabilistic

    cases = [[Symbol(names(Xy)[j]) for j in 1:i] for i in 1:ncol(Xy)]   
    r1 = range(pipeRandomForestClassifier, :(selector.features), values=cases)

    tmRandomForestClassifier = TunedModel(
        model = pipeRandomForestClassifier,
        range=r1,
        measures=[cross_entropy, BrierScore()],
        resampling=CV(nfolds=9)
    )

 
you helped me so much.  please let me know how I can help you.  let me know if you need help testing code or creating lab tutorials.  i enjoy "teaching" via jupyter notebooks.  or let me know if you need help fixing small bugs.  i like to return your time by helping you. 

for this issue, part of my problem is that I am following the Labs document very closely.  for example, https://alan-turing-institute.github.io/MLJTutorials/isl/lab-5/index.html  does NOT include

selector = FeatureSelector() 

in their pipes.  

i have noticed there are inconsistencies in how to create the pipes and/or tuned model across different models.  the great advantage of MLJ is to remove the inconsistencies across different models to only have only one and a consistent programming interface to the models.  some times the  inconsistencies are valid for good reason as you pointed out before.  in those cases, the error messages need to be more clear :)   so that we can figured out the problem on our own.  to me, as a new MLJ user, only following the labs, it is not very clear what a pipe needs for a model not documented in the labs.  more labs/documentation might help.  let me your comments since I might be off the mark. 

again, thank you!  and let me know how I can help out.

**Comment by ablaom** [comment]
Your welcome. Contributing tutorials to MLJTutorials would be awesome!  Just raise an issue at https://github.com/alan-turing-institute/MLJTutorials .

Ideally you attach a working julia script with the narrative in the form of comments, which can include markdown.  Even better, have it conform to the Literate.jl style.

But if you a attach or point us to a notebook, that's fine too.

**Comment by ablaom** [comment]
You can also raise an issue about the inconsistencies. Helpful if you can be specific.

**Comment by drcxcruz** [comment]
Hi, 

I created a lab pull request in alan-turing-institute/MLJTutorials.  

LAB: Using MLJ with the GLM package #54
Commits on May 11, 2020
Update MLJ_GLM_Lab.ipynb …

@drcxcruz
drcxcruz committed 6 minutes ago

Please let me of any comments.  it is a simple lab good for beginners.  

Thanks

**Comment by ablaom** [comment]
The issue in the title has not actually been addressed.

**Comment by ablaom** [comment]
Closing in favour of https://github.com/alan-turing-institute/MLJBase.jl/issues/313

**Comment by michele2198** [comment]
Thanks abloam, I struggled to find a way to perform feature selection and your code gave me MUCH help after some modifications, I paste it here, hope can help: 

`using MLJ
ncolumns = 3
X = MLJ.table(rand("abc", (10, ncolumns))|> categorical);
schema(X)
y = rand("MF", 10) |> categorical;

@load RandomForestClassifier  pkg = DecisionTree
@load RandomForestRegressor   pkg = DecisionTree
# Note the order here - the tree comes *after* the encoder:

selector=FeatureSelector();hot = OneHotEncoder();
KNN = @load RandomForestClassifier pkg=DecisionTree;
#@pipeline MyPipe(selector,hot,tree)
MyPipe=selector|>hot|>KNN
_names = schema(X).names |> collect # make this a vector not tuple!
_ncols = length(_names)
cases = [Symbol.(_names[1:i]) for i in 1:_ncols]

r1 = range(MyPipe, :(feature_selector.features), values=cases)

# check:
#iterator(r1)# 

# wrap in a tuning strategy:
tuned_pipe = TunedModel(; model=MyPipe,
                        range=r1,
                        measures=[cross_entropy, BrierScore()],
                        resampling=CV(nfolds=5))

mach = tuned_pipe_machine = machine(tuned_pipe, X, y) |> MLJ.fit!

report(mach).history

report(mach).best_model`

**Comment by ablaom** [comment]
Nice example! 

We are currently working on the API to better support feature selection (eg, recursive feature elimination): https://github.com/alan-turing-institute/MLJ.jl/issues/747.
