### ISSUE TITLE
MLJ needs to update it's compat entry for `RecipesBase` for Plots to work correctly on latest version

### ISSUE THREAD

**Issue by HarrisonWilde** [alan-turing-institute/MLJ.jl#522]
**Describe the bug**

MLJ needs to update it's compat entry for `RecipesBase`

**To Reproduce**

See https://github.com/JuliaPlots/Plots.jl/issues/2683

**Expected behavior**

N/A

**Additional context**

N/A

**Versions**

0.11.2

**Comment by ablaom** [comment]
Closing in favour of https://github.com/alan-turing-institute/MLJTuning.jl/issues/45

**Comment by ablaom** [comment]
@HarrisonWilde Thanks for reporting this!
