### ISSUE TITLE
Readme inconsistency

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJ.jl#524]
In readme under available models, there are 3 categories for maturity:
experimental/medium/high

EvoTrees.jl & NaiveBayes.jl are listed as Maturity = "low".
Should these be listed as "experimental" instead?

btw, I've tested  EvoTrees & would call it "medium"...

**Comment by ablaom** [comment]
> In readme under available models, there are 3 categories for maturity:
> experimental/medium/high
> 
> EvoTrees.jl & NaiveBayes.jl are listed as Maturity = "low".
> Should these be listed as "experimental" instead?

Yes. Good catch
> 
> btw, I've tested EvoTrees & would call it "medium"...

Agreed.

PR welcome.
