### ISSUE TITLE
ENH: Use `readme` as landing page for docs page?

### ISSUE THREAD

**Issue by nickeubank** [alan-turing-institute/MLJ.jl#530]
MLJ has some great docs (love the tutorials!), but the landing page is the "getting started", which assumes readers already know about the purpose and organization of MLJ. 

By contrast, the readme here does a terrific job of positioning the library. But if someone starts with the docs, they won't ever know it exists!

So maybe the repo readme could become the landing page of the [MLJ site](https://alan-turing-institute.github.io/MLJ.jl/dev/)?

**Comment by ablaom** [comment]
@nickeubank Thanks! This kind feedback is very helpful. 

To clarify: Are you suggesting that [this](https://alan-turing-institute.github.io/MLJ.jl/dev/) getting started page should have a link to the MLJ readme for the reader to get more about the purpose in organisation and MLJ? Sound like a good idea. Is that the whole of your suggestion?

**Comment by ablaom** [comment]
How's this: https://github.com/alan-turing-institute/MLJ.jl/blob/dev/docs/src/index.md ?

**Comment by nickeubank** [comment]
So I would actually move the WHOLE readme in as your `index.md` file. 

For a sense of context, I'm an educator / social scientist, so I work a lot with non-developers, and my experience is that that population doesn't go to github first, they go to the docs. And so I think it's important that the docs start with a nice intro/landing page for users. You have a great one in your readme, but I worry that it's not in the documentation site, it's over here in github, and I think it'd be better IN the docs. 

For example, the [lightgraphs docs](https://juliagraphs.org/LightGraphs.jl/stable/) start with a "what's light graphs?":  . [JuliaDB](https://juliadata.github.io/JuliaDB.jl/latest/) does the same.

**Comment by ablaom** [comment]
I understand, thank you. That makes sense.

@tlienart @sjvollmer I would have your reaction to this proposal before moving forward.

**Comment by tlienart** [comment]
This sounds like a good idea 👍🏼 and thanks for the feedback very useful indeed!
