### ISSUE TITLE
Re-export mape and MAPE from MLJBase

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJ.jl#532]
`mape(ŷ, y[test])`
throws: `UndefVarError: mape not defined`
`MLJ.mape(ŷ, y[test])` works

However other measures work w/o `MLJ.measure()`
`rms(ŷ, y[test])`

**Comment by ablaom** [comment]
Yeah, it's not re-exported. Thanks for reporting!

**Comment by azev77** [comment]
It would be awesome if there was a way to automatically do these things (if possible) once a new measure is added to MLJBase...

**Comment by ablaom** [comment]
Yeah, well there's https://github.com/simonster/Reexport.jl but I think this is an all-or-nothing thing, which is not ideal - or requires a bit of rethinking. We have to see if re-exporting *every* MLJBase function makes sense.

**Comment by ablaom** [comment]
The plan is for measures to move to it's own repo anyhow. In that case we could re-export all it's methods.
