### ISSUE TITLE
Hyperparameter tuning of KNN classifier

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#543]
**Describe the bug**
Hyperparameter tuning is triggering "unsupported range" error.

**To Reproduce**
```Julia
using MLJ
using CategoricalArrays
using LossFunctions

function tuning(m)
  l  = MisclassLoss()
  rs = (range(m, :n_neighbors, values=[2,5,10]),)
  tm = TunedModel(model=m, ranges=rs, measure=l)

  X = table(rand(100,3))
  y = categorical(rand(1:2, 100))

  # perform tuning
  mac = machine(tm, X, y)
  fit!(mac)

  fitted_params(mac).best_model
end

@load KNeighborsClassifier pkg="ScikitLearn"

tuning(KNeighborsClassifier()) # ArgumentError: Unsupported range.
```

**Expected behavior**
I expected the code to work, but I am not sure if this is the correct usage of the interface.

**Versions**
MLJ 0.11.2

**Comment by OkonSamuel** [comment]
@juliohm replace `rs = (range(m, :n_neighbors, values=[2,5,10]),)` with `rs = range(m, :n_neighbors, values=[2,5,10])`

**Comment by juliohm** [comment]
Thank you @OkonSamuel will give it a try. I had chosen the tuple based on the MLJTutorials example here: https://alan-turing-institute.github.io/MLJTutorials/getting-started/model-tuning Perhaps I should have chosen an array instead of a tuple exactly like in the tutorial? I am supposing we still need to pass an array when we want to tune various parameters of the same model, right?

**Comment by OkonSamuel** [comment]
yeah an array would also work

**Comment by juliohm** [comment]
Thank you, closing this for now.
