### ISSUE TITLE
Add configuration options for RandomForestClassifier.n_subfeatures that depend on the data size

### ISSUE THREAD

**Issue by CameronBieganek** [alan-turing-institute/MLJ.jl#557]
I was running a random forest classifier and wondering why it was taking so long... Then I noticed that the default value for `n_subfeatures` is zero, which means use all features. It would be nice if the default value was `:sqrt`, like in [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html) (though oddly the default in scikit-learn for `RandomForestRegressor` is to use all features...).

And while we're at it, it would be nice to interpret float/rational values of `n_subfeatures` as fractions of the number of features.

Having these built-in options is very helpful when you're writing helper functions to create various model and tuned-model objects, which happens in a data-independent way. In other words, my helper functions for SVMs and random forests were sharing some of the same code. Having to introduce an extra random-forest-specific helper function with an `X` argument so that I can do `n_subfeatures = floor(Int, sqrt(ncol(X)))` reduces my code reuse. 😄 And in general it seems like the hyperparameter objects should be defined in a data-independent way if possible.

**Comment by ablaom** [comment]
> I was running a random forest classifier and wondering why it was taking so long... Then I noticed that the default value for n_subfeatures is zero, which means use all features. It would be nice if the default value was :sqrt, like in scikit-learn (though oddly the default in scikit-learn for RandomForestRegressor is to use all features...).

Our policy is to use the same defaults as the package we are wrapping (and to use the same hyperparameter names). The simple reason is that we are not in the business of duplicating documentation for 3rd party model providers (such as scikitlearn) and *modifying* the behaviour of algorithms would require us to document our changes (and justify those changes, to some extent) which is a slippery slope for us to climb given current resources. 

Are you saying that the MLJ default is different from the default documented at the package? In this case it needs to be fixed. Please open a new specific issue. If this is not the case, then you would need to lobby for a change with the provider first. 

> And while we're at it, it would be nice to interpret float/rational values of n_subfeatures as fractions of the number of features.

I completely agree, but if the behaviour you want is not provided (and documented) by the algorithm provider, then you should try to get them to change that and let MLJ know if you are successful.

**Comment by CameronBieganek** [comment]
> Our policy is to use the same defaults as the package we are wrapping (and to use the same hyperparameter names).

Thanks, that makes sense!
