### ISSUE TITLE
Change DecisionTree.jl `n_subfeatures` default to -1 for random forest classifier and regressor

### ISSUE THREAD

**Issue by CameronBieganek** [alan-turing-institute/MLJ.jl#558]
Are you saying that the MLJ default is different from the default documented at the package? In this case it needs to be fixed. Please open a new specific issue.

_Originally posted by @ablaom in https://github.com/alan-turing-institute/MLJ.jl/issues/557#issuecomment-634393704_

**Comment by CameronBieganek** [comment]
I hadn't actually used DecisionTree.jl directly before, but it turns out that the default value of `n_subfeatures` for the random forest regressor and classifier models is -1, which means `sqrt(# features`. [Link to docs.](https://pkg.julialang.org/docs/DecisionTree/pEDeB/0.8.1/autodocs/#DecisionTree.RandomForestRegressor)

(For the decision tree classifiers and regressors the default is 0.)

**Comment by ablaom** [comment]
Good  catch, thanks!

**Comment by ablaom** [comment]
Closing in favour of https://github.com/alan-turing-institute/MLJModels.jl/issues/259

**Comment by ablaom** [comment]
Also, the lower level of this hyper-parameter is not 0, as presently, but -1.
