### ISSUE TITLE
Tutorial link in Getting Started doesn't link to right spot

### ISSUE THREAD

**Issue by kbjarnason** [alan-turing-institute/MLJ.jl#560]
**Describe the bug**

As per title
https://github.com/alan-turing-institute/MLJ.jl/blob/master/docs/src/getting_started.md

**Comment by kbjarnason** [comment]
In here
https://github.com/alan-turing-institute/MLJ.jl/blob/master/docs/src/getting_started.md

**Comment by ablaom** [comment]
Good catch, thanks
