### ISSUE TITLE
Document how to load models without the @load macro

### ISSUE THREAD

**Issue by CameronBieganek** [alan-turing-institute/MLJ.jl#562]
The `@load` macro is convenient for casual use, but when I'm working on a project or a package, I would prefer to use explicit `using` or `import` statements. Also, when I use the `@load` macro in VS Code, the linter gets pretty confused:

<img src="https://user-images.githubusercontent.com/8310743/83437042-a8f9f780-a404-11ea-9f19-d504ccbf144f.png" height="250">

**Comment by ablaom** [comment]
There is a doc-string:

```julia
help?> load
search: load load_path load_iris load_ames LoadError load_crabs load_boston

  load(name::String; pkg=nothing, modl=Main, verbosity=1, allow_ambiguous=false)

  Load the model implementation code for the model type with specified name
  into the module modl, specifying pkg if necesssary, to resolve duplicate
  names.

  load(proxy; pkg=nothing, modl=Main, verbosity=1)

  In the case that proxy is a return value of traits (ie, has the form (name =
  ..., package_name = ..., etc)) this is equivalent to load(name=proxy.name,
  pkg=proxy.package_name).

  If allow_ambiguous=true then multiple models with the same name can be
  imported, otherwise a warning is raised and the previously available model
  is kept.

  See also @load

  Examples
  ––––––––––

  load("ConstantClassifier")
  load(localmodels()[1])

  See also @load
```

We could add this to the manual, somewhere. Probably with a new section?

**Comment by CameronBieganek** [comment]
Oh, I didn't see the `load` function. However, this still confuses the linter:

<img src="https://user-images.githubusercontent.com/8310743/83786565-79432d80-a658-11ea-847f-63ff89c2d76e.png" width="500">

For this particular case, is it sufficient to use the following code in my project?

```julia
import DecisionTree
import MLJModels
```

I don't think the linter is smart enough to trace `eval`-ed expressions inside the `load` function. It needs to see explicit `using` or `import` statements.

**Comment by OkonSamuel** [comment]
@CameronBieganek. yes you could just do `import DecisionTree; RandomForestClassifier = MLJModels.DecisionTree_.RandomForestClassifier.` (This is not so clean that's why we recommend the load acro). There is no need to import **MLJModels** as it's already loaded automatically.

**Comment by ablaom** [comment]
This would be fragile as the load path to the model will change when we disintegrate MLJModels. If you really want, you can get the load path like this:

```julia
julia> info("RandomForestClassifier", pkg="DecisionTree").load_path
"MLJModels.DecisionTree_.RandomForestClassifier"
```
and that will be safe.

Frankly, I don't think the linter thing is an MLJ issue, not that you are suggesting it is 😄

**Comment by CameronBieganek** [comment]
Yeah, unfortunately the linter can't handle metaprogramming. Though I think they've special-cased some of the common macros like the JuMP macros.

I still kind of think that it would be nice if I could stick to explicit `using` and `import` statements in the top-level module of my package, but I suppose using the `@load` macro is fine. Anyhow, I guess as the MLJModels code is integrated into the native packages it will cease to be an issue. 🙂
