### ISSUE TITLE
Request for monte-carlo cross validation

### ISSUE THREAD

**Issue by yalwan-iqvia** [alan-turing-institute/MLJ.jl#564]
**Is your feature request related to a problem? Please describe.**
I would like to see more resampling strategies. In particular, I am interested in monte-carlo cross validation

**Describe the solution you'd like**
I think an implementation of monte-carlo cross validation provided by MLJ would be the right approach rather than rolling my own

**Describe alternatives you've considered**
Rolling my own

**Comment by ablaom** [comment]
PR welcome. The API is simple - just one struct and one method - and is described here: https://alan-turing-institute.github.io/MLJ.jl/dev/evaluating_model_performance/#Custom-resampling-strategies-1
I imagine you can pretty much follow the existing example, say ordinary CV, which is here:
https://github.com/alan-turing-institute/MLJBase.jl/blob/5aec436a948509639dd370ebf10194e424445e48/src/resampling.jl#L122

**Comment by ablaom** [comment]
In fact,  I believe Monte-Carlo cross-validation is already possible, using the `repeats` option and choosing the random version of  `Holdout`:

```julia
julia> X, y = make_regression(20, 2);
julia> model = KNNRegressor()
julia> evaluate(model, X, y, resampling=Holdout(rng=123), repeats=3)
Evaluating over 3 folds: 100%[=========================] Time: 0:00:00
┌───────────┬───────────────┬─────────────────────┐
│ _.measure │ _.measurement │ _.per_fold          │
├───────────┼───────────────┼─────────────────────┤
│ rms       │ 0.275         │ [0.257, 0.347, 0.2] │
└───────────┴───────────────┴─────────────────────┘
_.per_observation = [missing]

```

 In addition to Monte-Carlo "holdout" you could do Monte-Carlo "cv" or whatever .

**Comment by ablaom** [comment]
For an explanation of `repeat` do `?evaluate!`

**Comment by ablaom** [comment]
Note to self: Add "Monte-Carlo" do evaluation doc-string in connection to `repeat`

**Comment by yalwan-iqvia** [comment]
This is very good, thanks! I think this issue can in fact be closed as a consequence.
