### ISSUE TITLE
Loading SKLearn packages causes Julia to crash

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJ.jl#565]
I just did a clean install of Julia & MLJ & packages all latest, on Mac. 
The following causes Julia to crash. Only message `Julia has exited.`.
```julia
load("ARDRegressor", pkg="ScikitLearn")
load("ExtraTreesRegressor", pkg="ScikitLearn")
```

**Comment by ablaom** [comment]
`versioninfo()` would be helpful. Do you still have the problem if you restrict your env to MLJ and ScikitLearn?

**Comment by azev77** [comment]
```julia
julia> versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

**Comment by azev77** [comment]
Still have the problem restricting my `env` to MLJ & Sklearn. 
```julia
Status `~/Dropbox/COMPUTATION/_QE_Moll/ML/AZ_proj/Project.toml`
  [add582a8] MLJ v0.11.4 #master (https://github.com/alan-turing-institute/MLJ.jl/)
  [3646fa90] ScikitLearn v0.6.1 #master (https://github.com/cstjean/ScikitLearn.jl)
INTEL MKL ERROR: dlopen(/Users/AZevelev/.julia/conda/3/lib/libmkl_intel_thread.dylib, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/AZevelev/.julia/conda/3/lib/libmkl_intel_thread.dylib
  Reason: image not found.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.
```

**Comment by ablaom** [comment]
Yeah this is very frustrating. However, I believe this is a "known" issue unrelated to MLJ. 

The latest workaround, as I understand it, is to `build` PyCall with `PYTHON="path/to/your/local/anaconda/python"` set, after switching out MKL for OpenBLAS, as described here: https://docs.anaconda.com/mkl-optimizations/

**Comment by ablaom** [comment]
See also the PyCall readme for more on choosing your python installation.

**Comment by azev77** [comment]
I’ll try that. 
Btw, the reason I raised this is before my code would break when I ran certain Sklearn models. 
Now it breaks when I load sklearn models.

**Comment by ablaom** [comment]
No, no. It is good that you raise this issues. Many thanks!

**Comment by OkonSamuel** [comment]
> ```julia
> [3646fa90] ScikitLearn v0.6.1 #master
> ```

@azev77 please update `ScikitLearn` to the current master

**Comment by azev77** [comment]
@OkonSamuel just tried, still no luck

**Comment by OkonSamuel** [comment]
`ScikitLearn v0.6.2` has just been released try that instead.

**Comment by azev77** [comment]
Thanks @OkonSamuel but still no luck. 
```julia
Status `~/Dropbox/COMPUTATION/_QE_Moll/ML/AZ_proj/Project.toml`
  [add582a8] MLJ v0.11.4
  [3646fa90] ScikitLearn v0.6.2
[ Info: Precompiling MLJ [add582a8-e3ab-11e8-2d5e-e98b27df1bc7]
[ Info: Model metadata loaded from registry. 
[ Info: Precompiling ScikitLearn [3646fa90-6ef7-5e7e-9f22-8aca16db6324]
INTEL MKL ERROR: dlopen(/Users/AZevelev/.julia/conda/3/lib/libmkl_intel_thread.dylib, 9): Library not loaded: @rpath/libiomp5.dylib
  Referenced from: /Users/AZevelev/.julia/conda/3/lib/libmkl_intel_thread.dylib
  Reason: image not found.
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.

Julia has exited.
Press Enter to start a new session.
```

**Comment by OkonSamuel** [comment]
Remove scikitLearn and reinstall it again.

**Comment by OkonSamuel** [comment]
Okay. I guess you are running ScikitLearn using MLJ.??
In that case run this `using ScikitLearn; ScikitLearn.Skcore.import_sklearn()`
`ScikitLearn` by default doesn't install `sklearn` until it is needed. So the above line of code should fix this?.

**Comment by azev77** [comment]
@OkonSamuel 
how do I set `ENV["PYTHON"] =Conda`?

Also, `using ScikitLearn; ScikitLearn.Skcore.import_sklearn()` causes Julia to crash

**Comment by tlienart** [comment]
Could this issue just be moved to ScikitLearn instead? it's independent from MLJ right?

**Comment by OkonSamuel** [comment]
> Could this issue just be moved to ScikitLearn instead? it's independent from MLJ right?

i guess so

**Comment by tlienart** [comment]
alright cool closing here
