### ISSUE TITLE
Standardization of multi-targets

### ISSUE THREAD

**Issue by tlienart** [alan-turing-institute/MLJ.jl#568]
This came up in the discussion at PLSRegressors.jl; they tried to build a pipeline with `target = Standardizer()` in the case of multi-output regression and it seems they had problem with it. Any thougths @ablaom ?

cc: @filipebraida who might be able to give more context

see: https://github.com/lalvim/PLSRegressor.jl/pull/10#discussion_r439749841 for context.

**Comment by filipebraida** [comment]
The @lalvim who is solving this part and he will explain the context better.

**Comment by lalvim** [comment]
The main problem is that PLS computes scores and loadings on X and Y (differently from PCA that computes only on X) that can be standardized. These scores and loadings are based on correlation. That's why I prefer standardization on Y. Moreover, If I perform standardization on X, not on Y, then, on the prediction phase, If the user put a standardized X, the output will be also standardized. Thus, I have to destandardize Y before informing the user's output.

Hence, without standardization, it does not pass on the tests. The outputs are standardized (need to destandardize), because X was. However, If the user does not perform standartization on X, then, Y output will be on the same scale of X.

**Comment by ablaom** [comment]
I think I need some help understanding what your problem is. Standardization for tables works for me. Here's an example of a multi-target regressor with target standardization:

```julia
using MLJ

N = 100

# create some multi-target data for regression:
X = (x1=rand(N), x2=rand(N), x3=rand(N));
y1 = X.x1 - 2*X.x3 + 0.05*rand(N);
y2 = -X.x1 + X.x3 + 0.05*rand(N);
Ymat = hcat(y1, y2);
Y = MLJ.table(Ymat);

# find some models that do this kind of regression:
julia> models(matching(X, Y))
4-element Array{NamedTuple{(:name, :package_name, :is_supervised, :docstring, :hyperparameter_ranges, :hyperparameter_types, :hyperparameters, :implemented_methods, :is_pure_julia, :is_wrapper, :load_path, :package_license, :package_url, :package_uuid, :prediction_type, :supports_online, :supports_weights, :input_scitype, :target_scitype, :output_scitype),T} where T<:Tuple,1}:
 (name = MultiTaskElasticNetCVRegressor, package_name = ScikitLearn, ... )
 (name = MultiTaskElasticNetRegressor, package_name = ScikitLearn, ... )  
 (name = MultiTaskLassoCVRegressor, package_name = ScikitLearn, ... )     
 (name = MultiTaskLassoRegressor, package_name = ScikitLearn, ... )       


# pick one:
model = @load MultiTaskLassoRegressor
rows = 1:20

mypipe = @pipeline MyPipe(rgs = model, target=Standardizer())

mach = fit!(machine(mypipe, X, Y))
```

This works fine for me. 

Does this help?

**Comment by lalvim** [comment]
I will see my interface. Probably I did something wrong.

**Comment by filipebraida** [comment]
> This works fine for me.

We ( @lalvim ) run your code ( @ablaom ) and add the predictor. It gave the same error as ours. The problem occurs in de-standardization of the target within the predict method. This problem only occurs when the target is a matrix.

```
julia> pred = MLJ.predict(mach, rows = 1:20);
ERROR: MethodError: no method matching inverse_transform(::Standardizer, ::Dict{Symbol,Tuple{Float64,Float64}}, ::Tables.MatrixTable{Array{Float64,2}})
Closest candidates are:
  inverse_transform(::UnivariateStandardizer, ::Any, ::Any) at /Users/filipebraida/.julia/packages/MLJModels/uSKTW/src/builtins/Transformers.jl:295
  inverse_transform(::MLJModels.ScikitLearn_.FeatureAgglomeration, ::Any, ::Any) at /Users/filipebraida/.julia/packages/MLJModels/uSKTW/src/ScikitLearn/ScikitLearn.jl:285
  inverse_transform(::MLJBase.AbstractMachine{M}, ::Any...) where M at /Users/filipebraida/.julia/packages/MLJBase/LxAsa/src/operations.jl:28
  ...
```

Thanks!

**Comment by ablaom** [comment]
You are right! No `inverse_transform` is implemented in the multivariate case. Would indeed be good to have this. 

Closing in favour of https://github.com/alan-turing-institute/MLJModels.jl/issues/269
