### ISSUE TITLE
@load_MNIST

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJ.jl#584]
In [MLJ.jl](https://github.com/alan-turing-institute/MLJ.jl/blob/master/src/MLJ.jl) we have: @load_boston, @load_ames, @load_iris, @load_reduced_ames, @load_crabs

It would be awesome to have (in [MLJ.jl](https://github.com/alan-turing-institute/MLJ.jl/blob/master/src/MLJ.jl)): @load_MNIST

Currently the closest thing is in [MLJFlux.jl](https://github.com/alan-turing-institute/MLJFlux.jl)

**Comment by ablaom** [comment]
Yes, it would be nice, but it is kinda big.

**Comment by ablaom** [comment]
Of course it could be pulled on demand from wherever. PR welcome.

**Comment by azev77** [comment]
The reason I opened this issue is that most ML tutorials I've seen have: 
1 regression w/ Boston or Ames housing data
2 classification w/ Titanic data (binary survive or die) & Iris data (multi-class) 
3 image classification w/ MNIST & CIFAR-10

Currently the only MNIST example in MLJ is in the MLJFlux readme.

Can we just import it from Flux like in the MLJFlux readme: 
```julia
N = 1000
X, y = Flux.Data.MNIST.images()[1:N], Flux.Data.MNIST.labels()[1:N];
```
so something like
```julia
@load_mnist = Flux.Data.MNIST.images(), Flux.Data.MNIST.labels()
```
Then we can do an image classifier tutorial comparing Flux, XGBoost, LightGBM...

**Comment by azev77** [comment]
> Of course it could be pulled on demand from wherever. PR welcome.

@ablaom Be careful what you wish for ;): https://github.com/alan-turing-institute/MLJ.jl/pull/588

**Comment by ablaom** [comment]
> Can we just import it from Flux like in the MLJFlux readme: 
```julia
N = 1000
X, y = Flux.Data.MNIST.images()[1:N], Flux.Data.MNIST.labels()[1:N];
```

Yes, that's the way to do it. You just need `import Flux` first and you're away.

**Comment by azev77** [comment]
That was fun. As expected, you weren't too thrilled w/ my hack. 
I guess it's OK for ML to not have `@load_flux` & we can use  `Flux.Data.MNIST.` the same way we use `RDatasets`. 
But I really hope we have a general MLJ image classification tutorial w/ MNIST comparing Flux/LGB/XGB etc. 
-Right now the only place in MLJ w/ MNIST is the MLJFlux readme. 

Btw, there have been many PRs I've been reluctant to submit for features that I want bc I expect you'd be similarly unimpressed w/ my "hacks". 
There are prob many package dependency issues & other issues a maintainer needs to worry about that I'm unaware of...
