### ISSUE TITLE
fitted_params(LogisticModel):  linear_binary_classifier = Any[]

### ISSUE THREAD

**Issue by drcxcruz** [alan-turing-institute/MLJ.jl#597]
**Describe the bug**

The new fitted_params(LogisticModel)   is returning empty for linear_binary_classifier field.  How do we get the coefficients from the fitted_params_given_machine field?  

> (standardizer = (mean_and_std_given_feature = Dict(:score => (50.88902933684601, 8.701909614072397)),), 
> linear_binary_classifier = Any[], 
> machines = Machine[Machine{Standardizer} @338, Machine{LinearBinaryClassifier{LogitLink}} @311], 
> fitted_params_given_machine = OrderedCollections.LittleDict{Any,Any,Array{Any,1},Array{Any,1}}(Machine{Standardizer} @338 
> 	=> (mean_and_std_given_feature = Dict(:score => (50.88902933684601, 8.701909614072397)),),Machine{LinearBinaryClassifier{LogitLink}} @311 
> 	=> (coef = [1.046678960710956], intercept = -1.302398012326754)))

	
	

The new fitted_params works fine for linear regression. 

> (standardizer = (mean_and_std_given_feature = Dict(:V1 => (0.0024456300706479973, 1.1309193246154066)),), 
> linear_regressor = (coef = [1.1047104309244824], intercept = 0.01589388399578976), machines = Machine[Machine{Standardizer} @566, Machine{LinearRegressor} @593], 
> fitted_params_given_machine = OrderedCollections.LittleDict{Any,Any,Array{Any,1},Array{Any,1}}(Machine{Standardizer} @566 
> 	=> (mean_and_std_given_feature = Dict(:V1 => (0.0024456300706479973, 1.1309193246154066)),),Machine{LinearRegressor} @593 
> 	=> (coef = [1.1047104309244824], intercept = 0.01589388399578976)))

**To Reproduce**
@everywhere MLJ.@load LinearRegressor          pkg = GLM
@everywhere MLJ.@load LinearBinaryClassifier   pkg = GLM
**Expected behavior**

**Additional context**

**Versions**
(@v1.4) pkg> status
Status `C:\Users\BCP\.julia\environments\v1.4\Project.toml`
  [336ed68f] CSV v0.6.2
  [324d7699] CategoricalArrays v0.8.1
  [aaaa29a8] Clustering v0.14.1
  [861a8166] Combinatorics v1.0.2
  [a93c6f00] DataFrames v0.21.4
  [7806a523] DecisionTree v0.10.5
  [31c24e10] Distributions v0.23.4
  [f6006082] EvoTrees v0.4.8
  [da1fdf0e] FreqTables v0.4.0
  [38e38edf] GLM v1.3.9
  [0e44f5e4] Hwloc v1.0.3
  [09f84164] HypothesisTests v0.10.0
  [7073ff75] IJulia v1.21.2
  [b1bec4e5] LIBSVM v0.4.0
  [add582a8] MLJ v0.12.0
  [a7f614a8] MLJBase v0.14.2
  [e80e1ace] MLJModelInterface v0.3.0
  [d491faf4] MLJModels v0.11.0
  [e1d29d7a] Missings v0.4.3
  [6f286f6a] MultivariateStats v0.7.0
  [5fb14364] OhMyREPL v0.5.5
  [42b8e9d4] ParallelKMeans v0.1.8
  [14b8a8f1] PkgTemplates v0.7.6
  [54e16d92] PrettyPrinting v0.2.0
  [1a8c2f83] Query v0.12.2
  [612083be] Queryverse v0.6.1
  [ce6b1742] RDatasets v0.6.9
  [8523bd24] ShapML v0.3.0 #master (https://github.com/nredell/ShapML.jl)
  [2913bbd2] StatsBase v0.33.0
  [bd369af6] Tables v1.0.4
  [112f6efa] VegaLite v2.2.0
  [009559a3] XGBoost v1.1.1

(@v1.4) pkg>                                                  

</details>

**Comment by ablaom** [comment]
This is a known issue. It should be resolved by this GLM.jl PR: 

https://github.com/JuliaStats/GLM.jl/pull/378

**Comment by drcxcruz** [comment]
thanks for creating the GLM.jl PR.  I hope the GLM team releases it to production soon.  for now, i am getting the coefficients from fitted_params_given_machine
