### ISSUE TITLE
Problem fetching spawned @pipeline processes

### ISSUE THREAD

**Issue by drcxcruz** [alan-turing-institute/MLJ.jl#598]
**Describe the bug**

how do we do ranges in the new MLJ version?  thanks

>         @everywhere pipeRandomForestRegressor = @pipeline FeatureSelector RandomForestRegressor
>         cases = [[Symbol(names(X)[j]) for j in 1:i] for i in 1:ncol(X)] 
> 
>         r1 = range(pipeRandomForestRegressor, :(pipeRandomForestRegressor.features), values=cases)
> 
>        ERROR: type Pipeline2446 has no field pipeRandomForestRegressor
> 

I think many labs such as https://alan-turing-institute.github.io/DataScienceTutorials.jl/isl/lab-5/index.html are incorrect now.
**To Reproduce**

@everywhere rfc = MLJ.@load RandomForestClassifier  pkg = DecisionTree
@everywhere rfr = MLJ.@load RandomForestRegressor   pkg = DecisionTree

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by ablaom** [comment]
You will something like

```julIia
r1 = range(pipeRandomForestRegressor, :(feature_selector.features), values=cases)
```

**Comment by drcxcruz** [comment]
hi,

that range works, thanks.  However, the spawn is not finding the pipe.  does spawn work with the new pipes syntax? 



    Xy = copy(X)
    yPermutedIndex = sample(1:length(y), length(y), replace = false, ordered = false)
    Xy.Y = y[yPermutedIndex,1]
    E = ExpInd[:,1] |> categorical

    @everywhere pipeRandomForestClassifier = @pipeline FeatureSelector RandomForestClassifier  #) prediction_type = :probabilistic
    cases = [[Symbol(names(Xy)[j]) for j in 1:i] for i in 1:ncol(Xy)]   
    r1 = range(pipeRandomForestClassifier, :(feature_selector.features), values=cases)
    tmRandomForestClassifier = TunedModel(
        model = pipeRandomForestClassifier,
        range = r1,
        measures = [cross_entropy, BrierScore()],
        resampling = CV(nfolds = 5)
    )  
    # train model with X and permuted Y
    BrefOnlyX = @spawnat :any fitAndPredict(tmRandomForestClassifier, Xy, E)

    # train model with X and Y without permuting
    Xy = copy(X)
    Xy.Y = y[:,1]
    BrefXY = @spawnat :any fitAndPredict(tmRandomForestClassifier, Xy, E)

    fetchXY = fetch(BrefXY)

julia>     fetchXY = fetch(BrefXY)
ERROR: On worker 5:
UndefVarError: Pipeline1362 not defined
deserialize_datatype at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:1211
handle_deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:788
deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:735
deserialize_datatype at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:1235
handle_deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:788
deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:735
handle_deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:803
deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:735 [inlined]
deserialize_global_from_main at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\clusterserialize.jl:160
#3 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\clusterserialize.jl:72 [inlined]
foreach at .\abstractarray.jl:1919
deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\clusterserialize.jl:72
handle_deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:878
deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:735
handle_deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:792
deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:735
handle_deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:795
deserialize at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Serialization\src\Serialization.jl:735 [inlined]
deserialize_msg at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\messages.jl:99
#invokelatest#1 at .\essentials.jl:712 [inlined]
invokelatest at .\essentials.jl:711 [inlined]
message_handler_loop at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\process_messages.jl:185
process_tcp_streams at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\process_messages.jl:142
#97 at .\task.jl:358

**Comment by ablaom** [comment]
Thanks for reporting. 

Perhaps this has something to do with the fact that each process is using new auto-generated name for the pipe. That the pipe type name is automatically generated is new. 

You could test this hypothesis by explictly adding `name=MyPipe` to override this behaviour, as in:

```julia
@everywhere pipeRandomForestClassifier = @pipeline FeatureSelector RandomForestClassifier name=MyPipe
```

**Comment by drcxcruz** [comment]
hi,

that helps it to find the pipe but now it is generating an ugly error.

@everywhere pipeRandomForestClassifier = @pipeline FeatureSelector RandomForestClassifier name=MyPipe

ERROR: On worker 3:
BoundsError
getindex at .\number.jl:78 [inlined]
getter at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\univariate_finite\arrays.jl:137 [inlined]
_broadcast_getindex_evalf at .\broadcast.jl:631 [inlined]
_broadcast_getindex at .\broadcast.jl:604 [inlined]
getindex at .\broadcast.jl:564 [inlined]
macro expansion at .\broadcast.jl:910 [inlined]
macro expansion at .\simdloop.jl:77 [inlined]
copyto! at .\broadcast.jl:909 [inlined]
copyto! at .\broadcast.jl:864 [inlined]
copy at .\broadcast.jl:840 [inlined]
materialize at .\broadcast.jl:820 [inlined]
broadcasted at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\univariate_finite\arrays.jl:138
broadcast at .\broadcast.jl:758 [inlined]
BrierScore at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\measures\finite.jl:183
BrierScore at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\measures\finite.jl:173 [inlined]
value at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\measures\measures.jl:78 [inlined]
value at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\measures\measures.jl:64
#264 at .\none:0
iterate at .\generator.jl:47 [inlined]
collect_to! at .\array.jl:711
collect_to_with_first! at .\array.jl:689
collect at .\array.jl:670
get_measurements at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\resampling.jl:779
#248 at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\resampling.jl:644 [inlined]
_mapreduce at .\reduce.jl:400
_mapreduce_dim at .\reducedim.jl:312 [inlined]
#mapreduce#580 at .\reducedim.jl:307 [inlined]
mapreduce at .\reducedim.jl:307 [inlined]
_evaluate! at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\resampling.jl:643
evaluate! at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\resampling.jl:796
evaluate! at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\resampling.jl:859
fit at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\resampling.jl:959
#fit_only!#77 at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:416
#fit!#80 at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:461 [inlined]
event at C:\Users\BCP\.julia\packages\MLJTuning\oLVRR\src\tuned_models.jl:257
#6 at C:\Users\BCP\.julia\packages\MLJTuning\oLVRR\src\tuned_models.jl:291 [inlined]
iterate at .\generator.jl:47 [inlined]
_collect at .\array.jl:678
collect_similar at .\array.jl:607 [inlined]
map at .\abstractarray.jl:2072 [inlined]
assemble_events at C:\Users\BCP\.julia\packages\MLJTuning\oLVRR\src\tuned_models.jl:290
build at C:\Users\BCP\.julia\packages\MLJTuning\oLVRR\src\tuned_models.jl:454
fit at C:\Users\BCP\.julia\packages\MLJTuning\oLVRR\src\tuned_models.jl:491
#fit_only!#77 at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:416
fit_only! at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:384 [inlined]
#fit!#80 at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:461 [inlined]
fit! at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:459 [inlined]
fitAndPredict at C:\Users\BCP\.julia\dev\InvariantCausalPrediction\src\InvariantEnvironmentPrediction.jl:21
#211 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\macros.jl:87
#101 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\process_messages.jl:290
run_work_thunk at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\process_messages.jl:79
run_work_thunk at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\process_messages.jl:88
Stacktrace:
 [1] #remotecall_fetch#141 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\remotecall.jl:390 [inlined]
 [2] remotecall_fetch(::Function, ::Distributed.Worker, ::Distributed.RRID) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\remotecall.jl:382
 [3] #remotecall_fetch#144 at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\remotecall.jl:417 [inlined]
 [4] remotecall_fetch at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\remotecall.jl:417 [inlined]
 [5] call_on_owner at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\remotecall.jl:490 [inlined]
 [6] fetch(::Future) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Distributed\src\remotecall.jl:529
 [7] InvariantEnvironmentPrediction(::DataFrame, ::Array{Float64,1}, ::DataFrame, ::Int64, ::Int64, ::Float64, ::Bool) at C:\Users\BCP\.julia\dev\InvariantCausalPrediction\src\InvariantEnvironmentPrediction.jl:60
 [8] InvariantEnvironmentPrediction at C:\Users\BCP\.julia\dev\InvariantCausalPrediction\src\InvariantEnvironmentPrediction.jl:37 [inlined]
 [9] ForestInvariantCausalPredictionSequential!(::DataFrame, ::DataFrame, ::DataFrame; α::Float64, selection::String, verbose::Bool) at C:\Users\BCP\.julia\dev\InvariantCausalPrediction\src\InvariantCausalPrediction.jl:501
 [10] top-level scope at REPL[57]:1

**Comment by ablaom** [comment]
> do we need input parameter: prediction_type = :probabilistic ?

No, that should be successfully inferred in the new release (and the macro let's you know otherwise).

**Comment by ablaom** [comment]
To speed things up, please provide a self-continained example - including data - that reproduces your error. Ideally, make this  a "minimal working example", which means eliminate any code that is not needed to reproduce the error. Thanks

**Comment by drcxcruz** [comment]
Hi,

I took off the spawn call.  It is still not working.  Here is the minimal example that generates an error.  I seen many errors as I tried to fix it for the last 3 hours :)  My guess is that the turning model object is bad.  thank you for your time.

The data files are:
[Issue20200714.zip](https://github.com/alan-turing-institute/MLJ.jl/files/4922307/Issue20200714.zip)


using Distributed
import Hwloc
if length(workers()) == 1
    addprocs(Hwloc.num_physical_cores())  # get ready for parallelism
end
@everywhere begin 
    using Distributed, MLJ, DataFrames
    using StatsBase: sample
    using HypothesisTests:  UnequalVarianceZTest, pvalue, EqualVarianceZTest, FisherExactTest, MannWhitneyUTest
end 
@everywhere forest_model = MLJ.@load RandomForestClassifier pkg = DecisionTree



using CSV, DataFrames, Query
cd("C:\\Users\\BCP\\github\\ICP\\Test")
dfX1forest = CSV.File("treeManX1.csv") |> DataFrame
dfE1forest = CSV.File("treeManE1.csv") |> DataFrame


X = copy(dfX1forest)
coerce!(X, autotype(X, :discrete_to_continuous))
y = dfE1forest[:,1] |> categorical


@everywhere pipeRandomForestClassifier = @pipeline FeatureSelector RandomForestClassifier 
cases = [[Symbol(names(X)[j]) for j in 1:i] for i in 1:ncol(X)]   
r1 = range(pipeRandomForestClassifier, :(feature_selector.features), values=cases)
tmRandomForestClassifier = TunedModel(
        model = pipeRandomForestClassifier,
        range = r1,
        measures = [cross_entropy, BrierScore()],
        resampling = CV(nfolds = 5)
)  

> julia> mtm = machine(tmRandomForestClassifier, X, y)
> Machine{ProbabilisticTunedModel{Grid,…}} @430 trained 0 times.
>   args:
>     1:  Source @867 ⏎ `Table{AbstractArray{Continuous,1}}`
>     2:  Source @357 ⏎ `AbstractArray{Multiclass{6},1}`


> julia> fit!(mtm)
> [ Info: Training Machine{ProbabilisticTunedModel{Grid,…}} @430.
> [ Info: Attempting to evaluate 2 models.
> ERROR: BoundsError
> Stacktrace:
>  [1] getindex at .\number.jl:78 [inlined]
>  [2] getter at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\univariate_finite\arrays.jl:137 [inlined]
>  [3] _broadcast_getindex_evalf at .\broadcast.jl:631 [inlined]
>  [4] _broadcast_getindex at .\broadcast.jl:604 [inlined]
>  [5] getindex at .\broadcast.jl:564 [inlined]
>  [6] macro expansion at .\broadcast.jl:910 [inlined]
>  [7] macro expansion at .\simdloop.jl:77 [inlined]
>  [8] copyto! at .\broadcast.jl:909 [inlined]
>  [9] copyto! at .\broadcast.jl:864 [inlined]
>  [10] copy at .\broadcast.jl:840 [inlined]
>  [11] materialize at .\broadcast.jl:820 [inlined]
>  [12] broadcasted(::typeof(pdf), ::MLJBase.UnivariateFiniteArray{Multiclass{6},Int64,UInt32,Float64,1}, ::CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\univariate_finite\arrays.jl:138
>  [13] broadcast at .\broadcast.jl:758 [inlined]
>  [14] (::BrierScore{UnivariateFinite})(::MLJBase.UnivariateFiniteArray{Multiclass{6},Int64,UInt32,Float64,1}, ::CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}}, ::Nothing) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\measures\finite.jl:183
>  [15] BrierScore at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\measures\finite.jl:173 [inlined]
>  [16] value at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\measures\measures.jl:78 [inlined]
>  [17] value(::BrierScore{UnivariateFinite}, ::MLJBase.UnivariateFiniteArray{Multiclass{6},Int64,UInt32,Float64,1}, ::DataFrame, ::CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}}, ::Nothing) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\measures\measures.jl:64
>  [18] (::MLJBase.var"#264#269"{DataFrame,CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}},MLJBase.UnivariateFiniteArray{Multiclass{6},Int64,UInt32,Float64,1}})(::BrierScore{UnivariateFinite}) at .\none:0
>  [19] iterate at .\generator.jl:47 [inlined]
>  [20] collect_to!(::Array{Array{Float64,1},1}, ::Base.Generator{Array{MLJBase.Measure,1},MLJBase.var"#264#269"{DataFrame,CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}},MLJBase.UnivariateFiniteArray{Multiclass{6},Int64,UInt32,Float64,1}}}, ::Int64, ::Int64) at .\array.jl:711
>  [21] collect_to_with_first!(::Array{Array{Float64,1},1}, ::Array{Float64,1}, ::Base.Generator{Array{MLJBase.Measure,1},MLJBase.var"#264#269"{DataFrame,CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}},MLJBase.UnivariateFiniteArray{Multiclass{6},Int64,UInt32,Float64,1}}}, ::Int64) at .\array.jl:689
>  [22] collect(::Base.Generator{Array{MLJBase.Measure,1},MLJBase.var"#264#269"{DataFrame,CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}},MLJBase.UnivariateFiniteArray{Multiclass{6},Int64,UInt32,Float64,1}}}) at .\array.jl:670
>  [23] (::MLJBase.var"#get_measurements#268"{Array{Tuple{Array{Int64,1},UnitRange{Int64}},1},Nothing,Int64,Array{MLJBase.Measure,1},typeof(predict),Bool,DataFrame,CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}}})(::Machine{Pipeline255}, ::Int64) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\resampling.jl:779
>  [24] #248 at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\resampling.jl:644 [inlined]
>  [25] _mapreduce(::MLJBase.var"#248#249"{MLJBase.var"#get_measurements#268"{Array{Tuple{Array{Int64,1},UnitRange{Int64}},1},Nothing,Int64,Array{MLJBase.Measure,1},typeof(predict),Bool,DataFrame,CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}}},Machine{Pipeline255},Int64,ProgressMeter.Progress}, ::typeof(vcat), ::IndexLinear, ::UnitRange{Int64}) at .\reduce.jl:400
>  [26] _mapreduce_dim at .\reducedim.jl:312 [inlined]
>  [27] #mapreduce#580 at .\reducedim.jl:307 [inlined]
>  [28] mapreduce at .\reducedim.jl:307 [inlined]
>  [29] _evaluate!(::MLJBase.var"#get_measurements#268"{Array{Tuple{Array{Int64,1},UnitRange{Int64}},1},Nothing,Int64,Array{MLJBase.Measure,1},typeof(predict),Bool,DataFrame,CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}}}, ::Machine{Pipeline255}, ::CPU1{Nothing}, ::Int64, ::Int64) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\resampling.jl:643
>  [30] evaluate!(::Machine{Pipeline255}, ::Array{Tuple{Array{Int64,1},UnitRange{Int64}},1}, ::Nothing, ::Nothing, ::Int64, ::Int64, ::Array{MLJBase.Measure,1}, ::typeof(predict), ::CPU1{Nothing}, ::Bool) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\resampling.jl:796
>  [31] evaluate!(::Machine{Pipeline255}, ::CV, ::Nothing, ::Nothing, ::Int64, ::Int64, ::Array{MLJBase.Measure,1}, ::Function, ::CPU1{Nothing}, ::Bool) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\resampling.jl:859
>  [32] fit(::Resampler{CV,Pipeline255}, ::Int64, ::DataFrame, ::CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\resampling.jl:959
>  [33] fit_only!(::Machine{Resampler{CV,Pipeline255}}; rows::Nothing, verbosity::Int64, force::Bool) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:416
>  [34] #fit!#80 at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:461 [inlined]
>  [35] event(::Pipeline255, ::Machine{Resampler{CV,Pipeline255}}, ::Int64, ::Grid, ::Nothing, ::NamedTuple{(:models, :fields, :parameter_scales),Tuple{Array{Pipeline255,1},Array{Expr,1},Array{Symbol,1}}}) at C:\Users\BCP\.julia\packages\MLJTuning\oLVRR\src\tuned_models.jl:257
>  [36] #6 at C:\Users\BCP\.julia\packages\MLJTuning\oLVRR\src\tuned_models.jl:291 [inlined]
>  [37] iterate at .\generator.jl:47 [inlined]
>  [38] _collect(::Array{Pipeline255,1}, ::Base.Generator{Array{Pipeline255,1},MLJTuning.var"#6#7"{Machine{Resampler{CV,Pipeline255}},Int64,Grid,Nothing,NamedTuple{(:models, :fields, :parameter_scales),Tuple{Array{Pipeline255,1},Array{Expr,1},Array{Symbol,1}}},ProgressMeter.Progress}}, ::Base.EltypeUnknown, ::Base.HasShape{1}) at .\array.jl:678
>  [39] collect_similar at .\array.jl:607 [inlined]
>  [40] map at .\abstractarray.jl:2072 [inlined]
>  [41] assemble_events(::Array{Pipeline255,1}, ::Machine{Resampler{CV,Pipeline255}}, ::Int64, ::Grid, ::Nothing, ::NamedTuple{(:models, :fields, :parameter_scales),Tuple{Array{Pipeline255,1},Array{Expr,1},Array{Symbol,1}}}, ::CPU1{Nothing}) at C:\Users\BCP\.julia\packages\MLJTuning\oLVRR\src\tuned_models.jl:290
>  [42] build(::Nothing, ::Int64, ::Grid, ::Pipeline255, ::NamedTuple{(:models, :fields, :parameter_scales),Tuple{Array{Pipeline255,1},Array{Expr,1},Array{Symbol,1}}}, ::Int64, ::CPU1{Nothing}, ::Machine{Resampler{CV,Pipeline255}}) at C:\Users\BCP\.julia\packages\MLJTuning\oLVRR\src\tuned_models.jl:454
>  [43] fit(::MLJTuning.ProbabilisticTunedModel{Grid,Pipeline255}, ::Int64, ::DataFrame, ::CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}}) at C:\Users\BCP\.julia\packages\MLJTuning\oLVRR\src\tuned_models.jl:491
>  [44] fit_only!(::Machine{MLJTuning.ProbabilisticTunedModel{Grid,Pipeline255}}; rows::Nothing, verbosity::Int64, force::Bool) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:416
>  [45] fit_only! at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:384 [inlined]
>  [46] #fit!#80 at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:461 [inlined]
>  [47] fit!(::Machine{MLJTuning.ProbabilisticTunedModel{Grid,Pipeline255}}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:459
>  [48] top-level scope at REPL[18]:1
>

**Comment by ablaom** [comment]
If I use the crab data set (and drop all the @Everywhere stuff which I'm guessing is not relevant) then I don't get any problems:

```julia
import DataFrames
using MLJ

X, y = @load_crabs
X = DataFrames.DataFrame(X)


@load RandomForestClassifier pkg=DecisionTree

pipeRandomForestClassifier = @pipeline FeatureSelector RandomForestClassifier
cases = [[Symbol(names(X)[j]) for j in 1:i] for i in 1:DataFrames.ncol(X)]
r1 = range(pipeRandomForestClassifier, :(feature_selector.features), values=cases)
tmRandomForestClassifier = TunedModel(
model = pipeRandomForestClassifier,
range = r1,
measures = [cross_entropy, BrierScore()],
resampling = CV(nfolds = 5)
)

mtm = machine(tmRandomForestClassifier, X, y)
julia> evaluate!(mtm, measure=cross_entropy)
Evaluating over 6 folds: 100%[=========================] Time: 0:00:00
┌───────────────┬───────────────┬─────────────────────────────────────────┐
│ _.measure     │ _.measurement │ _.per_fold                              │
├───────────────┼───────────────┼─────────────────────────────────────────┤
│ cross_entropy │ 1.61          │ [0.474, 1.93, 4.16, 0.763, 1.85, 0.489] │
└───────────────┴───────────────┴─────────────────────────────────────────┘
_.per_observation = [[[0.916, 0.357, ..., 0.223], [0.223, 0.357, ..., 0.223], [2.22e-16, 0.357, ..., 36.0], [2.3, 2.3, ..., 2.22e-16], [2.22e-16, 0.105, ..., 0.916], [0.223, 1.61, ..., 0.105]]]

```

Maybe your data is not compatible with the model. Can you please do `schema(X)` and `typeof(yc)` for me?

**Comment by drcxcruz** [comment]
hi,  

"@Everywhere stuff which I'm guessing is not relevant."  Sorry, it is 110% relevant :)  why did you take out the @everywhere in your code example?  did you get any errors with @everywhere?  are you able to run the MLJ model with the crabs data in parallel in 4 workers?

my program runs a few models in parallel using at least 4 workers.  each worker runs a MLJ model with the given X, and y.  we must use parallelism due to the high volume of data and complicated (and slow) algorithm.  

was version 0.12 tested in the parallel setting with @everywhere, pmap, and spawn?  If 0.12 does not work in parallel, it is a show stopper for us and I imagine others as well :)

"Maybe your data is not compatible with the model. Can you please do schema(X) and typeof(yc) for me?"  Sorry, my code has been working for months before I upgraded to version 0.12 :)

thanks for looking again.

**Comment by drcxcruz** [comment]
for simplicity, I am going to redesign my code to use pmap and not spawn.  thank you
