### ISSUE TITLE
LogisticModel:  pdf(ŷ[i], 1)  does not work after the last release

### ISSUE THREAD

**Issue by drcxcruz** [alan-turing-institute/MLJ.jl#599]
**Describe the bug**
pdf(ŷ[i], 1)  does not work after the last release for the LogisticModel.  How do we get the the two values stored in a  UnivariateFinite?  is there a function similar to pdf for UnivariateFinite items? Thanks

**To Reproduce**

@everywhere MLJ.@load LinearRegressor          pkg = GLM
@everywhere MLJ.@load LinearBinaryClassifier   pkg = GLM

LinearBinaryClassifierPipe = @pipeline Standardizer LinearBinaryClassifier
        yc =  categorical(y[:, 1])
        LogisticModel = machine(LinearBinaryClassifierPipe, X, yc)
        fit!(LogisticModel)
        fp = fitted_params(LogisticModel)
        k = collect(keys(fp.fitted_params_given_machine))[2]
        coefs = fp.fitted_params_given_machine[k].coef
        ŷ = MLJ.predict(LogisticModel, X)
       yhatResponse = [pdf(ŷ[i], 1) for i in 1:length(ŷ)]     # probability to 1 ala R 

ERROR: MethodError: no method matching getindex(::UnivariateFinite{Multiclass{2},Float64,UInt32,Float64}, ::Int64)

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by ablaom** [comment]
Thanks for reporting.

I am unable to reproduce using crab data - see below. Can you please provide some data `(X, yc)` which reproduces your error? 

```julia
using MLJ

@load LinearRegressor pkg = GLM
@load LinearBinaryClassifier pkg = GLM

X, yc = @load_crabs

LinearBinaryClassifierPipe = @pipeline Standardizer LinearBinaryClassifier

LogisticModel = machine(LinearBinaryClassifierPipe, X, yc)
fit!(LogisticModel)
ŷ = MLJ.predict(LogisticModel, X)

yhatResponse = [pdf(ŷ[i], "B") for i in 1:length(ŷ)];
julia> yhatResponse[1:4]
4-element Array{Float64,1}:
 0.9999999998687111
 0.9999999999924865
 1.0
 0.9999999999999851
```

**Comment by drcxcruz** [comment]
hi,

here is the minimal code that generates an error.  now, i am getting another error :(   thanks for your expertise.  

[Issue2.zip](https://github.com/alan-turing-institute/MLJ.jl/files/4922415/Issue2.zip)


using Distributed
import Hwloc
if length(workers()) == 1
    addprocs(Hwloc.num_physical_cores())  # get ready for parallelism
end
@everywhere begin
    using HypothesisTests: pvalue, UnequalVarianceTTest, VarianceFTest, EqualVarianceTTest
    using MLJ
    using DataFrames: DataFrame
    using CategoricalArrays: CategoricalArray
    using Distributions: UnivariateDistribution
end

@everywhere MLJ.@load LinearRegressor          pkg = GLM
@everywhere MLJ.@load LinearBinaryClassifier   pkg = GLM


# college data 
using CSV, DataFrames, Query
cd("C:\\Users\\BCP\\github\\ICP\\Test")
dfX3 = CSV.File("X3a.csv") |> DataFrame
dfY3 = CSV.File("Y3a.csv") |> DataFrame

X = copy(dfX3)
coerce!(X, autotype(X, :discrete_to_continuous))
y = copy(dfY3)

LinearBinaryClassifierPipe = @pipeline Standardizer LinearBinaryClassifier
yc =  categorical(y[:, 1])
LogisticModel = machine(LinearBinaryClassifierPipe, X, yc)




> julia> LogisticModel = machine(LinearBinaryClassifierPipe, X, yc)
> Machine{Pipeline269} @320 trained 0 times.
>   args:
>     1:  Source @470 ⏎ `Table{Union{AbstractArray{Continuous,1}, AbstractArray{Textual,1}}}`
>     2:  Source @149 ⏎ `AbstractArray{Multiclass{2},1}`


> julia> fit!(LogisticModel)
> [ Info: Training Machine{Pipeline269} @320.
> [ Info: Training Machine{Standardizer} @789.
> [ Info: Training Machine{LinearBinaryClassifier{LogitLink}} @900.
> ┌ Error: Problem fitting Machine{LinearBinaryClassifier{LogitLink}} @900
> └ @ MLJBase C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:486
> ERROR: TaskFailedException:
> MethodError: no method matching one(::Type{Any})
> Closest candidates are:
>   one(::Type{Union{Missing, T}}) where T at missing.jl:105
>   one(::Type{Missing}) at missing.jl:103
>   one(::BitArray{2}) at bitarray.jl:422
>   ...
> Stacktrace:
>  [1] fit_only!(::Machine{MLJModels.GLM_.LinearBinaryClassifier{GLM.LogitLink}}, ::Bool; kwargs::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:verbosity,),Tuple{Int64}}}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:487
>  [2] (::MLJBase.var"#98#100"{Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:verbosity,),Tuple{Int64}}},Machine{MLJModels.GLM_.LinearBinaryClassifier{GLM.LogitLink}}})() at .\task.jl:358
> Stacktrace:
>  [1] sync_end(::Array{Any,1}) at .\task.jl:316
>  [2] macro expansion at .\task.jl:335 [inlined]
>  [3] fit!(::Node{Nothing}, ::CPU1{Nothing}; kwargs::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:verbosity,),Tuple{Int64}}}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\composition\learning_networks\nodes.jl:189
>  [4] #fit!#94 at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\composition\learning_networks\nodes.jl:171 [inlined]
>  [5] fit!(::Machine{ProbabilisticSurrogate}; kwargs::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:verbosity,),Tuple{Int64}}}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\composition\learning_networks\machines.jl:152
>  [6] (::MLJBase.var"#_fit#184"{Machine{ProbabilisticSurrogate},Tuple{Standardizer,MLJModels.GLM_.LinearBinaryClassifier{GLM.LogitLink}},Tuple{MLJBase.Source,MLJBase.Source}})(::Pipeline269, ::Int64, ::DataFrame, ::Vararg{Any,N} where N) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\composition\models\from_network.jl:25
>  [7] fit(::Pipeline269, ::Int64, ::DataFrame, ::CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\composition\models\from_network.jl:168
>  [8] fit_only!(::Machine{Pipeline269}; rows::Nothing, verbosity::Int64, force::Bool) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:416
>  [9] fit_only! at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:384 [inlined]
>  [10] #fit!#80 at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:461 [inlined]
>  [11] fit!(::Machine{Pipeline269}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:459
>  [12] top-level scope at REPL[40]:1
> 
> 
> 


fp = fitted_params(LogisticModel)
k = collect(keys(fp.fitted_params_given_machine))[2]
coefs = fp.fitted_params_given_machine[k].coef
ŷ = MLJ.predict(LogisticModel, X)
		
yhatResponse = [pdf(ŷ[i], 1) for i in 1:length(ŷ)]     # probability to 1 ala R

**Comment by ablaom** [comment]
This looks like a classification problem with continuous input features. Do you get the same error if you instead do `X, yc = @load_iris` ?

**Comment by drcxcruz** [comment]
Hi, it is not working with the iris data set neither.   My code was working for months before version 0.12 :)   Was 0.12 tested in the parallel setting with @everywhere, pmap, spawn, etc.   ?  


using Distributed
import Hwloc
if length(workers()) == 1
    addprocs(Hwloc.num_physical_cores())  
end
@everywhere begin
    using HypothesisTests: pvalue, UnequalVarianceTTest, VarianceFTest, EqualVarianceTTest
    using MLJ
    using DataFrames: DataFrame
    using CategoricalArrays: CategoricalArray
    using Distributions: UnivariateDistribution
end

@everywhere MLJ.@load LinearRegressor          pkg = GLM
@everywhere MLJ.@load LinearBinaryClassifier   pkg = GLM

X, y = @load_iris
yc =  categorical(y[:, 1])

> julia> LogisticModel = machine(LinearBinaryClassifierPipe, X, yc)
> ┌ Warning: The scitype of `y`, in `machine(model, X, y, ...)` is incompatible with `model`:
> │ scitype(y) = AbstractArray{Multiclass{3},1}
> │ target_scitype(model) = AbstractArray{#s18,1} where #s18<:Finite{2}.
> └ @ MLJBase C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:81
> Machine{Pipeline262} @582 trained 0 times.
>   args:
>     1:  Source @584 ⏎ `Table{AbstractArray{Continuous,1}}`
>     2:  Source @219 ⏎ `AbstractArray{Multiclass{3},1}`
> 


> julia> fit!(LogisticModel)
> [ Info: Training Machine{Pipeline262} @582.
> [ Info: Training Machine{Standardizer} @426.
> [ Info: Training Machine{LinearBinaryClassifier{LogitLink}} @656.
> ┌ Error: Problem fitting Machine{LinearBinaryClassifier{LogitLink}} @656
> └ @ MLJBase C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:486
> ERROR: TaskFailedException:
> ArgumentError: y must be in the support of D
> Stacktrace:
>  [1] fit_only!(::Machine{MLJModels.GLM_.LinearBinaryClassifier{GLM.LogitLink}}, ::Bool; kwargs::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:verbosity,),Tuple{Int64}}}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:487
>  [2] (::MLJBase.var"#98#100"{Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:verbosity,),Tuple{Int64}}},Machine{MLJModels.GLM_.LinearBinaryClassifier{GLM.LogitLink}}})() at .\task.jl:358
> Stacktrace:
>  [1] sync_end(::Array{Any,1}) at .\task.jl:316
>  [2] macro expansion at .\task.jl:335 [inlined]
>  [3] fit!(::Node{Nothing}, ::CPU1{Nothing}; kwargs::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:verbosity,),Tuple{Int64}}}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\composition\learning_networks\nodes.jl:189
>  [4] #fit!#94 at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\composition\learning_networks\nodes.jl:171 [inlined]
>  [5] fit!(::Machine{ProbabilisticSurrogate}; kwargs::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:verbosity,),Tuple{Int64}}}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\composition\learning_networks\machines.jl:152
>  [6] (::MLJBase.var"#_fit#184"{Machine{ProbabilisticSurrogate},Tuple{Standardizer,MLJModels.GLM_.LinearBinaryClassifier{GLM.LogitLink}},Tuple{MLJBase.Source,MLJBase.Source}})(::Pipeline262, ::Int64, ::NamedTuple{(:sepal_length, :sepal_width, :petal_length, :petal_width),NTuple{4,Array{Float64,1}}}, ::Vararg{Any,N} where N) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\composition\models\from_network.jl:25
>  [7] fit(::Pipeline262, ::Int64, ::NamedTuple{(:sepal_length, :sepal_width, :petal_length, :petal_width),NTuple{4,Array{Float64,1}}}, ::CategoricalArray{String,1,UInt32,String,CategoricalArrays.CategoricalValue{String,UInt32},Union{}}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\composition\models\from_network.jl:168
>  [8] fit_only!(::Machine{Pipeline262}; rows::Nothing, verbosity::Int64, force::Bool) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:416
>  [9] fit_only! at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:384 [inlined]
>  [10] #fit!#80 at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:461 [inlined]
>  [11] fit!(::Machine{Pipeline262}) at C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:459
>  [12] top-level scope at REPL[20]:1
> 


julia> typeof(X)
NamedTuple{(:sepal_length, :sepal_width, :petal_length, :petal_width),NTuple{4,Array{Float64,1}}}

julia> typeof(yc)
CategoricalArray{String,1,UInt32,String,CategoricalArrays.CategoricalValue{String,UInt32},Union{}}

**Comment by drcxcruz** [comment]
it does not work even if i take out the @everywhere


using MLJ
MLJ.@load LinearRegressor          pkg = GLM
MLJ.@load LinearBinaryClassifier   pkg = GLM


X, y = @load_iris
typeof(X)
typeof(y)
yc =  categorical(y[:, 1])


julia> LogisticModel = machine(LinearBinaryClassifierPipe, X, yc)
┌ Warning: The scitype of `y`, in `machine(model, X, y, ...)` is incompatible with `model`:
│ scitype(y) = AbstractArray{Multiclass{3},1}
│ target_scitype(model) = AbstractArray{#s10,1} where #s10<:Finite{2}.
└ @ MLJBase C:\Users\BCP\.julia\packages\MLJBase\r3heT\src\machines.jl:81
Machine{Pipeline255} @350 trained 0 times.
  args:
    1:  Source @624 ⏎ `Table{AbstractArray{Continuous,1}}`
    2:  Source @595 ⏎ `AbstractArray{Multiclass{3},1}`

**Comment by drcxcruz** [comment]
hi again,

sorry :)  I am able to predict now but my **pdf** function is still not working.  The @everywhere is required since we run MLJ models in parallel.  


using Distributed
import Hwloc
if length(workers()) == 1
addprocs(Hwloc.num_physical_cores()) # get ready for parallelism
end
@everywhere begin
using HypothesisTests: pvalue, UnequalVarianceTTest, VarianceFTest, EqualVarianceTTest
using MLJ
using DataFrames: DataFrame
using CategoricalArrays: CategoricalArray
using Distributions: UnivariateDistribution
end

@everywhere MLJ.@load LinearRegressor pkg = GLM
@everywhere MLJ.@load LinearBinaryClassifier pkg = GLM

X, y = @load_crabs
typeof(X)
typeof(y)
yc = categorical(y[:, 1])

LinearBinaryClassifierPipe = @pipeline Standardizer LinearBinaryClassifier
LogisticModel = machine(LinearBinaryClassifierPipe, X, yc)

fit!(LogisticModel)
fp = fitted_params(LogisticModel)
 
Julia> ŷ = MLJ.predict(LogisticModel, X)
200-element MLJBase.UnivariateFiniteArray{Multiclass{2},String,UInt32,Float64,1}:
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>1.31e-10)
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>7.51e-12)
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>2.72e-20)
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>1.49e-14)
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>1.75e-9)
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>1.98e-14)
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>2.01e-14)
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>1.03e-15)
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>2.02e-12)
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>3.09e-22)
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>2.12e-32)
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>8.339999999999999e-27)
 UnivariateFinite{Multiclass{2}}(B=>1.0, O=>8.78e-22)


> julia> yhatResponse = [pdf(ŷ[i], 1) for i in 1:length(ŷ)]
> ERROR: MethodError: no method matching pdf(::UnivariateFinite{Multiclass{2},String,UInt32,Float64}, ::Int64)
> Closest candidates are:
>   pdf(::Distributions.DiscreteUniform, ::Int64) at C:\Users\BCP\.julia\packages\Distributions\RAeyY\src\univariate\discrete\discreteuniform.jl:77
>   pdf(::Distributions.Hypergeometric, ::Int64) at C:\Users\BCP\.julia\packages\Distributions\RAeyY\src\univariates.jl:553
>   pdf(::Distributions.Chernoff, ::Real) at C:\Users\BCP\.julia\packages\Distributions\RAeyY\src\univariate\continuous\chernoff.jl:168
>   ...
> Stacktrace:
>  [1] (::var"#10#11")(::Int64) at .\none:0
>  [2] iterate at .\generator.jl:47 [inlined]
>  [3] collect(::Base.Generator{UnitRange{Int64},var"#10#11"}) at .\array.jl:665
>  [4] top-level scope at REPL[16]:1
>
