### ISSUE TITLE
Unable to use functions predict(), predict_mode()

### ISSUE THREAD

**Issue by gd1989** [alan-turing-institute/MLJ.jl#602]
**Describe the bug**
Functions predict() and predict_mode() raise deprecation warnings.

**To Reproduce**
```julia
ŷ = predict_mode(clf, rows=test)

ŷ = predict(clf, rows=test)
```

**Expected behavior**
I though the possibility to specifiy rows to use has been brought back in?

**Additional context**
```julia
┌ Warning: `predict_mode(mach)` and `predict_mode(mach, rows=...)` are deprecated. Data or nodes should be explictly specified, as in `predict_mode(mach, X)`. 
│   caller = ip:0x0
└ @ Core :-1

┌ Warning: `predict(mach)` and `predict(mach, rows=...)` are deprecated. Data or nodes should be explictly specified, as in `predict_mode(mach, X)`. 
│   caller = ip:0x0
└ @ Core :-1

```

**Versions**
<details>

</details>

**Comment by ablaom** [comment]
It has, in MLJBase 0.14.3 (now we have 0.14.4). Are you sure you have the right version installed? Can you do `]status -m` to find out, our manually inspect your Manifest.toml

**Comment by gd1989** [comment]
Ah indeed, the version we are working with is MLJBase 0.14.1 @tlienart 
Thanks!

**Comment by tlienart** [comment]
this is still an issue as far as I'm aware, including with 14.4, @gd1989 could you provide an example + status please?

**Comment by gd1989** [comment]
UPDATE from initial issue

**Describe the bug**
Only function `predict_mode()` raises deprecation warning now.
Also, what is confusing is that the warning message raised when using `predict_mode()` refers to both `predict()` and `predict_mode()` while it should only apply to `predict_mode()`.


**To Reproduce**
```julia
ŷ = predict_mode(clf, rows=test)
```

**Expected behavior**
I thought the possibility to specifiy rows to use has been brought back in?

**Additional context**
```julia
┌ Warning: `predict_mode(mach)` and `predict_mode(mach, rows=...)` are deprecated. Data or nodes should be explictly specified, as in `predict_mode(mach, X)`. 
│   caller = ip:0x0
└ @ Core :-1
```

**Versions**
<details>



</details>

**Comment by gd1989** [comment]
sorted! package version incompatibilies were causing the issue
