### ISSUE TITLE
Add section on creating synthetic data to the manual

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#604]
`make_regression`, `make_blobs`, and so forth are not well-known.

**Comment by drcxcruz** [comment]
hello,

I  can work on a jupyter lab to show case function calls like the following.   let me know of any comments.  thanks 

> X, y = make_regression(100, 2)
> X, y = make_blobs(100, 2)
> 
> make_moons(100)
> make_circles(100)

**Comment by ablaom** [comment]
That would be great! I was thinking we should at least add something to the docs at docs/src/ . Maybe a new section called "Generating Synthetic Data". But once you have a tutorial, I could just copy and paste from that.

**Comment by drcxcruz** [comment]
Hello, 

Please let me know of any comments or suggestion on 
PR https://github.com/alan-turing-institute/MLJ.jl/pull/621

Thanks

**Comment by drcxcruz** [comment]
hello,

Just checking to see if I can close this issue :)
Was it released to production?  I do not see it in https://alan-turing-institute.github.io/MLJ.jl/stable/
Thanks

**Comment by ablaom** [comment]
I think you want to visit the dev branch. https://alan-turing-institute.github.io/MLJ.jl/dev/generating_synthetic_data/

Where did you get the link to the "stable" version? This should probably be changed. 

BTW I updated the doc-strings themselves, but they won't be live until the next MLJBase release

**Comment by drcxcruz** [comment]
hi there,

OK, thanks, I am getting the stable documentation from https://github.com/alan-turing-institute/MLJ.jl  . I still do not see anything anything when I search for "make_blods" in the stale documents.

I do not see this change in the PRs of  https://github.com/alan-turing-institute/MLJBase.jl .   I do see "ablaom added do not merge docs labels 9 days ago."  If there is no merge, how do we release it to production?  is something missing or am i misunderstanding? :)

**Comment by ablaom** [comment]
The additions on master are there: https://github.com/alan-turing-institute/MLJ.jl/blob/master/docs/src/generating_synthetic_data.md

Note, as explained in the PR replacing yours (https://github.com/alan-turing-institute/MLJ.jl/pull/626) the stuff you copied from the doc-strings is now automatically generated by Documenter. You can see the results of that in the link I just gave you ( https://alan-turing-institute.github.io/MLJ.jl/dev/generating_synthetic_data/). I'm guessing you won't see these in the "stable" version until we tag a new MLJ release, which we don't normally do just for doc additions.
