### ISSUE TITLE
Documentation for adding models: Discourage fields with type Union{Nothing,T} where T<:Real

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#606]
See https://github.com/alan-turing-institute/MLJBase.jl/issues/372#issuecomment-661360422

**Comment by drcxcruz** [comment]
Hi,  I will read the thread and do a write up.  should it be a new document section or a subsection of an existing document?   thanks

**Comment by ablaom** [comment]
Just add a sentence or two in these subsections:

https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#New-model-type-declarations-and-optional-clean!-method-1

https://alan-turing-institute.github.io/MLJ.jl/dev/quick_start_guide_to_adding_models/#Model-type-and-constructor-1

Something like:

"Although not essential, try to avoid `Union` types for model fields. For example, a field declaration `features::Vector{Symbol}` with a default of `Symbol[]` (detected with `isempty`) is preferred to `features::Union{Vector{Symbol}, Nothing}` with a default of `nothing`. 

Thanks!

**Comment by drcxcruz** [comment]
hi there,

I created two PRs

1. https://github.com/alan-turing-institute/MLJ.jl/pull/636
2. https://github.com/alan-turing-institute/MLJ.jl/pull/637

Please let me know of any comments.  

Thanks

**Comment by OkonSamuel** [comment]
@ablaom can we close this?
