### ISSUE TITLE
Allow access to the outcomes of fitting models on each fold in resampling

### ISSUE THREAD

**Issue by CameronBieganek** [alan-turing-institute/MLJ.jl#616]
Sometimes I would like to look at the models fit on each fold in a cross-validation. For instance, I might want to look at the hyperparameters that were selected in each fold if the model is a tuned model.

Consider this example:

```julia
using MLJ
using DataFrames
@load RandomForestRegressor pkg=DecisionTree

X = DataFrame(randn(100, 4));
y = randn(100);

tunable_rf = TunedModel(
    model = RandomForestRegressor(),
    tuning = Grid(shuffle=false),
    measure = rms,
    range = range(RandomForestRegressor(), :n_trees; values=[10, 20]),
    resampling = Holdout(fraction_train=0.8)
)

mach = machine(tunable_rf, X, y)
e = evaluate!(mach; resampling=CV(nfolds=3), measure=rms)
```

I can only access the best model for the fold that was trained most recently, like so:

```julia
julia> fitted_params(mach).best_model
RandomForestRegressor(
    max_depth = -1,
    min_samples_leaf = 1,
    min_samples_split = 2,
    min_purity_increase = 0.0,
    n_subfeatures = -1,
    n_trees = 10,
    sampling_fraction = 0.7,
    pdf_smoothing = 0.0) @706
```

The information on the best hyperparameters for the other folds appears to be lost.

**Comment by ablaom** [comment]
Sounds like a good idea.

 In terms of API, I guess we could introduce a new key for the object returned by `evaluate!`/`evaluate`, say `per_fold_model`. And then tuning strategies could elect to add these models to their `fitted_params`.

Any other suggestions?

**Comment by OkonSamuel** [comment]
I haven't given it much thought. What i had in mind was probably to add `report_per_fold` keyword to `evaluate!/evaluate` method. (I think for `TunedModel` the `report` contains info on the best model)

**Comment by ablaom** [comment]
@OkonSamuel Yes, that makes more sense. We add `report_per_fold` and also `fitted_params_per_fold` (for the complete picture). 

Alternatively, we could make it `machine_per_fold`, which would make both accessible from a single object (we would need to remove the data from the machines) but as the user will be exclusively interested in the report and learned parameters, this makes less sense to me.

Happy to provide guidance for a PR if someone wants this sooner rather than later 😄

**Comment by ablaom** [comment]
Will appear in MLJBase 0.15.0 and will be available in next minor release of MLJ.
