### ISSUE TITLE
transform for Clusterring and PCA should return tables

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#63]
In general transformers should return a table with the preferred sink type of `X`, where `X` is the table being transformed. Currently a matrix is being returned by KMeans, KMedoids and PCA. If `Xout` is this matrix, we should return instead `MLJBase.table(Xout, prototype=X)`

**Comment by tlienart** [comment]
For both `kmeans` and `kmedoids`, do you agree that what should be returned are the current assignments? and the report should contain the structure returned by `fit`?

So for instance `kmeans` returns `KmeansResult` struct with notable fields

* `centers` a matrix of size `p x k` where `p` is the dimensionality
* `assignments` a vector of size `n`

If we take these clustering methods as part of a pipeline summarising information then the only output that matters is the assignment isn't it?

(ok for PCA, will PR)

**Comment by tlienart** [comment]
Could I get some guidance on what should be returned in `Kmeans` and `Kmedoids`? specifically two things are of some importance:

* the assignments (a vector of size `n`), that's effectively the output of the algorithm
* the centers (a matrix of size `p x k`) which can be used to `transform` or `predict`

What might make sense is to leave the `fitresult` be the type returned by these algorithms e.g. `Clustering.KmeansResult` and extract specific elements in the `report` (though that seems like duplicating information unnecessarily). 

And then following that what do you recommend be wrapped in a table object?

(ok for PCA will PR)
