### ISSUE TITLE
potential bug in MLJBase.roc_curve

### ISSUE THREAD

**Issue by ma010** [alan-turing-institute/MLJ.jl#630]
**Describe the bug**
When using `MLJBase.roc_curve` function:
`tprs, fprs, ts = roc_curve(ŷ, y) = roc(ŷ, y)`,

I found out that the `tprs` and `fprs` may have been flipped around as my plot showed an upside down roc curve. Compared to `sklearn.metrics.roc_curve` function applied to the same dataset, I got the 'right' roc curve. Please help investigate. 

**To Reproduce**

```julia
using RDatasets, DataFrames, MLJ, DecisionTree, Plots, ScikitLearn

df = dataset("MASS", "Pima.te")

y, X = unpack(df, ==(:Type), colname -> true)

rf_model = @load RandomForestClassifier pkg="DecisionTree"
r1 = range(rf_model, :n_trees; values=[500]);
r2 = range(rf_model, :max_depth; values=[1, 2]);

tuned_model = TunedModel(model=rf_model,
                         resampling=CV(nfolds=3, rng=1886),
                         measure=BrierScore(),
                         range=[r1, r2])
tuned = machine(tuned_model, X, y)
train, test = partition(eachindex(y), 0.60, shuffle=true, rng=1886)

MLJ.fit!(tuned, rows=train)
yhat = MLJ.predict(tuned, X[test, :]);
tprs, fprs, ts = MLJ.roc_curve(yhat, y[test])
begin
    plotly()
    plot(fprs, tprs, label="MLJ ROC")
end
```
![mlj_roc](https://user-images.githubusercontent.com/9299020/89699905-71259980-d8f8-11ea-85c3-0a435b0cabb2.png)

However, when using `sklearn.metrics.roc_curve` 
```julia
using RDatasets, DataFrames, MLJ, DecisionTree, Plots, ScikitLearn

df = dataset("MASS", "Pima.te")

y, X = unpack(df, ==(:Type), colname -> true)

rf_model = @load RandomForestClassifier pkg="DecisionTree"
r1 = range(rf_model, :n_trees; values=[500]);
r2 = range(rf_model, :max_depth; values=[1, 2]);

tuned_model = TunedModel(model=rf_model,
                         resampling=CV(nfolds=3, rng=1886),
                         measure=BrierScore(),
                         range=[r1, r2])
tuned = machine(tuned_model, X, y)
train, test = partition(eachindex(y), 0.60, shuffle=true, rng=1886)

MLJ.fit!(tuned, rows=train)
yhat = MLJ.predict(tuned, X[test, :]);

y_true = Array{Int16, 1}(undef, length(y[test]))
for i in 1:length(y[test])
    if y[test][i] == "Yes"
        y_true[i] = 1
    else
        y_true[i] = 0
    end
end

@sk_import metrics: roc_curve
sk_fprs, sk_tprs, sk_ts = roc_curve(y_true, pdf.(yhat, "Yes"))
begin
    plotly()
    plot(sk_fprs, sk_tprs, label="Sk ROC")
end
```
I got a different curve.

**Expected behavior**
![sk_roc](https://user-images.githubusercontent.com/9299020/89699934-acc06380-d8f8-11ea-9be5-823141e3b38d.png)

**Versions**
```
DecisionTree v0.10.9
MLJ v0.12.0
MLJModels v0.11.3
ORCA v0.4.0
Plots v1.5.8
RDatasets v0.6.9
ScikitLearn v0.6.2
```

**Comment by ablaom** [comment]
@ma010 Thanks for reporting!

Yes, it looks to me like MLJ' documentation for `roc_curve` is incorrect. Rather than the current:

```julia
  tprs, fprs, ts = roc_curve(ŷ, y) = roc(ŷ, y)
```

it should read

```julia
  tprs, fprs, ts = roc_curve(ŷ, y) = roc(ŷ, y)
```

(which would be consistent with the scikitlearn implementation, as documented [here](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.roc_curve.html)

@tlienart Be good if you can confirm this diagnosis. I  have already checked that poster's `levels(y)` are consistent with our convention "negative < positive":

```julia
julia> levels(y)
2-element Array{String,1}:
 "No"
 "Yes"
``` 

Also, do you know if `roc_curve` is used in Data Science Tutorials ? We may want to check consistency there too.

**Comment by tlienart** [comment]
thanks both, yes the signature in the doc is incorrect, and, indeed, when I coded this I wanted the signature to be consistent with scikit learn.

amusingly roc is used (properly) in ISL Lab 4. 

I'll open a PR

**Comment by ma010** [comment]
Thank you all!
