### ISSUE TITLE
On models that fit a distribution to some data.

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#641]
@DilumAluthge has correctly pointed out an inconsistency in the API around these models, which we regard as `Supervised` with `X::Nothing`.  Currently, according to the [docs](https://alan-turing-institute.github.io/MLJ.jl/dev/adding_models_for_general_use/#Models-that-learn-a-probability-distribution-1) the ouput of `predict` for these models should be a distribution, but according to the general API for `Supervised` models, this should be a *vector* of distributions. Indeed, I suggest that for purposes of fitting these models into the rest of the framework (`evaluate!`, etc ) we should allow `X` to be `Vector{Nothing}` (one element per observation in `y`) and the predictions to be a vector of (constant) distributions, one for each element of `Xnew::Vector{Nothing}`. 

That is, if `d` is the distribution fit, then `predict(model, fitresult, [nothing, nothing, nothing])` returns `yhat = [d, d, d]`.  And if we have some new observations `y = [y1, y2, y3]`, we can do `m(yhat, y)` where `m` is a probabilistic measure (eg, proper scoring rule). 

Naturally, there would be no need for a model implementation to make actual *copies* of `d`. 

This is probably just a matter of changing the docs (which refers this part of the API as "experimental" anyway). 

Any other thoughts?

**Comment by DilumAluthge** [comment]
If these models are going to return a vector of distributions, does it make sense to also have them be subtypes of `Probabilistic`?

**Comment by ablaom** [comment]
I don't quite follow. We are changing the way distribution-fitting algorithms should be implemented precisely to ensure they conform to the `Probabilistic` API, which is necessary if we want to fit them into the same framework (allowing us to evaluate a scoring rule given some new point observations). 

I understand that viewing distribution-fitting algorithms as supervised models in this way (by viewing the data as the target `y` with "empty" `X`) is a standard trick.

Perhaps this will make more sense after I update the documentation where there is an example. I will ping you when I make the PR.

**Comment by DilumAluthge** [comment]
Perfect, yeah I think we are in agreement. Yeah ping me when you make the PR
