### ISSUE TITLE
MLJ_VERSION ci test fails on julia >=1.4

### ISSUE THREAD

**Issue by OkonSamuel** [alan-turing-institute/MLJ.jl#660]
For julia version >= 1.4 `MLJ_VERSION` test fails see [logs](https://travis-ci.com/github/alan-turing-institute/MLJ.jl/jobs/380057667) This is because MLJ isn't in the dependency graph while testing with julia versions >= 1.4. 
We have 2 choices here
1. revert to using Pkg.Toml.parse as in 
``` julia
 using Pkg.TOML 
 const MLJ_VERSION =
  VersionNumber(TOML.parsefile(joinpath(dirname(@__DIR__), "Project.toml"))["version"])`
```
2. disable ci tests for `MLJ_VERSION` while testing with julia version >=1.4

@tlienart , @ablaom , @DilumAluthge

**Comment by ablaom** [comment]
Well, looks like we're going round and round with this one. 😵 

 Unless @DilumAluthge wants to suggest a more canonical method of doing this, I'm happy for 1. I don't understand option 2, as it removes a test for something broken, no?

**Comment by DilumAluthge** [comment]
I think parsing the `Project.toml` file is the best bet here.
