### ISSUE TITLE
Add conspicuous links to List of Supported Models

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJ.jl#672]
I used to really like to vast list of models at the [MLJ](https://github.com/alan-turing-institute/MLJ.jl) Github homepage. The large list is one of the things that made me wanna try MLJ. 

Is the list permanently gone? 

The only comparable list I know is: https://github.com/alan-turing-institute/MLJModels.jl/blob/master/src/registry/Models.toml

**Comment by ablaom** [comment]
Great to have this feedback. It is not gone but moved: https://alan-turing-institute.github.io/MLJ.jl/dev/list_of_supported_models/

We should add some consipicuous links to improve discoverability.

**Comment by ablaom** [comment]
While we're at it, I noticed 3 models missing from MultivariateStats. Perhaps someone can do a review to find others that may have been missed.

**Comment by azev77** [comment]
BTW are PLS & SossMLJ ready to be added to the list of wrapped packages ?

**Comment by ablaom** [comment]
@azev77 PLS is now registered in pending MLJModels release. 

I think registration of SossMLJ is premature as the predicted "distributions" don't support enough of the API. For example, one cannot call `mean` on a single prediction, or alternatively `predict_mean`; and there are no probabilistic measures that will work with them at this time. That is, there is no way to readily compare their performance with existing models. 

You can still use the models with `using SossMLJ`.

**Comment by azev77** [comment]
@ablaom the following can automate a table showing all MLJ models, w/ all 20 traits per model
```julia
using MLJ, DataFrames, TableView
MLJ.models() |> DataFrames.DataFrame |> TableView.showtable
```

<img width="811" alt="image" src="https://user-images.githubusercontent.com/7883904/96494866-ee348f80-1214-11eb-9c14-8988bfad654c.png">

**Comment by ablaom** [comment]
Yeah, now the list in the Documenter.jl pages, we could do something like that.
