### ISSUE TITLE
Add link to TreeParzen from "Tuning Models" section of the manual, and the doc string for LatinHypercube

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#690]
The relevant page to be updated is https://github.com/alan-turing-institute/MLJ.jl/blob/master/docs/src/tuning_models.md

@ludoro Any chance you could do this?

**Comment by ablaom** [comment]
The tree parzen link is https://github.com/IQVIA-ML/TreeParzen.jl

**Comment by ludoro** [comment]
Yeah, will look into it

**Comment by ludoro** [comment]
Just create the PR for the tuning_models.md docs. However I don't get what I should do with TreeParzen.jl, should I add an example in their docs as well?

**Comment by ablaom** [comment]
Yeah, sorry for not being clearer. Can we just rewrite the first sentence like this:

```
Below we illustrate hyperparameter optimisation using the [`Grid`](@ref), [`RandomSearch`](@ref) and [`LatinHypercube`]
(@ref) tuning strategies. Also available is the [tree Parzen]() strategy;  for a complete list, 
see [here](https://github.com/alan-turing-institute/MLJTuning.jl#what-is-provided-here).
```

Just add it to the other PR, thanks.
