### ISSUE TITLE
No more symbols in CategoricalArrays

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#691]
The PR https://github.com/JuliaData/CategoricalArrays.jl/pull/310 means that an array with elements of type `Symbol` can no longer be wrapped as a `CategoricalArray`. 

This means **all MLJ documentation and test code that uses symbols in categorical data must be refactored to use strings instead**. 

These repos, at least, need checking/refactoring, in order of priority:

- [x] MLJ

- [x] MLJBase

- [x] MLJTuning

- [x] DataScienceTutorials

- [x] MLJScientificTypes

- [x] ScientificTypes

**Comment by arvganesh** [comment]
Hi, I just checked DataScienceTutorials and see that the types for CategoricalArray have been changed to Strings, does this issue still need to be open?

**Comment by ablaom** [comment]
Hey @arvganesh, thanks for chipping in.

Could you say how you confirmed this? 

The best test would be to bump the version of CategoricalArrays.jl in the [Manifest.toml](https://raw.githubusercontent.com/alan-turing-institute/DataScienceTutorials.jl/master/Manifest.toml) used by tutorials, which I see is still < 0.9 (when symbols disappeared) and check all the tutorial generate properly. I'm afraid I'm a little out-of-touch about the protocol for DataScienceTutorial updates, although I think this is documented [at the repo](https://github.com/alan-turing-institute/DataScienceTutorials.jl). A complete update of the tutorials is overdue, so it might make sense to close this current issue after that. 

But if you have an independent test...

**Comment by arvganesh** [comment]
Hi @ablaom, thanks for your reply. I checked for changes in two ways:

- Running `grep` to find '.jl' files with the keyword "categorical" and manually confirming that the Symbol type is not used (and that Strings were used) in Categorical Arrays.
- Changing the version of CategoricalArrays from `0.8.1` to `0.9` in the `Manifest.toml` file and running `serve()` from Franklin.

Let me know what you think.  I've attached a small PR that increments the version: https://github.com/alan-turing-institute/DataScienceTutorials.jl/pull/146.

**Comment by ablaom** [comment]
The first test may not be sufficient, as MLJ users may construct categorical vectors in other ways, eg,

```julia
coerce([:a, :a, :b], OrderedFactor)
```

However, the second sounds robust. 

I've copied the DataScienceTutorials author into your PR for comment, if possible. 

Many thanks

**Comment by arvganesh** [comment]
Great, thanks! Let me know if I can help further.
