### ISSUE TITLE
less fidgity alternative to `@load`

### ISSUE THREAD

**Issue by ExpandingMan** [alan-turing-institute/MLJ.jl#693]
In any of my normal workflows, `@load` is extremely problematic because Revise causes it to run repeatedly.  I have noticed that `@load` evals code directly into the module, which is pretty weird, and causes some pretty weird side-effects e.g. executing without showing you what was executed with `@macrocall`.

Personally, if it were up to me, I'd definitely change `@load` to just execute something incredibly straightforward such as:
```julia
using PackageContainingObject: Object
```
However, as this is not likely to change very soon as it's potentially breaking, I think it would be extremely helpful if we had another, more straightforward macro to go along with `@load` for situations in which `@load` is problematic.

I considered making a PR to MLJBase with a new macro, but, considering the strange behavior of `@load`, I wasn't quite sure what the consensus would be on what this should look like, where it should go, or whether it would even be accepted, so I thought I'd open up this issue before attempting anything.

**Comment by DilumAluthge** [comment]
Yeah, the fact that `@load` evals code is a bad sign.

As a general rule, macros should not run `eval`. Instead, a macro should return an expression containing the code that will be run.

**Comment by DilumAluthge** [comment]
Personally I just don't use the `@load` macro at all.

**Comment by ExpandingMan** [comment]
I think it is very bad that what `@load` does is simply not at all what users do and should expect a macro to do.  I very much believe that `@load` should be changed, but I assume the devs did it this way for a reason, so even if you guys are not willing to change it it would be nice to have an alternative.

**Comment by DilumAluthge** [comment]
Personally I think that the behavior of `@load` should be fixed so that it follows the commonly accepted guidelines for macros.

**Comment by DilumAluthge** [comment]
But yeah, if it is not possible to fix `@load`, I agree that we should have a saner alternative.

**Comment by ExpandingMan** [comment]
I'm starting to realize that the inability to use `@load` is a somewhat bigger problem than I thought.  Some model wrappers are loaded via MLJModels which uses `@require`, and it has been quite challenging to figure out how to get it to load the wrappers I need (I still have not been able to).  So as it stands the usability of MLJ seems rather compromised if `@load` is problematic for you.

**Comment by ExpandingMan** [comment]
For the record:
Currently `MLJModels` uses `Requires`, which works in `__init__`, so this means that if you want to import something form one of the MLJModels Requries packages, you need to put your import code in an `eval` inside your `__init__`.  Once MLJModels are disaggregated and we have the rest of the MLJInterface packages (current example: MLJScikitLearnInterface.jl), this is no longer necessary.

Presumably with these packages `@load` oculd just do a simple `import`.  I'm wondering if perhaps the reason for the `eval` in the first place was to get around issues with requires.

**Comment by ablaom** [comment]
As per slack discussion, implementation of @load is to be reviewed to remove `eval` . Intention of `@load` to remain the same, although `load` may be deprecated or replaced by some lower level functionality.

**Comment by ablaom** [comment]
I propose making default `verbosity=1` to remove mystery about what `@load` does, which prints how to suppress the diatribe.

**Comment by ablaom** [comment]
And we can overload `load_path` (a model trait) to work on strings, so that it returns the load path which the hacker can use to load code any which way.

As in `load_path("DecisionTreeRegressor", pkg="DecisionTree")` returns `:(MLJDecisionTreeInterface.DecisionTreeRegressor)` , the `pkg` kw only necessary to resolve duplicate model name over packages.

**Comment by CameronBieganek** [comment]
I've been away from MLJ for a while, so I'm not sure if this still works, but this is what I did to avoid using `@load`:

```julia
module Foo

using MLJ
import DecisionTree
import LIBSVM
import XGBoost
import MLJModels

import MLJBase
using MLJLinearModels: LogisticClassifier
import MLJLinearModels

include(joinpath(MLJModels.srcdir, "DecisionTree.jl"))
using .DecisionTree_: RandomForestClassifier

include(joinpath(MLJModels.srcdir, "XGBoost.jl"))
using .XGBoost_: XGBoostClassifier

include(joinpath(MLJModels.srcdir, "LIBSVM.jl"))
using .LIBSVM_: LinearSVC, SVC

include("foo.jl")

end
```

**Comment by ablaom** [comment]
This issue is resolved by https://github.com/alan-turing-institute/MLJModels.jl/pull/340, which will make the next minor release of MLJModels.
