### ISSUE TITLE
ERROR: MethodError: no method matching PCA() 

### ISSUE THREAD

**Issue by casasgomezuribarri** [alan-turing-institute/MLJ.jl#699]
**Describe the bug**
I am following the [MLJ.jl Data Science Tutorials](https://alan-turing-institute.github.io/DataScienceTutorials.jl/), and ran into an issue with [this one](https://alan-turing-institute.github.io/DataScienceTutorials.jl/isl/lab-10/) about PCA and Clustering.

I am trying to run this piece of code from the [first section](https://alan-turing-institute.github.io/DataScienceTutorials.jl/isl/lab-10/#pca_pipeline):

> @load PCA pkg=MultivariateStats
> 
> pca_mdl = PCA(pratio=1)
> pca = machine(pca_mdl, X)
> fit!(pca)
> PCA
> W = transform(pca, X);

And, although the first line is evaluated normally, all the other lines give back an error, which has its origin on the second line not being evaluated. This is the corresponding error:

> ERROR: MethodError: no method matching PCA()
> Closest candidates are:
> PCA(::Array{T,1}, ::Array{T,2}, ::Array{T,1}, ::T) where T<:Real at C:\Users\ivica.julia\packages\MultivariateStats\BYMwD\src\pca.jl:16
> PCA(::Array{T,1}, ::Array{T,2}, ::Array{T,1}, ::T, ::T) where T<:Real at C:\Users\ivica.julia\packages\MultivariateStats\BYMwD\src\pca.jl:6
> Stacktrace:
> [1] top-level scope at REPL[1]:1

The syntax of model creation seems to be consistent with the rest of the package, for example:

> dtr_model = DecisionTreeRegressor()

**Additional context**

I [posted this issue](https://github.com/JuliaStats/MultivariateStats.jl/issues/132) in the MultivariateStats.jl github repository since that is the package mentioned in the error message, but I was told to come over here instead. I hope someone can tell me what happened. 

I have been able to use every other ML model I have tried to use so far, PCA() seems to be the only one for which I get this error.

**Versions**
I am using Julia 1.4 on VSCode v. 1.51.0

</details>

**Comment by ablaom** [comment]
Thanks for reporting!

It's strange that you say the first line is successfully loading and my guess is that this is not really true. After the first line is executed your should get something like this:

```julia
julia> @load PCA pkg=MultivariateStats
PCA(
    maxoutdim = 0,
    method = :auto,
    pratio = 0.99,
    mean = nothing) @590
```
 Do you get this?

If you did not get this output and you did not get an error message, what IDE are you using?

One problem might be is that you have don't have MLJMultivariateStatsInterface to your environment, so try this:

```julia
using Pkg
Pkg.add("MLJMultivariateStatsInterface")
```

If this does not help can you please tell me the output of the following commands?

```julia
using Pkg
Pkg.status()
```

**Comment by casasgomezuribarri** [comment]
Hello, thanks for the reply.

Weirdly enough, when I went to try what you were suggesting the original code worked just fine (even though before posting any issues I rebooted my laptop and tried again with no success).

However, I do remember getting that as output for the first line, yes.

Out of curiosity, I ran `Pkg.status()`, just to see if I had MLJMultivariateStatsInterface in my env and got the following:

>   [336ed68f] CSV v0.7.7
>   [324d7699] CategoricalArrays v0.8.3
>   [a93c6f00] DataFrames v0.21.7
>   [7806a523] DecisionTree v0.10.10
>   [31c24e10] Distributions v0.23.12
>   [f6006082] EvoTrees v0.5.0
>   [cd3eb016] HTTP v0.8.19
>   [f4508453] InfoZIP v0.2.0
>   [1028da5a] LAJuliaUtils v0.3.0 #master (https://github.com/sylvaticus/LAJuliaUtils.jl.git)        
>   [b1bec4e5] LIBSVM v0.5.0
>   [30fc2ffe] LossFunctions v0.6.2
>   [add582a8] MLJ v0.13.0
>   [6ee0df7b] MLJLinearModels v0.5.1
>   [d491faf4] MLJModels v0.12.2
>   [5ae90465] MLJScikitLearnInterface v0.1.6       
>   [6f286f6a] MultivariateStats v0.7.0
>   [b8a86587] NearestNeighbors v0.4.6
>   [91a5bcdd] Plots v1.5.3
>   [c3e4b0f8] Pluto v0.12.6
>   [7f904dfe] PlutoUI v0.6.6
>   [f27b6e38] Polynomials v1.1.9
>   [54e16d92] PrettyPrinting v0.2.0
>   [438e738f] PyCall v1.92.1
>   [d330b81b] PyPlot v2.9.0
>   [ce6b1742] RDatasets v0.6.10
>   [860ef19b] StableRNGs v0.1.2
>   [2913bbd2] StatsBase v0.33.2
>   [856ac37a] UrlDownload v0.3.0
>   [009559a3] XGBoost v1.1.1
>   [a5390f91] ZipFile v0.9.2

So no, I don't have it. Why is it working then? The file where I had this issue explicitly has `using MultivariateStats` and `using MLJ`, so I don't think these are sufficient. Could it be MLJModels? I have imported it for a different project while waiting on news about this issue.

**Comment by ablaom** [comment]
> So no, I don't have it. Why is it working then? 

Ah. Because you are using an old version of MLJ (probably the one from the tutorials), which I had not anticipated. 

Let me know if you have persistent issues
