### ISSUE TITLE
Package it as so to work with Pkg.clone

### ISSUE THREAD

**Issue by vollmersj** [alan-turing-institute/MLJ.jl#7]

**Comment by vollmersj** [comment]
https://docs.julialang.org/en/v0.6.0/man ual/packages/#Creating-a-new-Package-1

**Comment by gbohner** [comment]
Doesn't seem to install dependencies with Pkg.clone(), maybe edit the REQUIRES file?

**Comment by ablaom** [comment]
Closing this issue. 

MLJ is now 0.7/1.0 compatible and `] add https://github.com/alan-turing-institute/MLJ.jl.git` works.
