### ISSUE TITLE
MLJDecisionTreeInterface.jl

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#700]
**Describe the bug**
My test suites started failing with this error message:

```julia
Got exception outside of a @test
  LoadError: LoadError: ArgumentError: Package MLJDecisionTreeInterface not found in current path:
  - Run `import Pkg; Pkg.add("MLJDecisionTreeInterface")` to install the MLJDecisionTreeInterface package.
```

I only depend on MLJModelInterface.jl, did something change recently? Why builds are failing without a new minor release?

**Comment by ablaom** [comment]
@juliohm Thanks for reporting. 

Yes there was a change on Friday. The DecisionTree.jl implementation of the model interface in MLJModelInterface.jl  has moved from MLJModels.jl to the current package. Formerly this implementation code was Requires-loaded when you imported DecisionTree.jl. To resolve your issue I expect that where you had DecisionTree.jl in an environment (as [deps] or [extras]) you now need this package instead (or in addition if you explicitly reference DecisionTree.jl objects).

I'm not sure I understand how you encountered the problem if MLJModels.jl is not also a dependency of your package/test. Maybe you can provide some more context.

**Comment by juliohm** [comment]
Thank you @ablaom , the issue was in a test suite where MLJModels.jl was in [extras] along with DecisionTree.jl. I fixed the Project.toml accordingly.

**Comment by ablaom** [comment]
But technically, MLJModels should have made a made a minor release, yes?

**Comment by DilumAluthge** [comment]
The issue may have arisen if the package in question did not have a compat entry for MLJModels.

We recommend that all test dependencies have compat entries, just like regular dependencies. However, AutoMerge does not enforce this for test dependencies; we only enforce it for regular dependencies.

**Comment by juliohm** [comment]
I didn't know it was possible to add a compat entry for a test dependency. The compat entry goes side by side with the compat entries of the actual dependencies?

**Comment by DilumAluthge** [comment]
Yep!

**Comment by ablaom** [comment]
@DilumAluthge Are you absolutely sure [compat] entries for [extras] have any effect?

**Comment by DilumAluthge** [comment]
I can't find it in the documentation, but it is definitely true.
