### ISSUE TITLE
Just a doc typo

### ISSUE THREAD

**Issue by Leonardbcm** [alan-turing-institute/MLJ.jl#704]
Hi everyone

https://alan-turing-institute.github.io/MLJ.jl/dev/internals/#fit!-and-predict/transform-1
The first argument is called "machine" whereas it seems to be referenced as "mach" in the method body.

**Comment by ablaom** [comment]
Thanks.

https://github.com/alan-turing-institute/MLJ.jl/pull/706/commits/31d30e30bd9a7d832e9e1c32b06ce2151642cb5a
