### ISSUE TITLE
Saving snapshots of a TunedModel as it trains

### ISSUE THREAD

**Issue by Leonardbcm** [alan-turing-institute/MLJ.jl#708]
Hi everyone,
I have been using TunedModel objects to perform hyper-parameter optimization. TunedModel are sometimes long to train if the grid is large. I would like to be able to inspect the training results as the object trains, to check the results on the parti of the grid that has been explored and have partial results.

The easiest way to implement this as I see it would be to define a serialization function for the TunedModel report and to save it somewhere on the disk. The user can reload it with another Julia version and reload it.

Other alternative would be to put all training advancement in a log file, but it is harder to extract data from a log.

Thanks for your support,

Leonard.

**Comment by ablaom** [comment]
Thanks for the suggestion. 

My plan is to address this with a general wrapper for iterative models: https://github.com/alan-turing-institute/MLJ.jl/issues/139 . So closing, as tracked.
