### ISSUE TITLE
All CV scores in a TunedModel

### ISSUE THREAD

**Issue by Leonardbcm** [alan-turing-institute/MLJ.jl#709]
Hi everyone,
I have been using TunedModel for hyper-parameter optimization. The `resampling` parameter allows me to perform cross-validation to have a more robust error value for my hyper-parameter configuration. 

However, when the training is finished, I can't access the Cross Validation results, only the average is available in the `report`. I would like to be able to inspect all the CV results.

Putting all CV results in the `history` section of the `report` seems to be the easiest way to achieve this. 

This remark holds true for other type of resampling parameters involving multiple training and evaluating.
Thanks for your support,

Leonard.

**Comment by ablaom** [comment]
What version of MLJTuning is in your manifest? I believe you should have access through the `per_fold` property of each history entry. From the MLJTuning readme:

![Screen Shot 2020-11-19 at 10 32 04 AM](https://user-images.githubusercontent.com/30517088/99590774-ae9ad680-2a52-11eb-9ce6-54fa3c08c500.png)

**Comment by Leonardbcm** [comment]
That is correct, I was still in version 0.4.2 of MLJTuning. 
After an update, I am able to access the `per_fold` property of an history entry.

Thanks for your help.
