### ISSUE TITLE
Unsupported const declaration

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#715]
**Describe the bug**
Today my test suites started failing with the following error message:

```julia
Got exception outside of a @test
  LoadError: syntax: unsupported `const` declaration on local variable around /home/juliohm/.julia/packages/MLJModels/GyILf/src/loading.jl:84
```

What can I do to fix this issue?

**Comment by DilumAluthge** [comment]
Can you post an MWE?

**Comment by DilumAluthge** [comment]
Also, it sounds like MLJModels.jl is a test dependency of your package.

Do you have a `[compat]` entry for `MLJModels`?

Try adding this line to the `[compat]` section of your package's `/Project.toml` file:
```toml
MLJModels = "0.12"
```

If your package also has a `/test/Project.toml` file, then you should also adding the same line to the `[compat]` section of `/test/Project.toml`. (If you don't have a `/test/Project.toml` file, just disregard this step.)

**Comment by juliohm** [comment]
Hi @DilumAluthge , I don't understand how adding a compat version addresses the root of the issue. MLJModels is only loaded for tests as you mentioned and I don't care which version is loaded. The fact that it is breaking right now seems unrelated to a compat issue. Can you please elaborate?

What has changed that triggered this const error? It was certainly not on my side as I am not touching any of the MLJ-related features in a while.

**Comment by DilumAluthge** [comment]
> Hi @DilumAluthge , I don't understand how adding a compat version addresses the root of the issue. MLJModels is only loaded for tests as you mentioned and I don't care which version is loaded. The fact that it is breaking right now seems unrelated to a compat issue. Can you please elaborate?

MLJModels.jl recently made a breaking release: v0.13.0. Because this is a breaking release, they are allowed to make breaking changes.

If you don't want your test suite to break, you should have `[compat]` entries for all of your test dependencies.

**Comment by DilumAluthge** [comment]
> What has changed that triggered this const error? It was certainly not on my side as I am not touching any of the MLJ-related features in a while.

I have a fix ready. I'll make a pull request soon.

But again, this change was made in MLJModels v0.13.0, so it is perfectly valid to make breaking changes.

**Comment by DilumAluthge** [comment]
To elaborate: between MLJModels v0.12.11 and MLJModels v0.13.0, there was a breaking change made to the `MLJModels.@load` macro.

This is legal because of the Julia/Pkg.jl interpretation of semver: if a package's version number is strictly less than 1.0.0, then a version bump of the form `0.x.y` to `0.(x+1).0` is breaking.

My guess is that, in your package's test suite, you use the `MLJModels.@load` macro somewhere, correct? So then your test suite is using the public API of `MLJModels`.

**Comment by DilumAluthge** [comment]
It's the same as if you used some dependency `Foo.jl` in your package's code. If you don't have a `[compat]` entry for `Foo` in your `Project.toml` file, then if `Foo.jl` makes a breaking change, there is a risk that it breaks your package.

The same logic applies for test dependencies. If your tests depend on the public API of `Bar.jl`, and you don't have a `[compat]` entry for `Bar`, then if `Bar.jl` makes a breaking change, there is a risk that it breaks your tests.

**Comment by DilumAluthge** [comment]
Anyway, that's all rather moot. This will be fixed by https://github.com/alan-turing-institute/MLJModels.jl/pull/344

After https://github.com/alan-turing-institute/MLJModels.jl/pull/344 is merged, you'll need to make some changes to your test suite.

Specificially, if you use the `MLJModels.@load` macro inside a `@testset`, you'll need to add `scope=:local`.

For example, if your code currently looks like this:
```julia
@testset "My testset name" begin
    @load DecisionTreeClassifier
end
```

You'll need to change it to look like this:
```julia
@testset "My testset name" begin
    @load DecisionTreeClassifier scope=:local
end
```

**Comment by juliohm** [comment]
I understand how semver works and the related issues. I am just wondering how the `@load` macro changed so dramatically to cause an error? What changed? Aren't we supposed to load models with `@load Foo` anymore?

**Comment by juliohm** [comment]
I see. The scope issue beating everyone again. :/

To be honest, I really wish MLJ didn't use a macro to load models. In an ideal world we would simply have a curated list of "best" "well-tested" models loaded by default in a package like `MLJModels.jl` for example. No need to mess around with loading code that is not installed or forcing users to go the through the path of the package manager everytime they need a new model.

**Comment by DilumAluthge** [comment]
> I understand how semver works and the related issues. I am just wondering how the `@load` macro changed so dramatically to cause an error? What changed? Aren't we supposed to load models with `@load Foo` anymore?

Previously, the `@load` macro would call `eval` inside of the macro. This is a major red flag. In MLJModels v0.13.0, the `@load` macro was refactored to no longer call `eval` inside of the macro.

This works perfectly fine if you are calling `@load` in global scope, which is the usual usage of `@load`.

However, in your case, I am guessing that you are calling `@load` inside local scope. Julia currently does not allow us to use the `const` keyword inside local scope, which is why you are seeing this error.

> Aren't we supposed to load models with `@load Foo` anymore?

You can definitely continue to load models with `@load Foo`. The only change is this: if you are calling the `@load` macro inside local scope, simply add the `scope=:local` keyword.

So, inside global scope:
```julia
@load Foo
```

And inside local scope:
```julia
@load Foo scope=:local
```

**Comment by juliohm** [comment]
We commented almost at the same time. My real wish is to remove the `@load` macro, and have a curated list of best models that is evolved over time. No one really needs to load three KNN implementations, 4 decision tree implementations, we just need the best out there.

**Comment by DilumAluthge** [comment]
In a lot of my code, I don't use the `@load` macro - I just access the model directly.

E.g. for decision trees, I can do this:
```julia
import MLJDecisionTreeInterface
const DecisionTreeClassifier = MLJDecisionTreeInterface.DecisionTreeClassifier
```

So you don't need to use the `@load` macro if you don't want to!

I think some people find the `@load` macro convenient, so we will continue to support it.

But you can use all of MLJ without ever once using the `@load` macro.

**Comment by juliohm** [comment]
I think the problem is discovery and user-experience. Right now a new user coming from sklearn or any other monolithic project will feel the pain of resorting to the package manager anytime a new model is desired. I have to search whatever package has the model, install it, fight with compat issues, do a lot of annoying environment management, just to try a new model on my dataset.

Ideally one would just do:

```julia
using MLJ

# now we have a curated list of models
# no need to install a bunch of packages
m1 = DecisionTreeClassifier()
m2 = KNN()
m3 = ...
```

**Comment by DilumAluthge** [comment]
> I think the problem is discovery and user-experience. Right now a new user coming from sklearn or any other monolithic project will feel the pain of resorting to the package manager anytime a new model is desired. I have to search whatever package has the model, install it, fight with compat issues, do a lot of annoying environment management, just to try a new model on my dataset.

That's what the `@load` macro does, right?

**Comment by DilumAluthge** [comment]
I think it's nice that we have multiple backends in MLJ. For example, we have multiple packages for decision trees - it's not immediately obvious to me that a single decision tree package is the best one, so why not support them all?

**Comment by juliohm** [comment]
> That's what the `@load` macro does, right?

As far as I understand the macro will just throw an error if the `DecisionTree.jl` package is not installed in the environment. So the user is forced to enter package mode and stop what he was trying to do.

**Comment by DilumAluthge** [comment]
I think that it is inevitable that someone that uses Julia will need to interact with the package manager. That's why it's so important that the package manager have a good user interface.

The maintainers of Pkg.jl always welcome new pull requests to improve the Pkg user experience.

**Comment by juliohm** [comment]
I mean, why use macros? I don't think this is a good use case. It causes more harm than help. Every time I try a new model, the model package is outdated compared to MLJ. So this decoupling is causing more harm than actually helping the end user.

If a curated list is made a dependency of MLJ, we will never encounter compatiblity issues.

**Comment by DilumAluthge** [comment]
> If a curated list is made a dependency of MLJ, we will never encounter compatiblity issues.

You could definitely make this package yourself.

E.g. make `MLJCuratedModels.jl`, and include all the models that you like, and `export` them.

So then a user only needs to do this:

Run this code one time:
```julia
using Pkg
Pkg.add("MLJCuratedModels")
```

And then put this code in their package:
```julia
using MLJCuratedModels
m1 = DecisionTreeClassifier()
m2 = KNN()
m3 = ...
```

Nothing about this needs to be maintained by MLJ. Anyone can make `MLJCuratedModels.jl`.

**Comment by DilumAluthge** [comment]
> If a curated list is made a dependency of MLJ, we will never encounter compatiblity issues.

But then every user that installs MLJ ends up installing a massive stack of dependencies, with binary dependencies, artifacts, etc. And they also end up with their hands tied as far as compatibility - if they want to install some small Julia package Foo.jl, but the version of Foo.jl that they need is not compatible with one of the many dependencies in the massive stack of dependencies, then they are out of luck.

So:
- `MLJCuratedModels.jl` - a great idea; anyone could make this package; doesn't need to be officially maintained by the MLJ team or the Alan Turing Institute.
- Making MLJ depend on `MLJCuratedModels.jl` - bad idea, makes MLJ.jl a massive slow package with many dependencies.

**Comment by juliohm** [comment]
I think you are missing the point I am trying to make here. The audience I have in mind are beginners coming to Julia willing to try ML models. Does it make sense? I am not talking about myself, I am talking about my interns who come to me and say: "Hey Julio, why is it so difficult to try a couple of models in MLJ? Why can't we just do something like `import sklearn` and be happy with a big list of well-tested models?"

**Comment by DilumAluthge** [comment]
Sure, so for that audience, we can definitely make `MLJCuratedModels.jl`.

Presumably this:
```julia
import MLJ
import MLJCuratedModels
```

Is just as easy as this:
```python
import sklearn
```

**Comment by juliohm** [comment]
So making this curated list the *default* recommend method is the point here. It doesn't matter who maintains the list, but promoting this `@load` macro is just harmful to the experience in my opinion.

Anyways, I am just sharing my concerns as a end-user, and as an experienced user who is still bitten by updates like this one that is crashing an old test suite. I am sure the maintainers of the project have already evaluated these options.

**Comment by DilumAluthge** [comment]
`MLJCuratedModels.jl` is really easy to make. Here is what the file `src/MLJCuratedModels.jl` looks like:
```julia
module MLJCuratedModels

export DecisionTreeClassifier
# and you have `export` statements for all of the models in your curated list

import MLJDecisionTreeInterface
const DecisionTreeClassifier = MLJDecisionTreeInterface.DecisionTreeClassifier
# repeat these two lines for all of the models in your curated list

end # end module MLJCuratedModels
```

**Comment by juliohm** [comment]
Yes, I know how to make a curated list.

**Comment by DilumAluthge** [comment]
> crashing an old test suite

I just want to be perfectly clear here: the reason your test suite crashed is because you did not have `[compat]` entries for all of the test dependencies that your test suite uses. Not because of anything else that we are discussing here. If you had a `[compat]` entry for MLJModels, then a breaking release of MLJModels would not have broken your test suite.

We strongly recommend that all direct dependencies have `[compat]` entries. In fact, this is required if you want automerge.

We also strongly recommend that all test dependencies have `[compat]` entries. However, we don't require this for automerge.

**Comment by juliohm** [comment]
I don't think this is just a matter of compat entries. It is a matter of a convoluted macro used in a context that makes things more complicated than they should be.

**Comment by DilumAluthge** [comment]
> So making this curated list the _default_ recommend method is the point here.

By "default recommended method", do you mean that we would promote this curated list in MLJ documentation?

I would certainly support this idea, at least in documentation for beginners.

**Comment by DilumAluthge** [comment]
There are two separate issues here:
1. Your test suite broken because you did not have a `[compat]` entry for MLJModels.
2. Should we promote and encourage the use of the `@load` macro or a curated list?

These are two separate issues; let's not get them confused.

The discussion in this issue is really about point 2, I think, right? That's your main concern - that instead of the `@load` macro, we should promote a single curated list of models for MLJ beginners.

**Comment by juliohm** [comment]
Yes, the maintainers of MLJ have all the up-to-date knowledge to maintain this list, and to release versions together with the project. Anyone that tries to do this as a separate effort will have more trouble than necessary. A curated list should be part of the release process otherwise it has not much value.

**Comment by DilumAluthge** [comment]
I think it could be a good idea to have a single curated list that we encourage MLJ beginners to use in documentation.

We just need to make sure that in documentation for **advanced** MLJ users, we present alternative options.

**Comment by DilumAluthge** [comment]
> Yes, the maintainers of MLJ have all the up-to-date knowledge to maintain this list, and to release versions together with the project.

This isn't really necessary, is it? E.g. if a new breaking release of MLJ comes out, and not all the models in `MLJCuratedModels.jl` are compatible with the new MLJ, that's totally fine. Users that need `MLJCuratedModels.jl` can just use an old version of MLJ.

**Comment by juliohm** [comment]
Makes sense. `@load` seems like an exceptional use case rather than the canonical use case. I doubt any ML pipeline out there nowadays will concentrate on a single or two models. People will be interested in trying a bunch of models, so they don't care about extra dependencies, hence curated list.

**Comment by DilumAluthge** [comment]
@juliohm Want to make a new issue (on either the `MLJ.jl` repo or the `MLJModels.jl` repo) to discuss a curated model list that is maintained by the MLJ maintainers? I'll chime in there as well. That way we can see if Anthony, Thibaut, etc. are able to spend some of their time maintaining such a list.

(This issue will be auto-closed when https://github.com/alan-turing-institute/MLJModels.jl/pull/344 is merged, so we should move discussion to an issue specific for this topic.)

**Comment by DilumAluthge** [comment]
Although, @juliohm can you explain a little bit more why you feel that this curated list needs to be maintained by the MLJ maintainers?

I.e. what are the reasons why a third-party couldn't register `CuratedMachineLearning.jl` in the General registry, and maintain it themselves?

**Comment by juliohm** [comment]
If the API changes, the model packages need to change as well right? So anyone maintaining a curated list would need to be aware of API changes in order to update the list. Sometimes a model is not updated yet, and the maintainer of the list isn't aware. But I understand your point that everything is possible. I am just saying it is natural for the MLJ maintainers to maintain such a list as opposed to defer this to someone else not closely involved with the project.

**Comment by DilumAluthge** [comment]
I see. My biggest concern is that Anthony, Thibaut, and the other MLJ maintainers are already very busy, and I just don't know if they have the time to do this.

**Comment by juliohm** [comment]
Opened the issue here: #716

**Comment by juliohm** [comment]
By the way, I just tried adding `@load DecisionTreeClassifier scope=:local` inside the test suite and a new error is shown:

```julia
Got exception outside of a @test
  LoadError: LoadError: ArgumentError: Invalid @load syntax.
   Sample usage: @load PCA pkg="MultivariateStats" verbosity=1
```

**Comment by DilumAluthge** [comment]
Yeah, that's because https://github.com/alan-turing-institute/MLJModels.jl/pull/344 hasn't been merged yet.

We need:
1. https://github.com/alan-turing-institute/MLJModels.jl/pull/344 to be merged
2. A new release of MLJModels.jl to be tagged

**Comment by ablaom** [comment]
@juliohm  https://github.com/JuliaRegistries/General/pull/25523
