### ISSUE TITLE
DecisionTreeClassifier does not appear to be a Supervised model.

### ISSUE THREAD

**Issue by rikhuijzer** [alan-turing-institute/MLJ.jl#741]
MLJ 1.6 appears to have broken loading of random forest models in Julia 1.6.

To reproduce, install all the required dependencies and do
```
pkg> add MLJ@0.16

julia> using MLJ

julia> DecisionTree = @load DecisionTreeClassifier verbosity=0;

julia> forest_model = EnsembleModel(atom=DecisionTree, n=10);
ERROR: MLJDecisionTreeInterface.DecisionTreeClassifier does not appear to be a Supervised model.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] EnsembleModel(; args::Base.Iterators.Pairs{Symbol, Any, Tuple{Symbol, Symbol}, NamedTuple{(:atom, :n), Tuple{DataType, Int64}}})
   @ MLJ ~/.julia/packages/MLJ/xgrEQ/src/ensembles.jl:370
 [3] top-level scope
   @ REPL[4]:1
```
On the other hand, doing exactly the same with MLJ@0.15 works. This can be validated by restarting Julia and running the same code again after running
```
pkg> add MLJ@0.15
```

**Comment by ablaom** [comment]
Thanks for reporting, appreciate it!

There was a change in the behaviour of @load which you seem to have missed.  It now returns are *type* instead of an instance. So, to resolve your issue do this:

```julia
DecisionTree = @load DecisionTreeClassifier verbosity=0;   # binds type to `DecisionTree`
tree = DecisionTree()  # construct default instance
forest_model = EnsembleModel(atom=DecisionTree, n=10);
```

More at [release notes](https://github.com/alan-turing-institute/MLJ.jl/releases/tag/v0.16.0)

**Comment by rikhuijzer** [comment]
Ah, yes, I should have checked! Thanks!
