### ISSUE TITLE
Load issue

### ISSUE THREAD

**Issue by azev77** [alan-turing-institute/MLJ.jl#752]
Previously the following worked to automatically load all models: 
```julia
for (i, model) in enumerate(models())
    load(model.name, pkg=model.package_name, verbosity=0) 
end
```
Now I get an error message: 
```julia
ERROR: The `load` function is no longer supported. Use the `@load` macro instead, as in `@load RandomForestRegressor pkg = DecisionTree`.
```

Then I try:
```julia
for (i, model) in enumerate(models())
    @load model.name pkg = model.package_name
end

ERROR: ArgumentError: There is no model named "model.name" in the registry. 
 Run `models()` to view all registered models.
```

**Comment by ablaom** [comment]
What you want to do is use interpolation, as in 

```julia
name = "PCA"
@load $name
```

But `@load` does not support this yet (https://github.com/alan-turing-institute/MLJModels.jl/issues/368). However there is a workaround:

```julia
name = "PCA"
@eval @load $name
```

Also, note that`@load` no longer returns an instance, only returns a *type*.  See (https://alan-turing-institute.github.io/MLJ.jl/dev/loading_model_code/) for details.  The new `@load` is much faster, more robust, has no unexpected side-effects, and should work in any scope (eg, in a function within a module within a package).

So the following works for me:

```julia
using Pkg
Pkg.activate(temp=true)
Pkg.add("MLJ")

using MLJ
model_types = []
for model in models()
    T = @eval @load $(model.name) pkg=$(model.package_name) add=true
    push!(model_types, T)
end
model_instances = map(T -> T(), model_types)
```

However, note `@load` no longer returns an instance, only returns a *type*. See (https://alan-turing-institute.github.io/MLJ.jl/dev/loading_model_code/) for details.
