### ISSUE TITLE
Evaluate with acceleration is only working on a single worker

### ISSUE THREAD

**Issue by f0lie** [alan-turing-institute/MLJ.jl#754]
**Describe the bug**
I used `default_resource(CPUProcesses(8))` and the output only shows that everything is running on a single worker.

**To Reproduce**

```julia
Tree = @load DecisionTreeClassifier pkg=DecisionTree
tree = Tree()
tree_mach = machine(tree, X_discrete, y)

cross_valid = CV(nfolds=5, shuffle=true, rng=1234)
default_resource(CPUProcesses(8))

evaluate!(tree_mach, resampling=cross_valid,
                     measure=macro_f1score,
                     operation=predict_mode,
                     verbosity=2))

┌ Info: Distributing evaluations among 1 workers.
└ @ MLJBase /home/f0lie/.julia/packages/MLJBase/pCCd7/src/resampling.jl:889
┌ Info: Training Machine{DecisionTreeClassifier,…} @966.
└ @ MLJBase /home/f0lie/.julia/packages/MLJBase/pCCd7/src/machines.jl:342
┌ Info: Training Machine{DecisionTreeClassifier,…} @966.
└ @ MLJBase /home/f0lie/.julia/packages/MLJBase/pCCd7/src/machines.jl:342
┌ Info: Training Machine{DecisionTreeClassifier,…} @966.
└ @ MLJBase /home/f0lie/.julia/packages/MLJBase/pCCd7/src/machines.jl:342
Evaluating over 5 folds:  20%[=====>                   ]  ETA: 0:00:07┌ Info: Training Machine{DecisionTreeClassifier,…} @966.
└ @ MLJBase /home/f0lie/.julia/packages/MLJBase/pCCd7/src/machines.jl:342
┌ Info: Training Machine{DecisionTreeClassifier,…} @966.
└ @ MLJBase /home/f0lie/.julia/packages/MLJBase/pCCd7/src/machines.j342  
Evaluating over 5 folds: 100%[=========================] Time: 0:00:01

```

**Expected behavior**
While it doesn't crash, it seems like it's suppose to be working across several workers. I try using CPUThreads() and doesn't change things. Also, I tried to using `Distributed` and manually add processes with `addproc` and that just crashed the code. Says that it's missing a key.

I think it has something to do with the setup of workers. I am running on Juypter Notebooks if that makes a difference.

**Versions**
Latest and greatest.

</details>

**Comment by f0lie** [comment]
Figured out out, you need to start things with `julia -p n`. If you are running a notebook, then you need to go to the notebook kernel json and add `-p n` to the args list.

https://discourse.julialang.org/t/enable-multiple-cores-for-jupyter-lab/18658/7

**Comment by ablaom** [comment]
Thanks for reporting in any case.

**Comment by f0lie** [comment]
The multiprocessing documentation could spell this out saying that you need to run `julia -p 5 <script` to use several processes. Right now it's pretty bare.

I am not sure if this is the place to raise this problem but it takes a massive amount of memory to run things. It seems like julia is copying the models between the processes so a decently sized model becomes massive with enough processes. Maybe this is just the nature of machine learning but this does put a large stop on scaling things.

**Comment by ablaom** [comment]
Do you notice any difference in memory use if you add `cache=false` to the machine constructor, as in 

```julia
X, y = @load_iris
model = (@load NeuralNetworkClassifier)()
mach = machine(model, X, y, cache=false) |> fit!
```

?
