### ISSUE TITLE
Add facility to quickly define a model stack with meta-learner

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#76]

**Comment by ablaom** [comment]
Here are some suggestions for a canned version of Wolpert stacking, implemented by generalizing the learning network in [this tutorial](https://alan-turing-institute.github.io/DataScienceTutorials.jl/) which is then "exported" as a new model type(s); see also [this workshop notebook](https://github.com/ablaom/MachineLearningInJulia2020/blob/master/wow.ipynb).


### Avoiding macros

Following discussion [here](https://github.com/alan-turing-institute/MLJ.jl/issues/594) and elsewhere, we should avoid using macros. Rather than defining a custom type each time, we use type parameters to give us the flexibility we need. Previously, there were difficulties having a variable number of component models in a composite, but I believe these have now [been mitigated](https://github.com/alan-turing-institute/MLJBase.jl/pull/553). As an example of the kind of struct definition and constructor I have in mind, see [this `Averager`example](https://github.com/alan-turing-institute/MLJModelInterface.jl/pull/97) for averaging the predictions of multiple regressors of different type.


### Types

I expect we need two types `ProbablisticStack{base_model_names}` and `DeterministicStack{base_model_names}`, where `base_model_names` is a tuple of symbols recording the user-specified names of the base-model "fields" (actually properties); we have a single user constructor, however, called  `Stack(...)` (or `stack(...)`?). This follows that pattern for `TunedModel`, `EnsembleModel`,  and `IteratedModel`.


### Scope

#### The adjudicator

I think the only restriction needed on the adjudicator is `input_scitype(Adjudicator) <: Table(Continuous)`. It can be `Probablistic` or `Deterministic`, and `Stack` calls the appropriate `ProbabilisticStack` or `DeterministicStack` accordingly.

#### Base learners

For either `ProbabilisticStack` or `DeterministicStack` I suggest restricting the base learners to probabilistic predictors (classifiers or regressors) and deterministic regressors, at least to start with. (I haven't looked into what other frameworks such as `vecstack` do.) Specifically, we restrict to types `M`, as tabulated below: 

`Probabilistic`/`Deterministic` | `target_scitype(M) <: _`        | pre-adjudicator transformation of prediction
--------------------------------|---------------------------------|---------------------------------------
`Deterministic`                 | `AbstractArray{<:Continuous}`   | none
`Probabilistic`                 | `AbstractArray{<:Continuous}`   | `predict_mean` or `predict_median` (1)
`Probablistic`                  | `AbstractArray{<:Finite}`       | `yhat -> pdf(yhat, levels(yhat))`   (2)


 - (1) Determined by a hyper-parameter `continuous_operation`, default `predict_mean`
 - (2) For this use of `pdf`, see [this section](https://alan-turing-institute.github.io/MLJ.jl/dev/getting_started/#Fit-and-predict) of the MLJ manual. Of course in this case we get multiple columns passed to the adjudicator.
   
More advanced, but less useful I would guess, would be to add deterministic classifiers:

`Probabilistic`/`Deterministic` | `target_scitype(M) <: _`        | pre-adjudicator transformation
--------------------------------|---------------------------------|--------------------------------------------
`Deterministic`                 | `AbstractArray{<:Finite}`       | apply `transform` of a `ContinuousEncoder` 

Do `?ContinuousEncoder` for details. 

```

@olivierlabayle Can you think of any other design decisions that need clarifying?

**Comment by olivierlabayle** [comment]
Thanks for the detailed description. The split between `ProbablisticStack` and `DeterministicStack` types seems quite natural. 

My understanding is that the `pre_judge_transform` function should be dispatched on something like (`ModelType`, `target_scitype(M)`)? But `target_scitype(M)` is itself a type, I don't think I've seen this pattern before, can you point to some doc?

**Comment by ablaom** [comment]
Do, for example

```julia
pre_judge_transform(yhat, ::Type{<:Probabilistic}, ::Type{<:AbstractArray{<:Finite}) = 
    pdf(yhat, levels(yhat))
```

But this assumes `yhat` is regular data, so you must additionally add one definition to overload for nodes:

```julia
pre_judge_transform(yhat::Node, args...) = node(yhat->pre_judge_transform(yhat, args...), yhat)
```

@olivierlabayle Does this answer your question?

**Comment by ablaom** [comment]
@oleskiewicz see my edit to original design comment.

**Comment by olivierlabayle** [comment]
Yes perfect, I didn't know the `::Type{}` syntax.
