### ISSUE TITLE
Migrate packages to JuliaAI

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#765]
Eventually it would make sense to move the whole MLJ ecosystem to [JuliaAI](https://github.com/JuliaAI) but already very helpful and not too disruptive would be to move the "interface only" packages listed below. These are currently difficult for developers to find, unless they have them bookmarked. 

**edit** Here are the steps to move a repo:

- transfer ownership by visiting Settings of the source repo
- make a PR to General.jl to update the url of the package
- update any model load paths, like `MLJBase.package_url(::Type{<:Stack}) =
    "https://github.com/alan-turing-institute/MLJBase.jl"`
- if there is auto-generated docs, update the deployment url in docs/make.jl
- update README badges to point to the correct urls

@sjvollmer I have invited you to JuliaAI. If you accept, you will be able to do step (i) (and will be the only one able to do so unless Turing will grant someone else access). An alternative would be for Turing to give Mose or me (temporary) access. 

@giordano Do you already have privileges to transfer repos owned by alan-turing-institute?

Transferred:

- [x] MLJClusteringInterface = "d354fa79-ed1c-40d4-88ef-b8c7bd1568af"
- [x] MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
- [x] MLJGLMInterface = "caf8df21-4939-456d-ac9c-5fefbfb04c0c"
- [x] MLJLIBSVMInterface = "61c7150f-6c77-4bb1-949c-13197eac2a52"
- [x] MLJMultivariateStatsInterface = "1b6a4a23-ba22-4f51-9698-8599985d3728"
- [x] MLJNaiveBayesInterface = "33e4bacb-b9e2-458e-9a13-5d9a90b235fa"
- [x] MLJScikitLearnInterface = "5ae90465-5518-4432-b9d2-8a1def2f0cab"
- [x] MLJXGBoostInterface = "54119dfa-1dab-4055-a167-80440f4f7a91"
- [x] NearestNeighborModels = "636a865e-7cf4-491e-846c-de09b730eb36" (+ gh pages for manual)
- [x] MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692" (+ gh pages for manual)

PR to General has been posted:

- [x] MLJClusteringInterface = "d354fa79-ed1c-40d4-88ef-b8c7bd1568af"
- [x] MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
- [x] MLJGLMInterface = "caf8df21-4939-456d-ac9c-5fefbfb04c0c"
- [x] MLJLIBSVMInterface = "61c7150f-6c77-4bb1-949c-13197eac2a52"
- [x] MLJMultivariateStatsInterface = "1b6a4a23-ba22-4f51-9698-8599985d3728"
- [x] MLJScikitLearnInterface = "5ae90465-5518-4432-b9d2-8a1def2f0cab"
- [x] MLJXGBoostInterface = "54119dfa-1dab-4055-a167-80440f4f7a91"
- [x] NearestNeighborModels = "636a865e-7cf4-491e-846c-de09b730eb36" (+ gh pages for manual)
- [x] MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692" (+ gh pages for manual)

other stuff sorted:

- [x] MLJClusteringInterface = "d354fa79-ed1c-40d4-88ef-b8c7bd1568af"
- [x] MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
- [x] MLJGLMInterface = "caf8df21-4939-456d-ac9c-5fefbfb04c0c"
- [x] MLJLIBSVMInterface = "61c7150f-6c77-4bb1-949c-13197eac2a52"
- [x] MLJMultivariateStatsInterface = "1b6a4a23-ba22-4f51-9698-8599985d3728"
- [x] MLJNaiveBayesInterface = "33e4bacb-b9e2-458e-9a13-5d9a90b235fa"
- [x] MLJScikitLearnInterface = "5ae90465-5518-4432-b9d2-8a1def2f0cab"
- [x] MLJXGBoostInterface = "54119dfa-1dab-4055-a167-80440f4f7a91"
- [x] NearestNeighborModels = "636a865e-7cf4-491e-846c-de09b730eb36" (+ gh pages for manual)
- [x] MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692" (+ gh pages for manual)

**Comment by giordano** [comment]
> @giordano Do you already have privileges to transfer repos owned by alan-turing-institute?

I'd need to be admin of a repository to be able to transfer it to another organisation, I don't think I'm admin of any of them

**Comment by ablaom** [comment]
Here are the rest:

- [ ] MLJBase.jl (and gh pages for manual)
- [ ] MLJScientificTypes.jl (and gh pages for manual)
- [ ] MLJTuning.jl
- [ ] MLJ.jl (and gh  pages for manual)
- [ ] MLJModelInterface.jl
- [ ] DataScienceTutorials.jl (and gh  pages for manual)
- [ ] MLJModels.jl
- [ ] MLJLinearModels.jl
- [ ] MLJGaussianProcessesInterface.jl
- [ ] MLJRegistry.jl
- [ ] ScientficTypes.jl
- [ ] MLJTime
- [ ] MLJSnipplets (private)
- [ ] MLJ-composebility (private)
- [ ] MLJRegistry (could be archived and left in place; only used by very old versions of mlj
- [ ] StatisticalTraits.jl


Note: MLJFlux lives at Flux org, which provides GPU testing.

**Comment by ablaom** [comment]
@DilumAluthge When transferring ownership to a new organization, what steps should we take, typically,  to handle the documentation, when this is hosted by the repo's github pages?

For example, in the case of [MLJScientificTypes](https://discourse.julialang.org/t/pros-and-cons-of-using-flux-directly-over-using-mlj-mljflux/59756), I guess we just update the make.jl [deployment url]([MLJScientificTypes](https://discourse.julialang.org/t/pros-and-cons-of-using-flux-directly-over-using-mlj-mljflux/59756). Are there any unexpected consequences of doing this we should worry about? Or some other step I'm missing?

cc @vollmersj

**Comment by DilumAluthge** [comment]
Updating the `make.jl` file should be sufficient, actually.

**Comment by DilumAluthge** [comment]
All the docs themselves are in the `gh-pages` branch, so when you transfer the repo, the docs should automatically show up at the new URL.

**Comment by DilumAluthge** [comment]
In addition to updating make.jl, you'll need to update the URLs for the "docs" badges in the README.

**Comment by ablaom** [comment]
Thanks!

**Comment by zsz00** [comment]
Why create a new organization? 
Why is it called JuliaAI? 
Why not move to the existing JuliaML?

**Comment by DilumAluthge** [comment]
Could we move the MLJRegistry.jl repo (https://github.com/alan-turing-institute/MLJRegistry.jl) to the `JuliaAI` organization?

I know that it is archived, but I think that it still makes sense for MLJRegistry.jl to live in the same place as MLJModels.jl and MLJBase.jl.

cc: @ablaom @vollmersj @sjvollmer

**Comment by ablaom** [comment]
This is all done except MLJ itself. So closing in favour of separate issue.

**Comment by DilumAluthge** [comment]
FYI, https://github.com/alan-turing-institute/MLJRegistry.jl has not been migrated - would be good to do so, even though it is archived.
