### ISSUE TITLE
Error for the iris dataset example in Getting Started page

### ISSUE THREAD

**Issue by AlexandruMoraru310** [alan-turing-institute/MLJ.jl#768]
**Describe the bug**

For the iris dataset example on Getting Started page I got error when I ran the `evaluate` function.

**To Reproduce**

`evaluate(tree, X, y, resampling=CV(shuffle=true), measure=cross_entropy, verbosity=0)`

**Expected behavior**
Estimate the performance.

**Additional context**
I created a machine and then I gave it as parameter to the `evaluate!` (not `evaluate`) function:
```
mach = machine(tree, X, y)
evaluate!(mach, resampling=CV(shuffle=true), measure=cross_entropy, verbosity=0)
```
and it worked as expected!

**Versions**
<details>

julia version = 1.6.0
MLJ version = 0.16.1

</details>

**Comment by AlexandruMoraru310** [comment]
I rechecked and it seems that the code from tutorial works, but for some reason VSCode highlights it as "possible method call error" so I don't know if this is a real issue.

**Comment by ablaom** [comment]
@AlexandruMoraru310 Thanks for reporting.

Sounds to me like a limitation of the VSCode linter, not an MLJ issue. 

Feel free to re-open if you get a real error and please include a stack trace to assist diagnosis.
