### ISSUE TITLE
Add link to support channel if an official channel exists

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#773]
**Is your feature request related to a problem? Please describe.**
By reading the README.md I couldn't find an immediate link to a support channel like Zulip, Discourse, etc.

**Describe the solution you'd like**
Add a link to any supported channel or channels so that newcomers can get support from the community.
Also, add the link to the documentation at the very top. Possibly a very visible button.

**Comment by ablaom** [comment]
Opening discussions in issues is fine. But some find this intimidating, yes? We do have #mlj on Julia slack but this has the disadvantage of being non-archival. We should probably jump into a different forum. I'll bring this up at our next meeting. 

What would your suggestion be?

cc @OkonSamuel

**Comment by juliohm** [comment]
Zulip is the chat with archive that many of us are using already.

**Comment by OkonSamuel** [comment]
For now, I'll prefer Discourse channel, due to the relatively small number of Zulip users. But as Zulip users grows, it doesn't hurt to switch to Zulip.

**Comment by juliohm** [comment]
Discourse is not a online chat experience where people can jump in and ask.
Making slack the default doesn't seem to help much either.

**Comment by OkonSamuel** [comment]
Ok, That's means Zulip is out only choice.

**Comment by juliohm** [comment]
Or gitter or any other chat-like service where discussions are archived and
searchable later. Zulip is the natural choice, yes.

**Comment by ablaom** [comment]
Opened a discussion on #mlj slack about this: https://julialang.slack.com/archives/CC57ZE7EY/p1618960476041300
