### ISSUE TITLE
Issue to track MLJModelInterface 1.0 rollout

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#776]
MLJModelInterface 1.0 is identical to the previous patch, so the compat helper PR's should pass tests. For reasons I don't understand (cc @DilumAluthge)  it seems the CI for these PR's is not automatically triggered, so we have to close and re-open the PR's to trigger. 

Here is the todo list to keep track of progress:

- [x] MLJMultivariateStatsInterface = "1b6a4a23-ba22-4f51-9698-8599985d3728"
- [x] MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
- [x] EvoTrees = "f6006082-12f8-11e9-0c9c-0d5d367ab1e5"
- [x] NearestNeighborModels
- [x] LightGBM = "7acf609c-83a4-11e9-1ffb-b912bcd3b04a" [PR opened](https://github.com/IQVIA-ML/LightGBM.jl/pull/110)
- [x] MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
- [x] MLJClusteringInterface = "d354fa79-ed1c-40d4-88ef-b8c7bd1568af"
- [x] MLJFlux = "094fc8d1-fd35-5302-93ea-dabda2abf845"
- [x] MLJGLMInterface = "caf8df21-4939-456d-ac9c-5fefbfb04c0c"
- [x] MLJLIBSVMInterface = "61c7150f-6c77-4bb1-949c-13197eac2a52"
- [x] MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692"
- [x] MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
- [x] MLJNaiveBayesInterface = "33e4bacb-b9e2-458e-9a13-5d9a90b235fa"
- [x] MLJScikitLearnInterface = "5ae90465-5518-4432-b9d2-8a1def2f0cab"
- [x] MLJXGBoostInterface = "54119dfa-1dab-4055-a167-80440f4f7a91"
- [x] ParallelKMeans = "42b8e9d4-006b-409a-8472-7f34b3fb58af"
- [x] PartialLeastSquaresRegressor = "f4b1acfe-f311-436c-bb79-8483f53c17d5" [PR opened](https://github.com/lalvim/PartialLeastSquaresRegressor.jl/pull/25)
- [x] MLJTuning
- [x] ~~MLJIteration~~ not a direct dep

**Comment by DilumAluthge** [comment]
> it seems the CI for these PR's is not automatically triggered,

This is usually an issue with the SSH key that is being passed to CompatHelper.

**Comment by ablaom** [comment]
Mmm. I'm not convinced. It seems the if the keys are wrong the compathelper action fails. See, eg, the fail here: https://github.com/alan-turing-institute/MLJDecisionTreeInterface.jl/actions/workflows/CompatHelper.yml. After choosing new keys in this case, the action succeeds, but still no CI is triggered.

**Comment by DilumAluthge** [comment]
Ah. The issue here is that if there is already an open PR, CompatHelper skips it, even if you have rotated the keys.

**Comment by ablaom** [comment]
I don't think there was an open PR.

**Comment by ablaom** [comment]
But I'll test your hypothesis next time 😄

**Comment by ablaom** [comment]
🎉 Well, that's most of them done. Whew.

**Comment by ablaom** [comment]
All done.
