### ISSUE TITLE
Make it possible to use deterministic metrics for models providing probabilistic prediction types

### ISSUE THREAD

**Issue by irublev** [alan-turing-institute/MLJ.jl#789]
**Is your feature request related to a problem? Please describe.**

Consider the following example:

```julia
using MLJ, MLJLinearModels, MLJBase

X, y = @load_iris
classifier = LogisticClassifier(lambda=10.0, gamma=0.0, penalty=:l2, fit_intercept=true, solver=LBFGS())
mach = machine(classifier, X, categorical(y)) |> fit!

cv = StratifiedCV(nfolds=10, shuffle=false)
```

If we call the code
```julia
evaluate!(mach, resampling=cv, measure=[Accuracy()])
```
then we obtain the following error:
```
LogisticClassifier @749 <: Probabilistic but prediction_type(Accuracy @731) = :deterministic.
To override measure checks, set check_measure=false.
```

The error is clear, we need to use only probabilistic metrics (such as `AreaUnderCurve`) for models with probabilistic prediction types, while `Accuracy` is for models with deterministic prediction types.

**Describe the solution you'd like**

In fact, in Python scikit-learn successfully processes calculation of deterministic metrics for models able to return probabilitic predictions. For this purpose it is possible to implement both predict and predict_proba methods with predict simply taking argmax amoung probabilities of labels. It would be good if we can parameterize models returning probabilistic predictions with some method able to convert probabilistic predictions to deterministic ones, so that both probabilistic and deterministic measures are applicable to the same model.

**Yet one question**

And I have another question connected with with the one above. It is necessary to calculate a confusion matrix for the model above.  And it is not possible to do this directly, only via a trick descibed at https://discourse.julialang.org/t/mlj-confusion-matrix-methoderror/46856. Is it possible to make automatic or semiautomatic (i.e. without tricks and hacks) conversion of arrays of label distributions to arrays of labels?

**Comment by ablaom** [comment]
Thanks for reporting.

In MLJ you can use `predict_mean`/`predict_mode`/`predict_medium` for probabilistic predictors when you want a deterministic prediction. To use a deterministic metric in your example, specify `operation=predict_mode` in `evaluate!`. 

So, for example, your particular issue is resolved by 

```julia
evaluate!(mach, resampling=cv, operation=predict_mode, measure=[Accuracy()])
```

Another solution is to create a `@pipeline` model in which the probabilistic classifier is followed by `v -> mode.(v)` . The pipeline model is then deterministic.

**Comment by ablaom** [comment]
Actually, there is a bug here. The error message is supposed to be more informative:

```julia
ERROR: ArgumentError: 
LogisticClassifier @148 <: Probabilistic but prediction_type(Accuracy @390) = :deterministic.                      
Perhaps you want to set operation=predict_mode. 
To override measure checks, set check_measure=false. 
```

Will fix this.
