### ISSUE TITLE
Saving the out of sample Loss in iterated models

### ISSUE THREAD

**Issue by Leonardbcm** [alan-turing-institute/MLJ.jl#793]
Hi everyone,

As I understand it from [controls](https://alan-turing-institute.github.io/MLJ.jl/dev/controlling_iterative_models/#IterationControl.Callback) , training losses (loss computed on all the data if `retrain=true` or only the in-sample data if `resampling` is not `nothing`) are automaticly collected and stored in the machine's report.

```julia
using MLJ, MLJFlux, Flux, DataFrames

X = DataFrame(rand(Float64, 1000, 10), :auto); 
y = @. exp(X[:, 2]) + 2 * X[:, 3] *  X[:, 4];

Model = @load NeuralNetworkRegressor pkg=MLJFlux verbosity=0
model = IteratedModel(model = Model(),
                      controls = [Step(1), NumberSinceBest(5)],
                      retrain = true,
                      resampling = Holdout())
mach = machine(model, X, y)
fit!(mach)
report(mach).model_report.training_losses
```
>>> 22-element Vector{Float64}:                                                                                                                                                                                         5.270668490122291                                                                                                                                                                                                  0.3740043562193489                                                                                                                                                                                                 0.24284800731474374                                                                                                                                                                                                0.15982876143669492                                                                                                                                                                                                0.10277438422108662                                                                                                                                                                                                0.06731912907737343                                                                                                                                                                                                0.04783816355393909                                                                                                                                                                                                0.03862304939446953                                                                                                                                                                                                0.03491531181934951                                                                                                                                                                                                0.033616804490055364                                                                                                                                                                                               0.033190762002145616                                                                                                                                                                                               0.03304186863214396                                                                                                                                                                                                0.03297782432946485                                                                                                                                                                                                0.03294225617643775                                                                                                                                                                                                0.032918669231365834                                                                                                                                                                                               0.03290164172717916                                                                                                                                                                                                0.03288890869337537                                                                                                                                                                                                0.0328792457433953                                                                                                                                                                                                 0.03287185457349523                                                                                                                                                                                                0.032866170044040154                                                                                                                                                                                               0.0328617800134844                                                                                                                                                                                                 0.03285837541525048 

From the provided [example ](https://github.com/FluxML/MLJFlux.jl/blob/dev/examples/mnist/mnist.jl) I get that for accessing the out-of-sample losses, I can use the `Control` `WithLossDo`. 

In the example the following code is provided : 
```julia
losses = []
add_loss(loss) = push!(losses, loss)
WithLossDo(add_loss) # in the controls field of the IterativeModel
```

Here the variable `losses` is declared in the global scope. However, I would like to store this loss into the report of the machine, and to be able to retrieve it directly using the `machine` object (not by reading log files). 

I tried a workaround:
```Julia
callback = Callback(x -> push!(report(x).validation_losses, 2))
```
But this could not work as the filed `validation_losses` does not exists in the report and as `report` is a `NamedTuple`, it is not possible to mutate it and add a field.

I don't know if I'm missing a `Control` subtilty or if simply the current design of `Controls` does not allow for storing out of sample losses, but either way I am asking for your help on that matter.

Not that options are : storing the out of sample losses in a globally defined variable using `WithLossDo` or in a log,
Thanks in advance!

**Comment by ablaom** [comment]
@Leonardbcm Thanks for taking this new functionality out for a spin. 

> As I understand it from controls , training losses (loss computed on all the data if retrain=true or only the in-sample data if resampling is not nothing) are automaticly collected and stored in the machine's report.

Well, to clarify, this is not generic behaviour, but just something specific to the model being wrapped. If you train a bare `NeuralNetworkRegressor`, then `training_losses` is a key in the report generated when you fit that model. Some other model may not have that in their report. Part of the report of the *wrapped* model is the report generated by *atomic* model  - this is what `model_report` is accessing. FYI, this is the report generate in the last control cycle, or when using all data if `train=true`.

As for your request, reports are not something the user is intended to mutate, as you realised. In the current design, you need to create the external variable as shown in the examples. Controls do have an associated ephemeral state, but a *history* of that state is not actually recorded internally.

I have some proposals for improvements but could you please first explain your use case a bit more. Why is creating the external variable not adequate in your case?

**Comment by ablaom** [comment]
Closing in favour of https://github.com/JuliaAI/IterationControl.jl/issues/47
