### ISSUE TITLE
Have `evaluate!` automatically run the right kinds of predictions for each metric

### ISSUE THREAD

**Issue by CameronBieganek** [alan-turing-institute/MLJ.jl#795]
Closely related to #789.

I was going to open an issue related to this a while ago, but I never got around to it. Since the measure functions have traits, it might not be too hard to have `evaluate!` perform multiple different kinds of predictions if needed, and match the correct types of predictions to each measure.

**Comment by ablaom** [comment]
Sounds like a good idea. In principle there could be ambiguity: do I want `predict_mean` or `predict_median` when `target_scitype` is `Continuous` and `prediction_type(measure) = :probabilistic`. (Actually, we don't have any probabilistic measures for the continuous case, but we should!). 

Do we choose the mean and issue a warning?

**Comment by CameronBieganek** [comment]
> Do we choose the mean and issue a warning?

Sounds reasonable. Although if a warning is going to be issued, I like to have some way of making the function call more explicit that will avoid the warning... The example that immediately comes to mind is `read_csv` from the **readr** R package (there might be a similar situation for CSV.jl): When you don't specify the column types it will print a message saying how the columns are interpreted, whereas if you specify the column types, then it doesn't print the message. In other words, it's nice to have a way to avoid warnings (or even printed Info messages) that you don't care about.

So, maybe this would work:
- Have `operation` default to `nothing`.
- If `operation == nothing`, then pick the prediction types automatically based on the measures provided. Print a warning if there are any ambiguous cases.
- If `operation` is a scalar or a length-1 vector, use that operation for all measures, without a warning.
- If `operation` is a vector and `length(operation) == length(measure)` then use the corresponding element of `operation` for the corresponding element of `measure`. (No warnings are printed.)

**Comment by ablaom** [comment]
Perfect. I agree @info is better than @warn.

**Comment by ablaom** [comment]
Transferred to https://github.com/JuliaAI/MLJBase.jl/issues/598
