### ISSUE TITLE
MLJ universe graphic in README.md transparency issue

### ISSUE THREAD

**Issue by Seelengrab** [alan-turing-institute/MLJ.jl#796]
**Describe the bug**
In github dark mode, the MLJ Universe graphic in README.md is hard to view.

**To Reproduce**
Browse to the main repo page with dark mode on Github enabled.

Screenshot of what it looks like:

![image](https://user-images.githubusercontent.com/11753998/119646045-feea5b00-be1e-11eb-9691-27e8696255df.png)

**Comment by ablaom** [comment]
Thanks for flagging. Should be okay now

**Comment by Seelengrab** [comment]
Yes, much better! Thank you!
