### ISSUE TITLE
Conditional package loading like 

### ISSUE THREAD

**Issue by vollmersj** [alan-turing-institute/MLJ.jl#8]
[https://github.com/JuliaIO/FileIO.jl/blob/8656519a4eb45915c1eff21cac17d14054244c5f/src/loadsave.jl#L1-L50 ](https://github.com/JuliaIO/FileIO.jl/blob/8656519a4eb45915c1eff21cac17d14054244c5f/src/loadsave.jl#L1-L50 )

**Comment by ablaom** [comment]
This solution uses `Base.__toplevel__`, which is apparently not recommended:

> StefanKarpinski
Steward
Jun 14
Messing around with Base.__toplevel__ or Base.loaded_modules is not recommended and may break at any time in a 1.x release. I don’t really understand the use case for CxxWrap well enough to give advice on a better way to do this. @barche, can you elaborate?

From [this Discourse thread](https://discourse.julialang.org/t/using-an-already-loaded-module-in-0-7/11587/5).

**Comment by ablaom** [comment]
Another [Discourse thread](https://discourse.julialang.org/t/optional-dependencies-requires-jl/3294/21) discusses conditional loading.

**Comment by ysimillides** [comment]
We have conditional package loading using Requires, will be moving away from this in the near future to Separate Packages for dependencies.
