### ISSUE TITLE
Dependency between MLJ and MLJModels

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#82]
At present MLJ depends on MLJModels and MLJModels depends on MLJ for testing purposes only. If MLJ were registered, we could add it as an "testing only" dependency and things seem to work in that case. But MLJ is unregistered, so this is not possible (because of the way Pkg works) and the circular dependency prevents one adding either package to a Julia environment. Thanks to @ysimillides we have a temporary workaround, where MLJ is loaded into MLJModels from within the test script, but this not ideal, since we may be testing with different versions of things from what we are running with (I think?).

We could: 

1. live with the hack until such time as MLJ is registered
2. restrict testing in MLJModels to what is available in MLJBase, which, after all, is the code being implemented by MLJModels. 
3. same as 2 but move enough of MLJ to MLJBase (machine API, testing data sets) to allow testing of the machine interfaces as well.

I vote for 2 but could be persuaded to go for 3. What do others think?

**Comment by tlienart** [comment]
Is the issue only on Travis or am I missing something? Locally I commented out the hack, added the packages and could test MLJModels fine ((https://github.com/tlienart/MLJModels.jl/tree/wip-glm2)?

**Comment by ablaom** [comment]
After some long pondering, I made the executive decision to remove MLJ as a dependency of MLJModels. To make the MLJ testing datasets available to MLJModels (for testing), MLJ/datasets.jl, MLJ/data and MLJ/tasks.jl have been migrated to MLJBase (which naturally remains a dependency of MLJModels).  The file tasks.jl is mostly just task contstuctors. The rest of the task API can probably go into MLJ.

The Pkg.add hack is gone.

Eventually I hope to remove MLJRegistry as a dependency of MLJ, but to so I need to know how to retrieve single files from a public github repo (or something like that) and I am asking around. RemoteFiles.jl doesn't seem to work. Suggestions welcome

**Comment by ablaom** [comment]
Dependency of MLJ on MLJRegistry now also removed.
