### ISSUE TITLE
Document the `Explicit` tuning strategy

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#822]
https://github.com/JuliaAI/MLJTuning.jl/pull/142

Presumably this is added to https://github.com/alan-turing-institute/MLJ.jl/blob/dev/docs/src/tuning_models.md

cc @rikhuijzer

**Comment by rikhuijzer** [comment]
I have some tough deadlines for my PhD, but will try to cram this in next week :+1:

**Comment by ablaom** [comment]
Take your time.
