### ISSUE TITLE
MLJ: machine / evaluate! are random in unclear ways

### ISSUE THREAD

**Issue by schlichtanders** [alan-turing-institute/MLJ.jl#823]
**Describe the bug**
having
```julia
using MLJ
Tree = @load DecisionTreeClassifier pkg=DecisionTree 
tree = Tree()

import RDatasets
iris = RDatasets.dataset("datasets", "iris");
y, X = unpack(iris, ==(:Species), colname -> true);
```

The following is essential random despite it looks like we explicitly told it not to be random.
```julia
mach = machine(tree, X, y)  # adding a mutable cache to the model for performant training 
evaluate!(mach, resampling=Holdout(fraction_train=0.7, shuffle=false),
    measures=[log_loss, brier_score], verbosity=0)
```
sometimes it returns
```
┌───────────────────────────────────┬───────────────┬────────────┐
│ _.measure                         │ _.measurement │ _.per_fold │
├───────────────────────────────────┼───────────────┼────────────┤
│ \e[34mLogLoss{Float64} @912\e[39m │ 8.01          │ [8.01]     │
│ BrierScore @550                   │ -0.444        │ [-0.444]   │
└───────────────────────────────────┴───────────────┴────────────┘
```

and sometimes
```
┌───────────────────────────────────┬───────────────┬────────────┐
│ _.measure                         │ _.measurement │ _.per_fold │
├───────────────────────────────────┼───────────────┼────────────┤
│ \e[34mLogLoss{Float64} @912\e[39m │ 9.61          │ [9.61]     │
│ BrierScore @550                   │ -0.533        │ [-0.533]   │
└───────────────────────────────────┴───────────────┴────────────┘
```

Looks to me like a bug, or unintuitive parameter naming. Definitely something which makes me feel uncomfortable as a newbie to MLJ.

Is it really a bug?
How can someone control this randomness?

---------------------------

**Expected behavior**

if `shuffle = false`, there should be no randomness

**Versions**

Julia = 1.6.1
MLJ = 0.16.7

**Comment by ablaom** [comment]
@schlichtanders Thanks for reporting.

Yes, that is not what one expects. However, the problem, is not with `evaluate!` but almost certainly due to non-determinism in the `DecisionTreeClassifier` itself. For consider:

```julia
using MLJ
using Random
Random.seed!(123)

Tree = @load DecisionTreeClassifier pkg=DecisionTree
tree = Tree()

import RDatasets
iris = RDatasets.dataset("datasets", "iris");
y, X = unpack(iris, ==(:Species), colname -> true);

train, test = partition(eachindex(y), 0.7)

mach = machine(tree, X, y)

fit!(mach, rows=train)
yhat = predict(mach, rows=test)
LogLoss()(yhat, y[test]) |> mean
# 8.009700753137146

fit!(mach, rows=train, force=true)
yhat = predict(mach, rows=test)
LogLoss()(yhat, y[test]) |> mean
# 9.611640903764574

``` 

You could test this by directly calling the DecisionTree.jl models (without MLJ wrapper) but I've not done this.

My guess (because I have implemented trees myself and had the same issue) is that although the number of randomly sampled features at each node is, by default, *all* features (`n_features=0`), the *order* in which these features are considered is still random. So, when two features have the same minimum gini index among all features, the first is probably chosen, but "first" depends on that order.

You could argue that this behaviour is unexpected and post an issue at DecisionTree.jl. Or, you could recover reproducibility by specifying the RNG passed to the core DecisionTreeClassifier model. However, this hyper-parameter is not exposed in the MLJ implementation [yet](https://github.com/JuliaAI/MLJDecisionTreeInterface.jl/issues/4), as it is a more recent addition.  I shall try to push this along.

**Comment by ablaom** [comment]
I have now exposed `rng` as a hyper-parameter in the MLJ models. Once [this](https://github.com/JuliaRegistries/General/pull/42047) merges, you can update `MLJDecisionTreeInterface` and the following will work:

```julia
using MLJ
Tree = @load DecisionTreeClassifier pkg=DecisionTree 
tree = Tree(rng=123)     <----------------------------------- note well

import RDatasets
iris = RDatasets.dataset("datasets", "iris");
y, X = unpack(iris, ==(:Species), colname -> true);
mach = machine(tree, X, y)

julia> map(1:20) do j
       evaluate!(mach, resampling=Holdout(fraction_train=0.7), measures=[log_loss, brier_score], verbosity=0)
       end
20-element Vector{NamedTuple{(:measure, :measurement, :operation, :per_fold, :per_observation, :fitted_params_per_fold, :report_per_fold, :train_test_rows), Tuple{Vector{MLJBase.Measure}, Vector{Float64}, Vector{typeof(predict)}, Vector{Vector{Float64}}, Vector{Vector{Vector{Float64}}}, Vector{NamedTuple{(:tree, :encoding), Tuple{DecisionTree.Node{Float64, UInt8}, Dict{CategoricalArrays.CategoricalValue{String, UInt8}, UInt8}}}}, Vector{NamedTuple{(:classes_seen, :print_tree), Tuple{CategoricalArrays.CategoricalVector{String, UInt8, String, CategoricalArrays.CategoricalValue{String, UInt8}, Union{}}, MLJDecisionTreeInterface.TreePrinter{DecisionTree.Node{Float64, UInt8}}}}}, Vector{Tuple{Vector{Int64}, Vector{Int64}}}}}}:
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
 PerformanceEvaluation(8.01, -0.444)
```

(Incidentally, you will get much better performance if you shuffle the iris data sets which is ordered by target value. You can do this by unpacking in this way:

```julia
y, X = unpack(iris, ==(:Species), colname -> true, rng=234);
```
)

**Comment by schlichtanders** [comment]
@ablaom thank you a lot for all your work here.

The reason was apparently hidden quite in the details. Thanks for explaining the randomness in DecisionTree models.
I am glad you could create a workaround that fast. Thank you very much for your effort.

I am using deterministic code preferably for workshops so that every participant can compare whether they get the same results. Glad it is now also possible with DecisionTrees.

**Comment by ablaom** [comment]
No problem. Checked out your fall-in-love-with-Julia repo - was pleased to see MLJ being showcased there. Another resource not mentioned there that you mind find useful is the material for our [JuliaCon Workshop 2020](https://github.com/ablaom/MachineLearningInJulia2020).
