### ISSUE TITLE
r2 metrics

### ISSUE THREAD

**Issue by refrancesco6** [alan-turing-institute/MLJ.jl#830]
Good Trades, Hello, I am Renato and new to MLJ, I wanted to consult because the R2 metric is not available to evaluate the models, I search in measure and it cannot be found, is there any way to evaluate the models with this metric?

**Comment by ablaom** [comment]
No, I don't believe this one exists.

In the meantime, can you define your own custom measure for use in evaluation; see https://alan-turing-institute.github.io/MLJ.jl/dev/performance_measures/#Traits-and-custom-measures . 

PR also welcome. The code would live [here](https://github.com/JuliaAI/MLJBase.jl/blob/dev/src/measures/continuous.jl)

**Comment by refrancesco6** [comment]
Thanks for your quick response. A hug
