### ISSUE TITLE
Unable to retrieve machine in Mac which is saved from Windows

### ISSUE THREAD

**Issue by vishalhedgevantage** [alan-turing-institute/MLJ.jl#840]
I saved machine in cloud from windows 10 and I am able to retrieve it fine from windows 10. But when I try to retrieve the machine from Mac it gives me EOF error and is unable to load the machine. 
I am able to reproduce this error with a simple machine through this code -

using RDatasets, DataFrames, JLSO, MLJ

iris = dataset("datasets", "iris")

y, X = unpack(iris, ==(:Species), colname -> true)
Tree = @load DecisionTreeClassifier pkg=DecisionTree
tree = Tree()
mach = machine(tree, X, y)
train, test = partition(eachindex(y), 0.7, shuffle=true)
fit!(mach, rows=train)
MLJ.save("test_machine.jlso", mach)

if I try to retrieve this machine in Mac through this shared folder, it gives an error.
I must point out that with same code if I save a machine from Mac, I am able to retrieve it successfully in Windows.

I have tried this with MLJ versions (0.16.7 and 0.16.8) and DecisionTree 0.10.10

**Comment by ablaom** [comment]
@vishalhedgevantage Thanks for reporting!

MLJ uses JLSO.jl for serialization. This format is a thin wrapper for either native julia serialization (default, applying in your case) or the BSON format. I would expect platform-specific issues would lie there and not with MLJ. 

I'm assuming you are serialising and deserializing with the *same* julia version? I don't believe the julia native format is necessarily stable across versions. 

@oxinabox Is it possible JLSO has cross-platform issues? 

For reference, [here](https://github.com/JuliaAI/MLJSerialization.jl/blob/dev/src/machines.jl) is the MLJ code that calls JLSO.

**Comment by oxinabox** [comment]
We do test cross-platform loads in JLSO.
But I think only in the Windows can  open files created on Mac direction.

If you can provide files we can look into.
Open an issue on JLSO.jl once you have a minimal reproducer

**Comment by ablaom** [comment]
Closing for now as not expected to be an MLJ issue.
