### ISSUE TITLE
DBSCAN from Clustering.jl not registered

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#845]
The latest version of Clustering.jl provides DBSCAN, and yet we can't `@load DBSCAN pkg=Clustering`.

Reference: https://juliastats.org/Clustering.jl/stable/dbscan.html

**Comment by ablaom** [comment]
Sounds like a good idea. 

PR welcome. Code goes [here](https://github.com/JuliaAI/MLJClusteringInterface.jl/blob/master/src/MLJClusteringInterface.jl). The existing clusters can be viewed as templates. I guess you need only implement `predict` and no `transform` in this case.
