### ISSUE TITLE
Inconsistent output type for different clustering models

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#846]
The KMeans model from Clustering.jl returns cluster labels as `CategoricalValue`. The `GMMClusterer` model from BetaML.jl returns cluster labels as `UnivariateFinite`. Shouldn't all these clustering models return a consistent/predictable type? Otherwise end-users are forced to handle these differences manually in their one-shot scripts.

**Comment by juliohm** [comment]
Related:
- https://github.com/JuliaAI/MLJModelInterface.jl/issues/120
- https://github.com/sylvaticus/BetaML.jl/issues/26

**Comment by ablaom** [comment]
Supervised models that can predict probabilities do so by default when `predict` is called. To get a deterministic prediction you call `predict_mode` or `predict_mean` or wrap in `BinaryThresholdPredictor`. 

It seems to me Unsupervised models should follow the same pattern. 

Closing as addressed by cited issues and new issues opened in response.
