### ISSUE TITLE
transformations like in R with formulas `y ~ a + a * b + b^3`.

### ISSUE THREAD

**Issue by vollmersj** [alan-turing-institute/MLJ.jl#867]
**Is your feature request related to a problem? Please describe.**
This would make code more easy readable.
**Describe the solution you'd like**
One could use  StatsModels.jl `@formula`?

**Comment by ablaom** [comment]
Thanks. This is however a duplicate of https://github.com/JuliaAI/MLJModels.jl/issues/406
