### ISSUE TITLE
Is MLJ ready for Julia 1.7?

### ISSUE THREAD

**Issue by roland-KA** [alan-turing-institute/MLJ.jl#869]
I've tried MLJ on Julia 1.7 using Pluto notebooks. The notebooks worked fine on Julia 1.6.x, but crash in the combination Julia 1.7/Pluto (see fonsp/Pluto.jl#1722) with a segmentation fault. Nevertheless the code works on Julia 1.7 using the REPL. 

So it may be a Pluto issue, but could also be some MLJ code which is not ready for 1.7. Therefore I would like to know, if MLJ has been tested and released for 1.7 on all platforms?

**Comment by roland-KA** [comment]
Thanks for the information!

And as you have seen perhaps, issue fonsp/Pluto.jl#1722 is neither related to MLJ nor to Pluto. It seems to be a general issue of Julia 1.7 on the M1 platform.

**Comment by ablaom** [comment]
Yes, MLJ is 1.7 ready and tested.
