### ISSUE TITLE
Stratified CV not working - LoadError: MethodError: no method matching iterate(::CategoricalValue{String, UInt32})

### ISSUE THREAD

**Issue by casasgomezuribarri** [alan-turing-institute/MLJ.jl#871]
**Describe the bug**

`MLJBase.StratifiedCV` is meant to apply only to target variables for which `scitype == Multiclass || OrderedFactor` [(docs)](https://alan-turing-institute.github.io/MLJ.jl/dev/evaluating_model_performance/#MLJBase.StratifiedCV). Also, objects of these `scitype`s have machine type `CategoricalValue` [(docs)](https://alan-turing-institute.github.io/MLJ.jl/dev/working_with_categorical_data/#Under-the-hood:-CategoricalValue-and-CategoricalArray).

Yet when I try to implement a stratified partition of the data according to a Multiclass variable, I get the following error:

> ERROR: LoadError: MethodError: no method matching iterate(::CategoricalValue{String, UInt32})
> Closest candidates are:
>   iterate(::Union{LinRange, StepRangeLen}) at range.jl:664
>   iterate(::Union{LinRange, StepRangeLen}, ::Int64) at range.jl:664
>   iterate(::T) where T<:Union{Base.KeySet{var"#s79", var"#s78"} where {var"#s79", var"#s78"<:Dict}, Base.ValueIterator{var"#s77"} where var"#s77"<:Dict} at dict.jl:693

Am I missing something obvious here? I have definitely used this functionality before without issues.

**To Reproduce**

```julia
using MLJ
using MLJBase
using DataFrames
using CategoricalArrays

a = DataFrame(rand(("a", "b"), 5, 10), :auto)
coerce!(a, Textual => Multiclass)

stratified_cv = StratifiedCV(; nfolds=2, shuffle=false)
train_val_pairs = MLJBase.train_test_pairs(stratified_cv, size(a, 1), a[:, "x1"])

```

**Versions**
<details>

> (@v1.6) pkg> status
>       Status `C:\Users\ivica\.julia\environments\v1.6\Project.toml`
>   [fbb218c0] BSON v0.3.4
>   [336ed68f] CSV v0.9.11
>   [324d7699] CategoricalArrays v0.10.2
>   [a8cc5b0e] Crayons v4.0.4
>   [a93c6f00] DataFrames v1.3.0
>   [a5dba43e] DynamicGrids v0.21.1
>   [5789e2e9] FileIO v1.11.2
>   [587475ba] Flux v0.12.8
>   [82e4d734] ImageIO v0.5.9
>   [6218d12a] ImageMagick v1.2.2
>   [916415d5] Images v0.23.3
>   [eb30cadb] MLDatasets v0.5.14
>   [add582a8] MLJ v0.16.11
>   [a7f614a8] MLJBase v0.18.26
>   [dbb5928d] MappedArrays v0.4.1
>   [dbeba491] Metalhead v0.5.3
>   [c3e4b0f8] Pluto v0.17.3
>   [2913bbd2] StatsBase v0.33.13
>   [a63ad114] Mmap

</details>

**Comment by ablaom** [comment]
Thanks for reporting, @casasgomezuribarri  

I think this is just a typo. Where a vector of integers is expected (the row indices) you have put a single integer. The following works for me:

```julia
julia> train_val_pairs = MLJBase.train_test_pairs(stratified_cv, 1:size(a, 1), a[:, "x1"])
2-element Vector{Tuple{Vector{Int64}, Vector{Int64}}}:
 ([2, 4], [1, 3, 5])
 ([1, 3, 5], [2, 4])
```

**Comment by casasgomezuribarri** [comment]
Really appreciate your answer, sorry for wasting your time on such a stupid error!

**Comment by ablaom** [comment]
No worries! I am forever doing `[x for x in length(v)]` when I really mean `[x for x in 1:length(v)]`.
