### ISSUE TITLE
New measures `RSquared` and aliases `rsq`, `rsquared` need exporting

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#880]
Or we should export measures in a more programmatic way.

**Comment by sayantan1410** [comment]
Hello, I would like to contribute to this issue, can you please explain a bit more on what is to be done ?

**Comment by ablaom** [comment]
Well, the dead easy option is just to add `RSquared, rsq, rsquared` to the list [here](https://github.com/alan-turing-institute/MLJ.jl/blob/3e552294d147b618ace256fa06a9db03f784d1d7/src/MLJ.jl#L95), just like we already have in the source package [here](https://github.com/JuliaAI/MLJBase.jl/blob/a852ddcb3f456e3e4603f878f01b8ca3b7229c09/src/MLJBase.jl#L226). I'd be perfectly happy with this. 

On the other hand, if you know some julia metaprogramming, you could replace the current nonsense with something more programatic, so we don't have to keep adding to the list every time add new measure is added in MLJBase. Once MLJBase is imported, you can do `measures()` to get a table of all the measures and their properties, the key ones being `name` and `instances` (aliases) which you are going to be interpolated into some `eval(:(export $name))` calls, or whatever.

**Comment by sayantan1410** [comment]
@ablaom Thank you so much, I will try to solve it in the better way possible. Will drop in a comment if I face some issue or have some problem in understanding.
