### ISSUE TITLE
Do not re-export `value`

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#891]
Too likely to conflict with other uses.

**Comment by sayantan1410** [comment]
Hey, I would like to work on this issue, can you guide me on how to proceed.

**Comment by ablaom** [comment]
Thanks @sayantan1410. However, we have not started a branch to collect PR's for the next breaking release yet.

**Comment by sayantan1410** [comment]
Okay no problem, let me know once you start, thank you !!

**Comment by ablaom** [comment]
Completed.
