### ISSUE TITLE
Documentation of 'Common MLJ Workflows' shows wrong `partition` syntax

### ISSUE THREAD

**Issue by roland-KA** [alan-turing-institute/MLJ.jl#894]
The MLJ documentation in [section 'Common MLJ Workflows'](https://alan-turing-institute.github.io/MLJ.jl/dev/common_mlj_workflows/#Common-MLJ-Workflows) shows the following `partition` example (using `multi = true`):

`(Xtrain, ytrain), (Xtest, ytest)  = partition((X, y), 0.6, multi=true,  rng=123)`

The order of the results is wrong in this example. 

It should read instead:

`(Xtrain, Xtest), (ytrain, ytest) = ...`

**Comment by ablaom** [comment]
Great catch, thanks!
