### ISSUE TITLE
Update `Save` method documentation

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#899]
After:

- [x] https://github.com/JuliaAI/MLJIteration.jl/pull/47 is merged and a new MLJIteration version  tagged

... remove the following sentence from https://github.com/alan-turing-institute/MLJ.jl/blob/master/docs/src/controlling_iterative_models.md :

"⋆ If using MLJIteration without MLJ, then Save is not available unless one is also using MLJSerialization."

**Comment by mertbozkir** [comment]
I couldn't find it in the docs, this sentence is removed(I guess) so you can close this issue 😅

**Comment by ablaom** [comment]
Yes, you are right, @mertbozkir. Thank you.
