### ISSUE TITLE
Parameter interface and constraint description

### ISSUE THREAD

**Issue by vollmersj** [alan-turing-institute/MLJ.jl#9]
https://github.com/JuliaOpt/MathProgBase.jl

**Comment by vollmersj** [comment]
This is the place to discuss hyperparamters
 - [OLD MLJ](https://github.com/dominusmi/mlj/blob/e811e1462f332528caeeb220482a6271fbec55bb/MLJ.jl#L69)
 - [exposing hyper parameter as a dict](https://github.com/tlienart/AnalyticalEngine.jl/blob/master/src/supervised/sm-utils.jl)

**Comment by ablaom** [comment]
Closing this as now implemented along lines suggested in [issue #2](https://github.com/alan-turing-institute/MLJ.jl/issues/2#issuecomment-442946216)
