### ISSUE TITLE
Broken tutorial link

### ISSUE THREAD

**Issue by KronosTheLate** [alan-turing-institute/MLJ.jl#917]
![image](https://user-images.githubusercontent.com/61620837/160231122-8a69110e-9948-4318-998d-4a367100081e.png)
Takes me to
![image](https://user-images.githubusercontent.com/61620837/160231124-fada2601-bd7a-47a2-963f-5fb3ff3487d2.png)

**Comment by Philogicatician** [comment]
My phone states it's an outdated page: ![Screenshot_20220326-051928_Brave.jpg](https://user-images.githubusercontent.com/9929287/160235188-8fa62f7f-e88d-4b63-a59c-662af8aa725b.jpg)

**Comment by KronosTheLate** [comment]
Right! That just goes to show how much when you are looking for something specific in a bit of a hurry, compared to reading every line on the page. My bad. I do however think that the page should be taken down (or simply contain the link at the top), or that broken links should be fixed.

**Comment by ablaom** [comment]
@KronosTheLate Thanks for reporting. I've gone ahead and fixed the broken link anyway that will become live the next time we roll out a doc update. 

FYI: Here is the new target of that link: [Learning MLJ](https://alan-turing-institute.github.io/MLJ.jl/dev/learning_mlj/).
