### ISSUE TITLE
Confusing true_negative(x, y) error

### ISSUE THREAD

**Issue by dario-brooks** [alan-turing-institute/MLJ.jl#919]
**Describe the bug**

When trying to run "true_negative(x, y)" on two simple vectors x and y, I get a TypeError, which I have pasted below along with the code to reproduce it.
I've tried this within VSCode, then within a fresh Julia REPL in the terminal, then tried uninstalling and reinstalling Julia 1.7.2, then tried updating the MLJ package, etc. Assuming I've done the above troubleshooting steps correctly, the error persists...

**To Reproduce**

```julia
julia> using MLJ

julia> y = coerce([1.0, 0.0, 0.0], OrderedFactor)
3-element CategoricalArrays.CategoricalArray{Float64,1,UInt32}:
 1.0
 0.0
 0.0

julia> yp = coerce([1.0, 0.0, 0.0], OrderedFactor)
3-element CategoricalArrays.CategoricalArray{Float64,1,UInt32}:
 1.0
 0.0
 0.0

julia> MLJ.true_negative(y, yp)
ERROR: TypeError: non-boolean (Nothing) used in boolean context
Stacktrace:
 [1] _confmat(ŷ::CategoricalArrays.CategoricalVector{Float64, UInt32, Float64, CategoricalArrays.CategoricalValue{Float64, UInt32}, Union{}}, y::CategoricalArrays.CategoricalVector{Float64, UInt32, Float64, CategoricalArrays.CategoricalValue{Float64, UInt32}, Union{}}; rev::Nothing, perm::Nothing, warn::Bool)
   @ MLJBase ~/.julia/packages/MLJBase/hLtde/src/measures/confusion_matrix.jl:98
 [2] (::TrueNegative)(ŷ::CategoricalArrays.CategoricalVector{Float64, UInt32, Float64, CategoricalArrays.CategoricalValue{Float64, UInt32}, Union{}}, y::CategoricalArrays.CategoricalVector{Float64, UInt32, Float64, CategoricalArrays.CategoricalValue{Float64, UInt32}, Union{}})
   @ MLJBase ~/.julia/packages/MLJBase/hLtde/src/measures/finite.jl:649
 [3] top-level scope
   @ REPL[5]:1

```
Note: I have also tried "MLJBase.true_negative(y, yp)" and simply "true_negative(y, yp)". Each returns the same error.

**Expected behavior**

true_negative(x, y) should return the number of true negatives for observations x and ground truth y, so it should give an integer. For the vectors above, it should return 2, for example.

**Additional context**

System setup: Base model 2021 Macbook Air with the M1 chip. 

**Versions**
Running Julia v1.7.2, installed via Homebrew. (Previously running v1.7 installed via .dmg; gave an identical error).

Thank you for the support!!

**Comment by ablaom** [comment]
@dario-brooks Thank you for reporting. 

I could not reproduse using latest version of `MLJBase` (0.19.8).

Can you please report the output of `using Pkg; Pkg.status()`?

**Comment by ablaom** [comment]
@dario-brooks If you are able to assist as per previous comment, feel free to re-open.
