### ISSUE TITLE
DOC: Link giving 404 not found

### ISSUE THREAD

**Issue by bhavukkalra** [alan-turing-institute/MLJ.jl#929]
One of the links mentioned in Contributing readme(In the 3 point of `issues`), Is giving 404 not found. It should be removed or updated with a new one.

Link - [Contributing](https://github.com/alan-turing-institute/MLJ.jl/blob/dev/CONTRIBUTING.md)
![mljjs](https://user-images.githubusercontent.com/41142068/163670672-7dc9f80f-b16b-451d-97d5-1531711b050a.PNG)

**Comment by ablaom** [comment]
@bhavukkalra Thanks for reporting. 

I see that the project was still private and have made it public. Please confirm this is fixed by closing the issue.

Thanks again.

**Comment by bhavukkalra** [comment]
This still seems to be giving 404 not found

**Comment by ablaom** [comment]
@bhavukkalra Thanks for getting back to me. Can you please try one more time?

**Comment by bhavukkalra** [comment]
Yes, Its working now! Closing
