### ISSUE TITLE
models(matching(X, y)) returns empty but shouldn't 

### ISSUE THREAD

**Issue by Carlos-Trebbau** [alan-turing-institute/MLJ.jl#937]
Hi, I have a features table with these types:
![image](https://user-images.githubusercontent.com/84703650/166924378-b88980fe-0788-4384-a3bf-ee3ee1921e6d.png)
and a labels vector with this type:
![image](https://user-images.githubusercontent.com/84703650/166924660-fc190e78-deac-48f6-8fd4-8983e9ab2f8f.png)
But yet I get an empty array when calling `models(matching(X, y))` 

I've tried suppressing warnings and training a random forest but the fitting doesn't pass the type checks. I've also tried `coerce()` which seemingly does its thing without problem.

Here are the error messages:
![image](https://user-images.githubusercontent.com/84703650/166963307-894a4d83-c29c-43f1-b26c-0067971dc701.png)

I fail to see how the passed type is not a subtype of the expected type. 

Here's the head of the features table, in case it helps

![image](https://user-images.githubusercontent.com/84703650/166962506-97a03d6b-e164-43d1-93fb-846e196dd3ff.png)

Julia v1.7.2
MLJ v0.18.2
DecisionTree v0.10.11

Thanks!

**Comment by ablaom** [comment]
@Carlos-Trebbau Thanks for reporting.

If I understand you correctly, your target is a *table* not a vector (vector being the more typical case). Most supervised models are limited to a single target, which is presented as a *vector* (not a table with one column). If you are really wanting to do multi-target regression, then indeed you need `y` in a table, but there are not so many models of this kind. Here they are:

```julia
julia> models() do m 
           m.is_supervised && Table(Continuous) <: m.target_scitype
       end
10-element Vector{NamedTuple{(:name, :package_name, :is_supervised, :abstract_type, :deep_properties, :docstring, :fit_data_scitype, :human_name, :hyperparameter_ranges, :hyperparameter_types, :hyperparameters, :implemented_methods, :inverse_transform_scitype, :is_pure_julia, :is_wrapper, :iteration_parameter, :load_path, :package_license, :package_url, :package_uuid, :predict_scitype, :prediction_type, :supports_class_weights, :supports_online, :supports_training_losses, :supports_weights, :transform_scitype, :input_scitype, :target_scitype, :output_scitype), T} where T<:Tuple}:
 (name = KPLSRegressor, package_name = PartialLeastSquaresRegressor, ... )
 (name = MultiTaskElasticNetCVRegressor, package_name = ScikitLearn, ... )
 (name = MultiTaskElasticNetRegressor, package_name = ScikitLearn, ... )
 (name = MultiTaskLassoCVRegressor, package_name = ScikitLearn, ... )
 (name = MultiTaskLassoRegressor, package_name = ScikitLearn, ... )
 (name = MultitargetKNNRegressor, package_name = NearestNeighborModels, ... )
 (name = MultitargetLinearRegressor, package_name = MultivariateStats, ... )
 (name = MultitargetNeuralNetworkRegressor, package_name = MLJFlux, ... )
 (name = MultitargetRidgeRegressor, package_name = MultivariateStats, ... )
 (name = PLSRegressor, package_name = PartialLeastSquaresRegressor, ... )
```
None of these support non-`Continuous` features, as you correctly determined with your empty search. However, there are models that do support `Count` features and a *single* continuous target. Here they are:

```julia
julia> X = (x=rand([1,2], 5), y = rand(5));

julia> schema(X)
┌───────┬────────────┬─────────┐
│ names │ scitypes   │ types   │
├───────┼────────────┼─────────┤
│ x     │ Count      │ Int64   │
│ y     │ Continuous │ Float64 │
└───────┴────────────┴─────────┘


julia> y = rand(5);

julia> scitype(y)
AbstractVector{Continuous} (alias for AbstractArray{Continuous, 1})

julia> models(matching(X, y))
7-element Vector{NamedTuple{(:name, :package_name, :is_supervised, :abstract_type, :deep_properties, :docstring, :fit_data_scitype, :human_name, :hyperparameter_ranges, :hyperparameter_types, :hyperparameters, :implemented_methods, :inverse_transform_scitype, :is_pure_julia, :is_wrapper, :iteration_parameter, :load_path, :package_license, :package_url, :package_uuid, :predict_scitype, :prediction_type, :supports_class_weights, :supports_online, :supports_training_losses, :supports_weights, :transform_scitype, :input_scitype, :target_scitype, :output_scitype), T} where T<:Tuple}:
 (name = ConstantRegressor, package_name = MLJModels, ... )
 (name = DecisionTreeRegressor, package_name = BetaML, ... )
 (name = DecisionTreeRegressor, package_name = DecisionTree, ... )
 (name = DeterministicConstantRegressor, package_name = MLJModels, ... )
 (name = RandomForestRegressor, package_name = BetaML, ... )
 (name = RandomForestRegressor, package_name = DecisionTree, ... )
 (name = RandomForestRegressor, package_name = ScikitLearn, ... )
```

Does that clarify things sufficiently?

**Comment by ablaom** [comment]
If you want to do multi-target regression with `Count` in the features, one option is to first apply `ContinuousEncoder`. You can do this by using `pipe = ContinuousEncoder() |> model` instead of `model`, where `model` is an instance of your multi-target regressor.

**Comment by ablaom** [comment]
@Carlos-Trebbau Please do re-open this issue if you think I may have missed the point.

**Comment by Carlos-Trebbau** [comment]
Perfectly clear!

**Comment by DilumAluthge** [comment]
@ablaom Can we make it so that `matching(X, y)` prints a warning if `y` is a table that only has a single column?

**Comment by DilumAluthge** [comment]
> @ablaom Can we make it so that `matching(X, y)` prints a warning if `y` is a table that only has a single column?

https://github.com/JuliaAI/MLJModels.jl/pull/460

**Comment by ablaom** [comment]
Such a feature has now been added by @DilumAluthge
