### ISSUE TITLE
LoadError on Getting Started Fit and Predict exercise

### ISSUE THREAD

**Issue by dwschulze** [alan-turing-institute/MLJ.jl#940]
This tutorial

https://juliaai.github.io/DataScienceTutorials.jl/getting-started/fit-and-predict/

has a LoadError:

import MLJDecisionTreeInterface ✔
ERROR: LoadError: MethodError: objects of type Random._GLOBAL_RNG are not callable

I'm using Julia 1.6.6.

**Comment by ablaom** [comment]
@dwschulze Thanks for reporting.

I wonder if this is a Julia version issue and/or a package environment issue.  I see that the tutorials have been recently updated to work with Julia 1.7. Indeed, I tried to instantiate the provided `Project.toml` file and got an error when doing this under 1.6.5 (see https://github.com/JuliaAI/DataScienceTutorials.jl/issues/185). 

I was not able to reproduce your error using Julia 1.7 or Julia 1.6.5 (after regenerating a new Manifest.toml). 

Below is my test workflow:

1. Download and decompress the "whose project folder" (link on 4th line of tutorial page). In the case of Julia 1.6.5, delete the Manifest.toml file (to force regeneration in Step 3):

2. Change directory to the decompressed folder (called "A-fit-predict")

3. Launch the Julia REPL and run the following code

```julia
julia> using Pkg; Pkg.activate("."); Pkg.instantiate() # to load a valid set of packages 
julia> include("tutorial.jl")
```

This all works fine for me. Does it work fine for you? Are you using REPL or a Juptyer noteboo? How are you activating the package environment (if you know what that means)?

@tlienart

**Comment by dwschulze** [comment]
The source code download works for me without activation.  julia -i
tutorial.jl runs without any problem.

The problem is that the code on the web page is very different from the
source code download:

https://juliaai.github.io/DataScienceTutorials.jl/getting-started/fit-and-predict/

Each time I've tried to get a start with Julia I've run into introductory
material that is outdated or just plain wrong.  Do you know if the material
shown on the rest of the getting-started web pages is correct?

I don't know what activation is.  When I saw a 644 line Manifest.toml file
for less than 100 lines of source code I decided to skip the activation
(whatever that is) and see if it would run without it, and fortunately it
does.  The Manifest.toml file is autogenerated, but they don't say how.  If
they intend for us to use it they should explain what it does somewhere.

I'm used to seeing bloated pom.xml files for Java projects but 644 lines of
dependency management for less than 100 lines of code seems like the tail
wagging the dog.

**Comment by ablaom** [comment]
> The problem is that the code on the web page is very different from the
source code download:

I'm not sure I understand what is "different" about them. One is generated from the other.  What is true, is that the web page does not include the steps for activating a working (tested) package environment. Datascience Tutorials is assuming you are familiar with how this works. (Maybe that's an imperfect assumption, I agree.) The Project.toml inludes compatibility bounds for a collection of Julia packages, while the Manifest.toml is a complete snapshot of package versions (including all dependencies) satisfying those requirements. It is not expected that you generate this Manifest.toml yourself (I was doing this above as a diagnostic.) You tell Julia what environment you want to use using `Pkg.activate(...)`. To run the code in any Datascience Tutorial you must first download and activate the accompanying Project.toml/Manifiest.toml files to be sure to be using the same packages on which the tutorial was tested. Alternatively, you can build your own fresh environment `using Pkg.add(...)` for each new package you need) but there's no guarantee you'll get exactly the same installation. 

You can learn more about package management at https://docs.julialang.org/en/v1/stdlib/Pkg/

@dwschulze I propose we close this in favour of https://github.com/JuliaAI/DataScienceTutorials.jl/issues/186

**Comment by dwschulze** [comment]
Did you compare the source code on that web page to
A-fit-predict/tutorial.jl?  The first several lines are identical:

using MLJ import Statistics using PrettyPrinting using StableRNGs X, y =
@load_iris;
DecisionTreeClassifier = @load DecisionTreeClassifier pkg=DecisionTree
tree_model = DecisionTreeClassifier()

The web page then contains this which isn't in the
A-fit-predict/tutorial.jl.  This is where the error occurs:

import MLJDecisionTreeInterface ✔ DecisionTreeClassifier( max_depth = -1,
min_samples_leaf = 1, min_samples_split = 2, min_purity_increase = 0.0,
n_subfeatures = 0, post_prune = false, merge_purity_threshold = 1.0,
pdf_smoothing = 0.0, display_depth = 5, rng = Random._GLOBAL_RNG())

There may be other differences.  I don't see how one could be generated
from the other.

**Comment by ablaom** [comment]
Ohhh, I see the confusion. What you are referring to is *output* not code you enter. It's what you would expect to see having pasted in the previous cell. 

On the web page input cells have a light blue shading, while output cells have a light grey (?) shading.

**Comment by dwschulze** [comment]
Thanks for clearing that up.  I'll close this.
