### ISSUE TITLE
Make docs regarding Random Forest and Ensebles more clear

### ISSUE THREAD

**Issue by KronosTheLate** [alan-turing-institute/MLJ.jl#945]
From https://alan-turing-institute.github.io/MLJ.jl/dev/composing_models/:
"[Homogeneous Ensembles](https://alan-turing-institute.github.io/MLJ.jl/dev/homogeneous_ensembles/#Homogeneous-Ensembles) - for blending the predictions of multiple supervised models all of the same type, but which receive different views of the training data to reduce overall variance. The technique is known as observation [bagging](https://en.wikipedia.org/wiki/Bootstrap_aggregating). **Bagging decision trees, like a DecisionTreeClassifier, gives what is known as a random forest, although MLJ also provides several canned random forest models.**"

The quote suggests (to me at least) that an Ensemble of trees is equivalent to a random forest. However, from https://en.wikipedia.org/wiki/Random_forest#:~:text=Random%20forests%20or%20random%20decision,class%20selected%20by%20most%20trees.:
"An extension of the algorithm was developed by [Leo Breiman](https://en.wikipedia.org/wiki/Leo_Breiman)[[9]](https://en.wikipedia.org/wiki/Random_forest#cite_note-breiman2001-9) and [Adele Cutler](https://en.wikipedia.org/wiki/Adele_Cutler),[[10]](https://en.wikipedia.org/wiki/Random_forest#cite_note-rpackage-10) who registered[[11]](https://en.wikipedia.org/wiki/Random_forest#cite_note-11) "Random Forests" as a [trademark](https://en.wikipedia.org/wiki/Trademark) in 2006 (as of 2019, owned by [Minitab, Inc.](https://en.wikipedia.org/wiki/Minitab)).[[12]](https://en.wikipedia.org/wiki/Random_forest#cite_note-12) The extension combines Breiman's "[bagging](https://en.wikipedia.org/wiki/Bootstrap_aggregating)" idea and random selection of features, introduced first by Ho[[1]](https://en.wikipedia.org/wiki/Random_forest#cite_note-ho1995-1) and later independently by Amit and [Geman](https://en.wikipedia.org/wiki/Donald_Geman)[[13]](https://en.wikipedia.org/wiki/Random_forest#cite_note-amitgeman1997-13) in order to construct a collection of decision trees with controlled variance."

Of particular interest is "and random selection of features", which is not an option for Ensembles as far as I can tell. This difference between a random forest and ensemble of trees should be made more clear in the docs, or potentially the option to only classify by a random subset of features should be added to ensembles.

**Comment by KronosTheLate** [comment]
I do mean feature bagging. I did very much like your original suggestion:
```
Bagging decision trees, like a DecisionTreeClassifier, gives what Breiman[9] called a Random Forest. Nowadays, random forest implementations also bag features (do doc("RandomForest", pkg="DecisionTree" for an example). MLJ's EnsembleModel wrapper does not currently allow feature bagging.
```

The goal is simply to avoid having people think that an ensemble of trees is equivalent to a random forest.

**Comment by ablaom** [comment]
Mmm,  yes, but I deleted my original suggestion because I the standard implementations (eg, ScikitLearn) only subsample features at the level of nodes, and not additionally at the level of trees. So they are not "feature baggers" in the sense of model-generic feature bagging. Or am I still missing something?

**Comment by ablaom** [comment]
That is, I would say that bagging `DecisionTree.DecisionTreeClassifier` trees using `EnsembleModel`, with the atomic `n_subfeatures` hyper-parameter set to non-zero, *is* equivalent to `DecisioinTree.RandomForestClassifier` (there may be small differences in the nature of the bagging - eg, replacement or no replacement - I forget these details just now).
