### ISSUE TITLE
Compile time for DataFrames, typename hack not working

### ISSUE THREAD

**Issue by pdeffebach** [alan-turing-institute/MLJ.jl#946]
Please see [this discourse post](https://discourse.julialang.org/t/simple-table-operation-has-very-large-compilation-time-with-mlj/82503/5?u=pdeffebach) outlining the problem.

**Comment by ablaom** [comment]
@OkonSamuel Can we close in favour of https://github.com/JuliaAI/MLJBase.jl/issues/784 ?

**Comment by OkonSamuel** [comment]
closing in favor of https://github.com/JuliaAI/MLJBase.jl/issues/784 ?
