### ISSUE TITLE
Add ConformalPrediction.jl to list of 3rd party packages

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#967]

**Comment by ablaom** [comment]
cc @pat-alt

**Comment by pat-alt** [comment]
Happy to create a PR for this myself if helpful. Would do that once [this](https://github.com/pat-alt/ConformalPrediction.jl/issues/5) is sorted out.

**Comment by ablaom** [comment]
@pat-alt assigned.

**Comment by ablaom** [comment]
Completed
