### ISSUE TITLE
Encoders for feature engineering

### ISSUE THREAD

**Issue by indymnv** [alan-turing-institute/MLJ.jl#970]
I was checking the documentation a bit and I missed the possibility of using different encoders for feature engineering in machine learning; it looked like only One-Hot-Encoder is available.
In python, for now, Scikit-learn has a solution that it worked well, Pandas also have some less popular options, and there are third-party libraries that integrate very well with the ML ecosystem (Pandas-Scikit-Learn). It is interesting to check, for example, [Feature Engine](https://feature-engine.readthedocs.io/en/latest/#). However, I think most people in the Python ML ecosystem use the Scikit-learn feature encoders, I guess for reliability.

Is there a project for integrating more encoders into JuliaAI?

**Comment by juliohm** [comment]
@indymnv we are actively working on https://github.com/JuliaML/TableTransforms.jl, it is not specific to MLJ.jl though.

**Comment by ablaom** [comment]
@indymnv I'm going to reply to your message at thread referenced below.

Closing in favour of https://github.com/JuliaAI/MLJModels.jl/issues/314
