### ISSUE TITLE
Support for `ProbabilisticSet` type in `MLJModelInterface.jl`

### ISSUE THREAD

**Issue by pat-alt** [alan-turing-institute/MLJ.jl#978]
**Is your feature request related to a problem? Please describe.**
This is related to this [issue](https://github.com/pat-alt/ConformalPrediction.jl/issues/27) and this is more of a proposal than an issue. [`ConformalPrediction.jl`](https://github.com/pat-alt/ConformalPrediction.jl) is a new package for uncertainty quantification through Conformal Prediction (CP) for machine learning models trained in MLJ.

**Describe the solution you'd like**
Conformal classifiers produce set-valued predictions. This is currently not something that is supported for downstream tasks by MLJ. To add conformal classifiers for general use, we would need `LearnAPI.jl` to support a `ProbabilisticSet` type (and maybe `Set` for deterministic classifiers). Of particular interest here is to implement proper evaluation schemes for these types of predictions. A good starting point to this end could be this [tutorial](https://arxiv.org/pdf/2107.07511.pdf) from page 11 onwards. 

**Describe alternatives you've considered**
Currently, conformal classifiers in [`ConformalPrediction.jl`](https://github.com/pat-alt/ConformalPrediction.jl) are simply subtypes of `Supervised` (though I might change this to `Probabilisitic`). They should be more or less ready for general use (except for evaluation, of course, and perhaps other downstream tasks I'm not familiar with). 

As I won't get to this myself in the near future, I thought I'd open this up here for discussion. Any thought/comments/contribution very much welcome 🙏🏽 

cc @ablaom

**Comment by ablaom** [comment]
To clarify, LearnAPI.jl is a proposal for a new basement level model interface. MLJModelInterface.jl remains the active API. So @pat-alt's proposal, as I understand it, is to add the following to MLJModelInterface.jl:

```julia
abstract type Set <: Supervised end
abstract type ProbabilisticSet <: Supervised end
```
which sounds good to me.

**Comment by pat-alt** [comment]
Types have now been added to [`MLJModelInterface.jl`](https://github.com/JuliaAI/MLJModelInterface.jl/pull/167). Evaluation will be addressed in future issues.
