### ISSUE TITLE
Add wrappers for clustering to get uniform interface

### ISSUE THREAD

**Issue by juliohm** [alan-turing-institute/MLJ.jl#982]
Can you please provide an example with

1. Clustering.KMeans
2. Clustering.DBSCAN
3. BetaML.GaussianMixtureClusterer

where we call the same MLJ interface functions to "train" the clustering models with a random data set `X1 = rand(3,100)` and then "predict" the labels of new points `X2 = rand(3, 10)`?

Every time I try to accomplish this task I get stuck with various issues (e.g. the output of the models follow different formats and conventions). I am looking for a simple example with `MLJ.fit`, `MLJ.predict`, `MLJ.predict_mode` and `MLJ.transform` only. I don't want to wrap the models into a machine in this example.

**Comment by ablaom** [comment]
It is not possible at present as 1, 2, and 3 are all different: 2 does not generalize to new observations, and 3 outputs probabilistic labels. There are natural differences in the API for this reason. For a uniform interface, we need a wrapper to  convert non-generalizing clusters to generalizing ones, and a wrapper to convert probabilistic-predicting clusterers into deterministic ones. These do not exist at present. They could be created using MLJ learning networks.

**Comment by juliohm** [comment]
No longer needed.
