### ISSUE TITLE
MLJ Tuning optimizers are no working with julia 1.8.3 and julia 1.9.0

### ISSUE THREAD

**Issue by MrBenzWorld** [alan-turing-institute/MLJ.jl#990]
TreeParzen,MLJParticleSwarmOptimization are out dated and not supporting the latest julia

**Comment by ablaom** [comment]
Thanks for reporting. These will be part of the problem:

- [ ] https://github.com/IQVIA-ML/TreeParzen.jl/issues/84
- [ ] https://github.com/JuliaAI/MLJParticleSwarmOptimization.jl/issues/24

**Comment by MrBenzWorld** [comment]
Thank you for your response.

**Comment by ablaom** [comment]
Closed as complete.
